CREATE OR REPLACE FUNCTION F_HOST_BALANCE
( V_HOST_CODE   IN    MEMBER.MEMBER_CODE%TYPE)

RETURN NUMBER

IS
    V_BALANCE NUMBER(20);
BEGIN

SELECT (SELECT NVL(SUM(AMOUNT), 0)
         FROM CAL_HISTORY
         WHERE HOST_CODE = V_HOST_CODE)
        -
        (SELECT NVL(SUM(HOST_EXCHANGE_AMOUNT), 0)
         FROM HOST_EXCHANGE_HISTORY
         WHERE HOST_CODE = V_HOST_CODE)
AS BALANCE INTO V_BALANCE
FROM DUAL;
RETURN V_BALANCE;
END;  