-- 환전 신청시 충전신청내역 테이블과 충전신청계좌정보 테이블에 데이터가 추가되어야 한다.
-- 이용자 환전 신청 프로시저
CREATE OR REPLACE PROCEDURE PRC_USER_EXC_REG
( V_MEMBER_CODE         IN  VARCHAR
, V_MEMBER_BANK_NUMBER  IN  VARCHAR
, V_EXCHANGE_AMOUNT         IN  NUMBER
)
IS

V_ME_SEQ VARCHAR2(20) := F_CODE('ME', ME_SEQ.NEXTVAL);

BEGIN

INSERT INTO MEMBER_EXCHANGE_LIST(MEMBER_EXCHANGE_CODE, MEMBER_CODE, MEMBER_EXCHANGE_AMOUNT, MEMBER_EXCHANGE_DATE)
VALUES(V_ME_SEQ, V_MEMBER_CODE, V_EXCHANGE_AMOUNT, SYSDATE);

INSERT INTO MEMBER_EXCHANGE_BANK_INFO (MEMBER_EXCHANGE_BANK_INFO_CODE, MEMBER_EXCHANGE_CODE, MEMBER_BANK_NUMBER) 
VALUES (F_CODE('MEBIF', MEBIF_SEQ.NEXTVAL), V_ME_SEQ, V_MEMBER_BANK_NUMBER);

-- 커밋
COMMIT;

END;




SELECT *
FROM MEMBER_EXCHANGE_BANK_INFO;