
--<<공간 검수 관리>>
-- 항목 : 검수신청코드 공간명 공간유형 

--공간 검수 관리 뷰(VIEW) 생성 
CREATE OR REPLACE VIEW ADMIN_INSPECT_LIST_VIEW
AS
SELECT IR.INSPECT_REG_CODE, LBIF.LOC_NAME, LOCT.LOC_TYPE
,(SELECT COUNT(*)
FROM INSPECT_PROC_LIST
WHERE INSPECT_REG_CODE = IR.INSPECT_REG_CODE ) AS COUNT
FROM INSPECT_REG_LIST IR JOIN LOC_BASIC_INFO LBIF
    ON IR.LOC_CODE = LBIF.LOC_CODE
        JOIN LOC_TYPE LOCT
            ON LOCT.LOC_TYPE_CODE = LBIF.LOC_TYPE_CODE;


-- * 확인
SELECT INSPECT_REG_CODE,LOC_NAME,LOC_TYPE,COUNT
FROM ADMIN_INSPECT_LIST_VIEW
WHERE COUNT<1;

--확인용 데이터 입력
INSERT INTO INSPECT_REG_LIST(INSPECT_REG_CODE, LOC_CODE, INSPECT_REG_DATE)
VALUES(F_CODE('IR', IR_SEQ.NEXTVAL), 'L000001', SYSDATE); 
COMMIT;

--<<공간 검수 상세보기>>

--검수처리 뷰만들기 (URL웹사이트,사업등록증,상세이미지는 따로 )

CREATE OR REPLACE VIEW ADMIN_INSPECT_PR_VIEW
AS
SELECT IR.INSPECT_REG_CODE,LBIF.LOC_NAME,LBIF.LOC_SHORT_INTRO,LBIF.LOC_INTRO,LBIF.LOC_ADDR,LBIF.LOC_DETAIL_ADDR
,LOCT.LOC_TYPE, LDIF.MIN_PEOPLE,LDIF.MAX_PEOPLE
,LC.LOC_TEL,LC.LOC_MAIN_TEL,LC.LOC_EMAIL
,BZ.BIZ_NAME,BZ.BIZ_CEO,BZ.BIZ_CEO_TYPE,BZ.BIZ_MAIN_TYPE,BZ.BIZ_SUB_TYPE,BZ.BIZ_ADDR,BZ.BIZ_LICENSE_NUMBER
,LUI.LOC_USE_HOUR,LUI.LOC_USE_DAY_OFF,LUI.LOC_USE_APPOINT_DAY_OFF
FROM  LOC_BASIC_INFO LBIF JOIN LOC_TYPE LOCT
    ON LBIF.LOC_TYPE_CODE = LOCT.LOC_TYPE_CODE
        JOIN inspect_reg_list IR
            ON LBIF.LOC_CODE = IR.LOC_CODE
                    JOIN LOC_DETAIL_INFO LDIF
                        ON LBIF.LOC_CODE = LDIF.LOC_CODE
                            JOIN LOC_CONTACT LC
                                ON LBIF.LOC_CODE = LC.LOC_CODE
                                    JOIN BIZ_INFO BZ
                                        ON LC.LOC_CODE = BZ.LOC_CODE
                                            JOIN LOC_USE_INFO LUI
                                                ON LC.LOC_CODE = LUI.LOC_CODE
                                                        ; 

 --확인
 SELECT INSPECT_REG_CODE,LOC_NAME,LOC_SHORT_INTRO,LOC_INTRO,LOC_ADDR,LOC_DETAIL_ADDR
,LOC_TYPE,MIN_PEOPLE,MAX_PEOPLE
,LOC_TEL,LOC_MAIN_TEL,LOC_EMAIL
,BIZ_NAME,BIZ_CEO,BIZ_CEO_TYPE,BIZ_MAIN_TYPE,BIZ_SUB_TYPE,BIZ_ADDR,BIZ_LICENSE_NUMBER
,LOC_USE_HOUR,LOC_USE_DAY_OFF,LOC_USE_APPOINT_DAY_OFF
FROM ADMIN_INSPECT_PR_VIEW
where INSPECT_REG_CODE='IR000001';


                   
                   
--시설안내
CREATE OR REPLACE VIEW FACILITY_INFO_VIEW
AS
SELECT FIF.FACILITY_CONTENT, LBIF.LOC_BASIC_INFO_CODE, IR.INSPECT_REG_CODE 
FROM FACILITY_INFO FIF JOIN LOC_BASIC_INFO LBIF
 ON FIF.LOC_BASIC_INFO_CODE = LBIF.LOC_BASIC_INFO_CODE
    JOIN  INSPECT_REG_LIST IR
        ON IR.LOC_CODE = LBIF.LOC_CODE;
        
--확인
SELECT FACILITY_CONTENT FROM FACILITY_INFO_VIEW
WHERE INSPECT_REG_CODE='IR000001';

--주의사항
CREATE OR REPLACE VIEW CAUTION_VIEW
AS
SELECT CAU.CAUTION_CONTENT, LBIF.LOC_BASIC_INFO_CODE, IR.INSPECT_REG_CODE 
FROM CAUTION CAU JOIN LOC_BASIC_INFO LBIF
 ON CAU.LOC_BASIC_INFO_CODE = LBIF.LOC_BASIC_INFO_CODE
    JOIN  INSPECT_REG_LIST IR
        ON IR.LOC_CODE = LBIF.LOC_CODE
--==>>View CAUTION_VIEW이(가) 생성되었습니다.

--확인
SELECT CAUTION_CONTENT FROM CAUTION_VIEW
WHERE INSPECT_REG_CODE='IR000001';

--URL웹사이트
CREATE OR REPLACE VIEW WEB_VIEW
AS
SELECT LW.LOC_WEB_URL, LDIF.LOC_DETAIL_INFO_CODE, IR.INSPECT_REG_CODE 
FROM LOC_WEB LW JOIN LOC_DETAIL_INFO LDIF
    ON  LW.LOC_DETAIL_INFO_CODE= LDIF.LOC_DETAIL_INFO_CODE 
        JOIN  INSPECT_REG_LIST IR
            ON IR.LOC_CODE = LDIF.LOC_CODE;
            
--확인
SELECT LOC_WEB_URL FROM WEB_VIEW
WHERE INSPECT_REG_CODE='IR000001';


--○hostQnaManager

--hostQnaManager 페이지 qna 목록 쿼리문
CREATE OR REPLACE VIEW QNA_REPLY_VIEW
AS
SELECT QR.QNA_REPLY_CODE,Q.LOC_CODE,Q.QNA_CONTENT,QR.QNA_CODE, H.HOST_CODE
,QR.QNA_REPLY_CONTENT,HP.HOST_NICKNAME
,QNA_REPLY_DATE
,(SELECT COUNT(*)
FROM QNA_REPLY_REMOVE
WHERE QNA_REPLY_CODE = QR.QNA_REPLY_CODE ) AS COUNT
FROM QNA Q JOIN QNA_REPLY QR
    ON Q.QNA_CODE = QR.QNA_CODE
        JOIN LOC L
            ON  Q.LOC_CODE = L.LOC_CODE
                JOIN HOST H
                    ON L.HOST_CODE = H.HOST_CODE
                        JOIN HOST_PROFILE HP    
                            ON H.HOST_CODE = HP.HOST_CODE;
                            
--확인
SELECT QNA_REPLY_CODE,QNA_CONTENT,QNA_REPLY_CONTENT,HOST_NICKNAME,QNA_REPLY_DATE,loc_code
FROM QNA_REPLY_VIEW;
WHERE LOC_CODE='L000001';

--확인용 데이터 입력
INSERT INTO QNA_REPLY (QNA_REPLY_CODE, QNA_CODE, QNA_REPLY_CONTENT, QNA_REPLY_DATE)
VALUES (F_CODE('QRE', QRE_SEQ.NEXTVAL), 'Q000001', '열한번째....그만할까', sysdate);            

--HOST QNA POPUP페이지
CREATE OR REPLACE VIEW QNA_REPLY_SECOND_VIEW
AS
SELECT Q.LOC_CODE,QNA_REPLY_DATE,MP.MEMBER_NICKNAME,Q.QNA_CONTENT,QR.QNA_CODE,HP.HOST_NICKNAME, H.HOST_CODE
,QR.QNA_REPLY_CONTENT,QR.QNA_REPLY_CODE
FROM QNA Q JOIN QNA_REPLY QR
    ON Q.QNA_CODE = QR.QNA_CODE
        JOIN LOC L
            ON  Q.LOC_CODE = L.LOC_CODE
                JOIN HOST H
                    ON L.HOST_CODE = H.HOST_CODE
                        JOIN HOST_PROFILE HP    
                            ON H.HOST_CODE = HP.HOST_CODE
                                JOIN MEMBER_PROFILE MP
                                    ON Q.MEMBER_CODE = MP.MEMBER_CODE;
--==>>View QNA_REPLY_SECOND_VIEW이(가) 생성되었습니다.


--확인
SELECT LOC_CODE, QNA_REPLY_DATE, MEMBER_NICKNAME, QNA_CONTENT
		,HOST_NICKNAME,QNA_REPLY_CONTENT
		FROM QNA_REPLY_SECOND_VIEW
		WHERE QNA_REPLY_CODE ='QRE000001';

--시퀀스
CREATE SEQUENCE QRRM_SEQ;

--==============================================================

--○hostReviewManager

--hostReviewManager 페이지 Review 목록 쿼리문
CREATE OR REPLACE VIEW RW_REPLY_VIEW
AS
SELECT RVRE.REVIEW_REPLY_CODE,RV.LOC_CODE,RV.REVIEW_CONTENT,RVRE.REVIEW_CODE, H.HOST_CODE
,RVRE.REVIEW_REPLY_CONTENT,HP.HOST_NICKNAME
,REVIEW_REPLY_DATE
,(SELECT COUNT(*)
FROM REVIEW_REPLY_REMOVE
WHERE REVIEW_REPLY_CODE = RVRE.REVIEW_REPLY_CODE ) AS COUNT
FROM REVIEW RV JOIN REVIEW_REPLY RVRE
    ON RV.REVIEW_CODE = RVRE.REVIEW_CODE
        JOIN LOC L
            ON  RV.LOC_CODE = L.LOC_CODE
                JOIN HOST H
                    ON L.HOST_CODE = H.HOST_CODE
                        JOIN HOST_PROFILE HP    
                            ON H.HOST_CODE = HP.HOST_CODE;
 -->>View RW_REPLY_VIEW이(가) 생성되었습니다.                     
                            
--확인
SELECT REVIEW_REPLY_CODE,REVIEW_CONTENT,REVIEW_REPLY_CONTENT,HOST_NICKNAME,REVIEW_REPLY_DATE
FROM RW_REPLY_VIEW
WHERE LOC_CODE='L000001';
                 

--HOST QNA POPUP페이지
CREATE OR REPLACE VIEW RW_REPLY_SECOND_VIEW
AS
SELECT RV.LOC_CODE,REVIEW_REPLY_DATE,MP.MEMBER_NICKNAME,RV.REVIEW_CONTENT,RVRE.REVIEW_CODE,HP.HOST_NICKNAME, H.HOST_CODE
,RVRE.REVIEW_REPLY_CONTENT,RVRE.REVIEW_REPLY_CODE
FROM REVIEW RV JOIN REVIEW_REPLY RVRE
    ON RV.REVIEW_CODE = RVRE.REVIEW_CODE
        JOIN LOC L
            ON  RV.LOC_CODE = L.LOC_CODE
                JOIN HOST H
                    ON L.HOST_CODE = H.HOST_CODE
                        JOIN HOST_PROFILE HP    
                            ON H.HOST_CODE = HP.HOST_CODE
                                JOIN MEMBER_PROFILE MP
                                    ON RV.MEMBER_CODE = MP.MEMBER_CODE;
--==>>View RW_REPLY_SECOND_VIEW이(가) 생성되었습니다.

-- 뷰 삭제                
-- DROP VIEW RW_REPLY_SECOND_VIEW;   

--확인
SELECT LOC_CODE, REVIEW_REPLY_DATE, MEMBER_NICKNAME, REVIEW_CONTENT
		,HOST_NICKNAME,REVIEW_REPLY_CONTENT
		FROM RW_REPLY_SECOND_VIEW
		WHERE REVIEW_REPLY_CODE ='RVRE000001';

CREATE SEQUENCE RVRERM_SEQ;
                    
--==============================================================

--○HELP Manager

--HELPManager 페이지 Review 목록 쿼리문
CREATE OR REPLACE VIEW  HELP_VIEW
AS
SELECT  HLP.HELP_CODE, BT.BOARD_TYPE, HLP.HELP_TITLE, HLP.HELP_CONTENT, HLP.HELP_DATE
FROM HELP HLP JOIN BOARD_TYPE BT
ON HLP.BOARD_TYPE_CODE = BT.BOARD_TYPE_CODE;

 -->>View HELP_VIEW이(가) 생성되었습니다.                     
                            
--확인
SELECT HELP_CODE, BOARD_TYPE, HELP_TITLE, HELP_CONTENT, HELP_DATE
FROM HELP_VIEW
WHERE HELP_CODE='HLP000001';

SELECT HELP_CODE, BOARD_TYPE, HELP_TITLE, HELP_DATE
FROM HELP_VIEW
ORDER BY HELP_DATE DESC;

--공지사항 뷰 생성
CREATE OR REPLACE VIEW  NOTICE_VIEW
AS
SELECT N.NOTICE_CODE, I.IMPORTANT_NOTICE, N.NOTICE_TITLE, N.NOTICE_CONTENT, N.NOTICE_DATE,N.IMPORTANT_NOTICE_CODE
FROM NOTICE N JOIN IMPORTANT_NOTICE I
ON N.IMPORTANT_NOTICE_CODE = I.IMPORTANT_NOTICE_CODE;
--==>>View NOTICE_VIEW이(가) 생성되었습니다.


CREATE OR REPLACE VIEW  UNOTICE_VIEW
AS
SELECT N.NOTICE_CODE, I.IMPORTANT_NOTICE, N.NOTICE_TITLE, N.NOTICE_CONTENT, N.NOTICE_DATE,N.IMPORTANT_NOTICE_CODE
FROM NOTICE N JOIN IMPORTANT_NOTICE I
ON N.IMPORTANT_NOTICE_CODE = I.IMPORTANT_NOTICE_CODE;
--==>>View UNOTICE_VIEW이(가) 생성되었습니다.





