------------------------------------------------------------------------------------------------?—‹ DELETEMEMBER
/*
deleteAccount(?˜¸?Š¤?Š¸, ?´?š©?ž ?™?¼) 1

?´?š©?ž
0. ?”„ë¡œí•„? •ë³´ì—?„œ ?šŒ?›ì½”ë“œ ?™•?¸
1. ?˜ˆ?•½?‚´?—­ ?‚¨?•„?žˆ?œ¼ë©? ?ƒˆ?‡´ ë¶ˆê?
2. / ë§ˆì¼ë¦¬ì? ?‚¨?•„?žˆ?œ¼ë©? ?ƒˆ?‡´ ë¶ˆê??Š¥
3. ?™˜? „ê³„ì¢Œ ?…Œ?´ë¸”ì—?„œ ?•´?‹¹ ê³„ì¢Œë²ˆí˜¸ë¡? ?´ë£¨ì–´ì§? ê²ƒë“¤ ?‚­? œ
4. ì¶©ì „?‹ ì²?ê³„ì¢Œ?—?„œ ?•´?‹¹ê³„ì¢Œë²ˆí˜¸ë¡? ?´ë£¨ì–´ì§„ê²ƒ?“¤ 
   ì°¾ì•„?„œ ?‚­? œ
5. ê³„ì¢Œë²ˆí˜¸ ?…Œ?´ë¸”ì—?„œ ê³„ì¢Œ ?‚­? œ
6. ?”„ë¡œí•„? •ë³´ì—?„œ ?šŒ?›ì½”ë“œ ì°¾ì•„ ?‚­? œ
7. ?ƒˆ?‡´?šŒ?› ?…Œ?´ë¸? insert
*/

--?? ?´?š©?ž ?‚­? œ ?ˆœ?„œ 
-- ?—‹ ?”„ë¡œí•„? •ë³´ì—?„œ ?šŒ?›ì½”ë“œ ?™•?¸
SELECT MEMBER_CODE
FROM MEMBER_PROFILE
WHERE MEMBER_NICKNAME='ê¹?ê°ìž';
-->
SELECT MEMBER_CODE FROM MEMBER_PROFILE WHERE MEMBER_NICKNAME='ê¹?ê°ìž'
;
SELECT * FROM MEMBER_BANK_INFO;

--?—‹ ë©¤ë²„?”„ë¡œí•„ ?…Œ?´ë¸”ì— ?žˆ?Š”ì§? ?™•?¸ ?†’ ?—†?œ¼ë©? ?“±ë¡í•˜ì§? ?•Š?? ë©¤ë²„
SELECT COUNT(*) AS COUNT
FROM MEMBER_PROFILE
WHERE MEMBER_CODE = 'M000009';
-->
SELECT COUNT(*) AS COUNT FROM MEMBER_PROFILE WHERE MEMBER_CODE = 'M000009'
;

--?—‹ ?˜ˆ?•½?‚´?—­ ?žˆ?Š”ì§? ?™•?¸ 
SELECT B.BOOK_CODE, B.MEMBER_CODE, AP.APPLY_PACKAGE_CODE, AP.APPLY_DATE
, P.PACKAGE_CODE, PF.LOC_CODE
FROM BOOK_LIST B
JOIN APPLY_PACKAGE AP
ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
JOIN PACKAGE P
ON AP.PACKAGE_CODE = P.PACKAGE_CODE
JOIN PACKAGE_FORM PF
ON P.PACKAGE_FORM_CODE = PF.PACKAGE_FORM_CODE
WHERE AP.APPLY_DATE > SYSDATE AND B.MEMBER_CODE='M000002';
-->
SELECT COUNT(*) AS COUNT FROM BOOK_LIST B JOIN APPLY_PACKAGE AP ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE JOIN PACKAGE P ON AP.PACKAGE_CODE = P.PACKAGE_CODE JOIN PACKAGE_FORM PF ON P.PACKAGE_FORM_CODE = PF.PACKAGE_FORM_CODE WHERE AP.APPLY_DATE > SYSDATE AND B.MEMBER_CODE='M000002'
;


--------------------------------------------------------------------- ë§ˆì¼ë¦¬ì?
--?—‹ ë§ˆì¼ë¦¬ì? ?‚´?—­ ?™•?¸ ë°©ë²• 
-- ì¶©ì „ì²˜ë¦¬?‚´?—­(ì²˜ë¦¬?œê²ƒë§Œ) ì¡°ì¸ / ì¶©ì „ì²˜ë¦¬ì½”ë“œ LOAD_TYPE_CODE='LT000001'
-- - ?˜ˆ?•½ê²°ì œ?‚´?—­ ì°¨ê°
-- + ?´?š©?žê°? ì·¨ì†Œ?•œ ?˜ˆ?•½ ?™˜ë¶? ?‚´?—­
-- + ?˜¸?Š¤?Š¸ê°? ì·¨ì†Œ?•œ ?˜ˆ?•½ ?™˜ë¶? ?‚´?—­
-- - ?´?š©?ž ?™˜? „ ê¸ˆì•¡
-------------------------------------------


-- ë§ˆì¼ë¦¬ì? ì¶©ì „ ?‚´?—­
SELECT NVL(SUM(LR.LOAD_AMOUNT), 0)
FROM LOAD_PROC LP
JOIN LOAD_REG LR
ON LP.LOAD_REG_CODE = LR.LOAD_REG_CODE
WHERE LP.LOAD_TYPE_CODE='LT000001' AND LR.MEMBER_CODE='M000003';

-- ?˜ˆ?•½ ê²°ì œ ?‚´?—­
SELECT NVL(SUM(P.PACKAGE_PRICE), 0)
FROM BOOK_PAY_LIST BP
JOIN BOOK_LIST B
ON BP.BOOK_CODE = B.BOOK_CODE
JOIN APPLY_PACKAGE AP
ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
JOIN PACKAGE P 
ON AP.PACKAGE_CODE = P.PACKAGE_CODE
WHERE B.MEMBER_CODE='M000002';

          
-- ?˜¸?Š¤?Š¸ê°? ì·¨ì†Œ?•œ ?˜ˆ?•½?˜ ê²½ìš°        
SELECT NVL(SUM(P.PACKAGE_PRICE), 0) AS HOST_CANCEL
FROM HOST_CANCEL_LIST HC
JOIN BOOK_REFUND_LIST BR
ON HC.BOOK_CODE = BR.BOOK_CODE
    JOIN BOOK_LIST B
    ON BR.BOOK_CODE = B.BOOK_CODE
        JOIN APPLY_PACKAGE AP
        ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
            JOIN PACKAGE P
            ON AP.PACKAGE_CODE = P.PACKAGE_CODE
            WHERE B.MEMBER_CODE = 'M000002';

-- ?´?š©?žê°? ì·¨ì†Œ?•œ ?˜ˆ?•½?˜ ê²½ìš°
-- ?´?š©?ž ì·¨ì†Œ?‹œ 7?¼? „ - 100% ?™˜ë¶?, 6~1?¼? „ - 50% ?™˜ë¶?
SELECT NVL(SUM
(CASE WHEN (TO_DATE(AP.APPLY_DATE, 'YYYY-MM-DD') - TO_DATE(MC.MEMBER_CANCEL_DATE, 'YYYY-MM-DD')) < 7 
      THEN TRUNC(P.PACKAGE_PRICE * 0.5, -1) -- ?´?š©?ž ì·¨ì†Œ?¼?žê°? ?Œ¨?‚¤ì§? ? ?š©?¼ 6?¼ ? „?¼ ê²½ìš° 50?”„ë¡?
      ELSE TRUNC(P.PACKAGE_PRICE * 1, -1)   -- ?•„?‹ê²½ìš° 100?”„ë¡? ?™˜ë¶?, ?‚˜ë¨¸ì? ?˜ˆ?™¸?ƒ?™©?? ?›¹?—?„œ ì²˜ë¦¬
      END), 0) AS MEMBER_CANCEL
FROM MEMBER_CANCEL_LIST MC
JOIN BOOK_REFUND_LIST BR
ON MC.BOOK_CODE = BR.BOOK_CODE
    JOIN BOOK_LIST B
    ON BR.BOOK_CODE = B.BOOK_CODE
        JOIN APPLY_PACKAGE AP
        ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
            JOIN PACKAGE P
            ON AP.PACKAGE_CODE = P.PACKAGE_CODE;
            --WHERE B.MEMBER_CODE = 'M000002';

-- ?´?š©?žê°? ?™˜? „?•œ ê¸ˆì•¡
SELECT NVL(SUM(MEMBER_EXCHANGE_AMOUNT), 0)
FROM MEMBER_EXCHANGE_LIST
WHERE MEMBER_CODE = 'M000002';

--?—‹ ë§ˆì¼ë¦¬ì? ?”„ë¡œì‹œ??
VARIABLE V_CHANGE NUMBER;

CALL PRC_MEMBER_MILEAGE('M000005', :V_CHANGE);

-- ê³„ì¢Œ? •ë³? ?žˆ?Š”ì§? ?™•?¸ (MEMBER_BANK_INFO)
SELECT MEMBER_BANK_NUMBER
FROM MEMBER_BANK_INFO
WHERE MEMBER_CODE='M000003';
--> 
SELECT MEMBER_BANK_NUMBER, MEMBER_CODE FROM MEMBER_BANK_INFO WHERE MEMBER_CODE='M000001'
;

--?—‹ MEMBER_EXCHANGE_BANK_INFO?—?„œ ê³„ì¢Œ? •ë³? ?‚­? œ 
DELETE MEMBER_EXCHANGE_BANK_INFO
WHERE MEMBER_BANK_NUMBER 
IN ( SELECT MEMBER_BANK_NUMBER
     FROM MEMBER_BANK_INFO
     WHERE MEMBER_CODE='M000003');
--> 
DELETE MEMBER_EXCHANGE_BANK_INFO WHERE MEMBER_BANK_NUMBER IN ( SELECT MEMBER_BANK_NUMBER FROM MEMBER_BANK_INFO WHERE MEMBER_CODE='M000003')
;

--?—‹ ì¶©ì „?‹ ì²?ê³„ì¢Œ?—?„œ ?•´?‹¹ê³„ì¢Œë²ˆí˜¸ë¡? ?´ë£¨ì–´ì§„ê²ƒ?“¤ ì°¾ì•„?„œ ?‚­? œ
DELETE LOAD_REG_BANK_INFO
WHERE MEMBER_BANK_NUMBER
IN ( SELECT MEMBER_BANK_NUMBER
     FROM MEMBER_BANK_INFO
     WHERE MEMBER_CODE='M000003');
-->
DELETE LOAD_REG_BANK_INFO WHERE MEMBER_BANK_NUMBER IN ( SELECT MEMBER_BANK_NUMBER FROM MEMBER_BANK_INFO WHERE MEMBER_CODE='M000003')
;

--?—‹ ë©¤ë²„ê³„ì¢Œ? •ë³´ì—?„œ ?•´?‹¹ê³„ì¢Œë²ˆí˜¸ ì°¾ì•„ ?‚­? œ
DELETE FROM MEMBER_BANK_INFO WHERE MEMBER_CODE='M000003';

--?—‹ ë©¤ë²„?”„ë¡œí•„?—?„œ ?•´?‹¹ë©¤ë²„ ?‚­? œ
DELETE FROM MEMBER_PROFILE WHERE MEMBER_CODE='M000003';

--?—‹ ?ƒˆ?‡´ ?…Œ?´ë¸? INSERT 
INSERT INTO MEMBER_WITHDRAW(MEMBER_WITHDRAW_CODE, MEMBER_CODE, MEMBER_WITHDRAW_DATE) 
VALUES(F_CODE('MW', MW_SEQ.NEXTVAL), 'M000003' ,SYSDATE);
;
--> ?•œì¤?
INSERT INTO MEMBER_WITHDRAW(MEMBER_WITHDRAW_CODE, MEMBER_CODE, MEMBER_WITHDRAW_DATE) VALUES(F_CODE('MW', MW_SEQ.NEXTVAL), 'M000003',SYSDATE)
;

----------------------------------------------------------------------------------------------
--?—‹ DELETEHOST

/*
?˜¸?Š¤?Š¸

0. ?”„ë¡œí•„? •ë³´ì—?„œ ?šŒ?›ì½”ë“œ ?™•?¸
1. ?˜ˆ?•½?‚´?—­ ?žˆ?œ¼ë©? ?ƒˆ?‡´ ë¶ˆê??Š¥
2. ë§ˆì¼ë¦¬ì? ?‚¨?•„?žˆ?œ¼ë©? ?ƒˆ?‡´ ë¶ˆê??Š¥ 
3. LOC_CONTACT?—?„œ ?—°?½ì²? ?‚­? œ
4. BIZ_INFO?—?„œ ?‚¬?—…?ž? •ë³? ?‚­? œ
5. LOC_REMOVE(LRM)?— ?‚­? œ?œ ê³µê°„?œ¼ë¡? INSERT
6. ?™˜? „ê³„ì¢Œ?—?„œ ?•´?‹¹ ê³„ì¢Œ? •ë³? DELETE
7. HOST_BANK_INFO?—?„œ ?•´?‹¹ ?šŒ?›ì½”ë“œ?˜ ê³„ì¢Œ? •ë³? DELETE
8. HOST_PROFILE?—?„œ ?•´?‹¹ ?šŒ?›ì½”ë“œ?¸ ?šŒ?›? •ë³? DELETE
9. HOST_WITHDRAW(HW) ?— ?•´?‹¹ ?šŒ?›ì½”ë“œ ?šŒ?› INSERT

*/

--?˜… ?˜¸?Š¤?Š¸ ?‚­? œ ?ˆœ?„œ

--?—‹ ?•´?‹¹ ê³µê°„?˜ ?˜ˆ?•½?‚´?—­ ?™•?¸
SELECT B.BOOK_CODE, AP.APPLY_PACKAGE_CODE, AP.APPLY_DATE
, P.PACKAGE_CODE, PF.LOC_CODE, L.HOST_CODE
FROM BOOK_LIST B
JOIN APPLY_PACKAGE AP
ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
JOIN PACKAGE P
ON AP.PACKAGE_CODE = P.PACKAGE_CODE
JOIN PACKAGE_FORM PF
ON P.PACKAGE_FORM_CODE = PF.PACKAGE_FORM_CODE
JOIN LOC L
ON PF.LOC_CODE = L.LOC_CODE
WHERE AP.APPLY_DATE > SYSDATE AND L.HOST_CODE='H000003';
-->
SELECT COUNT(*) AS COUNT FROM BOOK_LIST B JOIN APPLY_PACKAGE AP ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE JOIN PACKAGE P ON AP.PACKAGE_CODE = P.PACKAGE_CODE JOIN PACKAGE_FORM PF ON P.PACKAGE_FORM_CODE = PF.PACKAGE_FORM_CODE JOIN LOC L ON PF.LOC_CODE = L.LOC_CODE WHERE AP.APPLY_DATE > SYSDATE AND L.HOST_CODE='H000001'
;

-- ë§ˆì¼ë¦¬ì? ?‚´?—­ ?™•?¸
/*
?´?š©?žê°? ?˜ˆ?•½?„ ì·¨ì†Œ?•  ê²½ìš°, ?•´?‹¹ ?¼?„¼?Š¸ë§Œí¼ ì°¨ê°?œ ê°?ê²©ì´
?˜¸?Š¤?Š¸?—ê²? ?“¤?–´?˜¨?‹¤. [? •?‚° ?‚´?—­ ?…Œ?´ë¸”ì? ê·? ?¼?„¼?Š¸ë¥? ?´ë¯? ì°¨ê°?•œ ê¸ˆì•¡?ž„.] 

------------------------------
    ? •?‚° ?‚´?—­(?˜¸?Š¤?Š¸)           CAL ?…Œ?´ë¸? 
-   ë§ˆì¼ë¦¬ì? ?™˜? „ ?‚´?—­(?˜¸?Š¤?Š¸)  HOST_EXCHANGE_LIST ?…Œ?´ë¸? HE
-----------------------------------
*/

-- ?˜¸?Š¤?Š¸ ? •?‚° ?‚´?—­?—?„œ ê°?ê²? ê°?? ¸?˜¤ê¸?
SELECT NVL(SUM(P.PACKAGE_PRICE), 0) AS PACKAGE_PRICE
FROM CAL C 
JOIN BOOK_LIST B
ON C.BOOK_CODE = B.BOOK_CODE
JOIN APPLY_PACKAGE AP
ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
JOIN PACKAGE P
ON AP.PACKAGE_CODE = P.PACKAGE_CODE
WHERE HOST_CODE='H000001';


-- ?™˜? „ ?‚´?—­ 
SELECT NVL(SUM(HOST_EXCHANGE_AMOUNT), 0) AS HOST_EXCHANGE_AMOUNT
FROM HOST_EXCHANGE_LIST
WHERE HOST_CODE='H000001';

--?—‹ ?˜¸?Š¤?Š¸ ë§ˆì¼ë¦¬ì? ?ž”?•¡ êµ¬í•˜ê¸?
SELECT
(SELECT NVL(SUM(P.PACKAGE_PRICE), 0)
FROM CAL C 
JOIN BOOK_LIST B
ON C.BOOK_CODE = B.BOOK_CODE
JOIN APPLY_PACKAGE AP
ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
JOIN PACKAGE P
ON AP.PACKAGE_CODE = P.PACKAGE_CODE
WHERE HOST_CODE='H000003'
)
-
(SELECT NVL(SUM(HOST_EXCHANGE_AMOUNT), 0)
FROM HOST_EXCHANGE_LIST
WHERE HOST_CODE='H000003'
) AS MILEAGE
FROM DUAL;

--?—‹ ë©¤ë²„?”„ë¡œí•„ ?…Œ?´ë¸”ì— ?žˆ?Š”ì§? ?™•?¸ ?†’ ?—†?œ¼ë©? ?“±ë¡í•˜ì§? ?•Š?? ë©¤ë²„
SELECT COUNT(*) AS COUNT
FROM HOST_PROFILE
WHERE HOST_CODE = 'H000009';
-->
SELECT COUNT(*) AS COUNT FROM HOST_PROFILE WHERE HOST_CODE = 'H000009'
;

-- !! ?—¬?Ÿ¬ê°?] LOC ?…Œ?´ë¸”ì—?„œ ?•´?‹¹ ?šŒ?›ì½”ë“œ?˜ ê³µê°„ì½”ë“œ ì°¾ê¸°
SELECT LOC_CODE
FROM LOC
WHERE HOST_CODE = 'H000006';
-->
SELECT LOC_CODE FROM LOC WHERE HOST_CODE = 'H000004'
;

--?—‹ ë°›ì•„?˜¨ ê³µê°„ì½”ë“œ?“¤ë¡? LOC_CONTACT?—?„œ ?—°?½ì²? ?‚­? œ
DELETE LOC_CONTACT WHERE LOC_CODE IN (SELECT LOC_CODE FROM LOC WHERE HOST_CODE = 'H000004')
;

--?—‹ ë°›ì•„?˜¨ ê³µê°„ì½”ë“œ?“¤ë¡? BIZ_INFO?—?„œ ?‚¬?—…?ž? •ë³? ?‚­? œ
DELETE BIZ_INFO WHERE LOC_CODE IN (SELECT LOC_CODE FROM LOC WHERE HOST_CODE = 'H000004')
;

--?—‹ LOC_REMOVE(LRM)?— ?‚­? œ?œ ê³µê°„?œ¼ë¡? INSERT (?—¬?Ÿ¬ë²? ?•´ì¤˜ì•¼?•¨ )
CALL PRC_DEL_LOC_INSERT('H000006')
;
--INSERT INTO LOC_REMOVE(LOC_REMOVE_CODE, LOC_CODE, LOC_REMOVE_DATE)
--VALUES(F_CODE('LRM', LRM_SEQ.NEXTVAL), 'L000001', SYSDATE);


-- !! ?—¬?Ÿ¬ê°?] ê³„ì¢Œ? •ë³? ?žˆ?Š”ì§? ?™•?¸ (HOST_BANK_INFO)
SELECT HOST_BANK_NUMBER, HOST_CODE
FROM HOST_BANK_INFO
WHERE HOST_CODE='H000004';
--> 
SELECT HOST_BANK_NUMBER FROM HOST_BANK_INFO WHERE HOST_CODE='H000004'
;
-- ?—¬ê¸°ì„œ HOST_BANK_NUMBER ë°›ì•„?˜´

--?—‹ ?™˜? „ê³„ì¢Œ?—?„œ ?•´?‹¹ ê³„ì¢Œ? •ë³? DELETE
DELETE 
FROM HOST_EXCHANGE_BANK_INFO
WHERE HOST_BANK_NUMBER IN (SELECT HOST_BANK_NUMBER FROM HOST_BANK_INFO WHERE HOST_CODE='H000001');
-->
DELETE FROM HOST_EXCHANGE_BANK_INFO WHERE HOST_BANK_NUMBER IN (SELECT HOST_BANK_NUMBER FROM HOST_BANK_INFO WHERE HOST_CODE='H000001')
;

--?—‹ HOST_BANK_INFO?—?„œ ê³„ì¢Œë²ˆí˜¸ ?‚­? œ
DELETE FROM HOST_BANK_INFO WHERE HOST_CODE='H000004';

--?—‹ HOST_PROFILE?—?„œ ?˜¸?Š¤?Š¸ë²ˆí˜¸ ?‚­? œ 
DELETE FROM HOST_PROFILE WHERE HOST_CODE='H000004';

--?—‹ ?ƒˆ?‡´ ?…Œ?´ë¸? INSERT 
INSERT INTO HOST_WITHDRAW(HOST_WITHDRAW_CODE, HOST_CODE, HOST_WITHDRAW_DATE) 
VALUES(F_CODE('HW', HW_SEQ.NEXTVAL), 'H000002' ,SYSDATE);
--> ?•œì¤?
INSERT INTO HOST_WITHDRAW(HOST_WITHDRAW_CODE, HOST_CODE, HOST_WITHDRAW_DATE) VALUES(F_CODE('HW', HW_SEQ.NEXTVAL), 'H000002' ,SYSDATE)
;

----------------------------------------------------------------------------------------------
/*
*locationDetail 3
?—
1. ê³µê°„?…Œ?´ë¸”ì—?„œ ?˜ˆ?•½?•  ê³µê°„?˜ ? •ë³´ë?? ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬?
   1-1. ê³µê°„?†Œê°? : (?´?š©?•ˆ?‚´?…Œ?´ë¸?) ?˜?—…?‹œê°?, ? •ê¸°íœ´ë¬´ì¼, ì§?? •?œ´ë¬´ì¼
   1-2. ?‹œ?„¤?•ˆ?‚´ : (?‹œ?„¤?•ˆ?‚´?…Œ?´ë¸?) ?‹œ?„¤?•ˆ?‚´?‚´?š©
   1-3. ì£¼ì˜?‚¬?•­ : ì£¼ì˜?‚¬?•­.ì£¼ì˜?‚¬?•­ ?‚´?š©
   1-4. ?Œ¨?‚¤ì§? : ?˜„?ž¬ ? ?š©?œ ?Œ¨?‚¤ì§? ì¢…ë¥˜, ì¢…ë¥˜?—?”°?¼ ? ?š©?œ ?‚ ì§?
2. ?•´?‹¹ ê³µê°„?˜ ë¦¬ë·°ë¥? ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬?
   (?‰? , ë¦¬ë·°?‚´?š©, ë¦¬ë·°?ž‘?„±?¼?ž, ?‹‰?„¤?ž„, [?šŒ?›ì½”ë“œ])
   2-1. ?´ë¯¸ì?ê°? ?žˆ?Š” ê²½ìš° ?´ë¯¸ì??…Œ?´ë¸”ì„ ?†µ?•´ ì¡°íšŒ
   2-2. ?‚­? œ?‚´?—­?´ ?žˆ?Š” ê²½ìš° ?‚­? œ?œ ê²Œì‹œë¬¼ë¡œ ?•ˆ?‚´?•˜?Š” ë¸”ë¼?¸?“œ ì²˜ë¦¬
3. ?•´?‹¹ ê³µê°„?˜ Q&Aë¥? ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬?
   3-1. ?‚­? œ?‚´?—­?´ ?žˆ?Š” ê²½ìš° ?‚­? œ?œ ê²Œì‹œë¬¼ë¡œ ?•ˆ?‚´?•˜?Š” ë¸”ë¼?¸?“œ ì²˜ë¦¬	
4. ?•´?‹¹ ë¦¬ë·°?˜ ë¦¬ë·°?‹µê¸??„ ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬?
   4-1. ?‚­? œ?‚´?—­?´ ?žˆ?Š” ê²½ìš° ?‚­? œ?œ ê²Œì‹œë¬¼ë¡œ ?•ˆ?‚´?•˜?Š” ë¸”ë¼?¸?“œ ì²˜ë¦¬
5. ?•´?‹¹ Q&A?˜ Q&A?‹µê¸??„ ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬? 
   5-1. ?‚­? œ?‚´?—­?´ ?žˆ?Š” ê²½ìš° ?‚­? œ?œ ê²Œì‹œë¬¼ë¡œ ?•ˆ?‚´?•˜?Š” ë¸”ë¼?¸?“œ ì²˜ë¦¬

?™¥
1. ?‹µê¸??´ ì¡´ìž¬?•˜?Š” ê²½ìš° ê·? ?‹µê¸??´ ì°¸ì¡°?•˜ê³? ?žˆ?Š” ë¦¬ë·°, Q&A ë°‘ì— ?˜¬ ?ˆ˜ ?žˆ?„ë¡? ?•œ?‹¤.
2. ì§??„ API
3. ë¦¬ë·°, Q&A ëª©ë¡ ?ƒ?„±?‹œ ?˜„?ž¬ ?„¸?…˜?˜ ?šŒ?› ì½”ë“œê°? ê°™ì„ ê²½ìš° ?ˆ˜? • ë°? ?‚­? œ ë²„íŠ¼?„ ?™œ?„±?™” ?‹œ?‚¨?‹¤.
4. ë¦¬ë·°?Š” ?•œë²ˆë§Œ ?ž‘?„±?´ ê°??Š¥?•˜?‹¤. ?˜„?ž¬ ?„¸?…˜ê³? ê°™ì? ?šŒ?›ì½”ë“œ?˜ ë¦¬ë·°ê°? ì¡´ìž¬?•˜?Š” ê²½ìš°?Š” 
?´ë¯? ?ž‘?„±?•œ ?´? ¥?´ ?žˆ?‹¤?Š” ê²ƒìœ¼ë¡? ?›„ê¸? ?ž‘?„±?´ ë¶ˆê??Š¥?•˜?‹¤.  
5. ?˜ˆ?•½?„ ?ƒ?—?„œ ?‚ ì§œë?? ?ˆ„ë¥´ë©´(?Œ¨?‚¤ì§? ? ?š©?œ ?‚ ì§œë§Œ ?™œ?„±?™”) ?•´?‹¹ ?‚ ì§œì— 
?žˆ?Š” ?Œ¨?‚¤ì§??“¤?´ ?¼?””?˜¤ ë°•ìŠ¤ ?˜•?‹?œ¼ë¡? ë³´ì—¬ì§?ê³? ?¼?””?˜¤ ë²„íŠ¼?„ ?´ë¦??•˜ë©? ê²°ì œê°? ê°??Š¥
*/

SELECT *
FROM LOC_BASIC_INFO;

--?—‹ ê¸°ë³¸? •ë³? -- ?“±ë¡ì™„ë£Œëœ ê³µê°„?“¤?´ ?– ?•¼?•¨
SELECT LB.LOC_NAME, LT.LOC_TYPE
, LB.LOC_SHORT_INTRO, LB.LOC_INTRO
, LB.LOC_ADDR, LB.LOC_DETAIL_ADDR
, LD.MIN_PEOPLE, LD.MAX_PEOPLE
, L.LOC_REG_DATE, H.HOST_NICKNAME
FROM LOC_BASIC_INFO LB
JOIN LOC_TYPE LT 
ON LB.LOC_TYPE_CODE = LT.LOC_TYPE_CODE
    JOIN LOC_DETAIL_INFO LD
    ON LB.LOC_CODE = LD.LOC_CODE
        JOIN LOC L
        ON LB.LOC_CODE = L.LOC_CODE
            JOIN HOST_PROFILE H
            ON L.HOST_CODE = H.HOST_CODE;
--> ë·°ë¡œ ?ž‘?—…
SELECT LOC_NAME, LOC_TYPE, LOC_SHORT_INTRO, LOC_INTRO
, LOC_ADDR, LOC_DETAIL_ADDR, MIN_PEOPLE, MAX_PEOPLE
, LOC_REG_DATE, HOST_NICKNAME, HOST_CODE
FROM VIEW_BASIC_INFO
WHERE LOC_CODE = 'L000001';

SELECT *
FROM LOC;

SELECT *
FROM LOC_DETAIL_INFO;







--?—‹ ê³µê°„?†Œê°? 
SELECT LOC_USE_HOUR, LOC_USE_DAY_OFF, LOC_USE_APPOINT_DAY_OFF
FROM LOC_USE_INFO
WHERE LOC_CODE='L000001';
--> 
SELECT LOC_USE_HOUR, LOC_USE_DAY_OFF, LOC_USE_APPOINT_DAY_OFF, LOC_CODE
FROM VIEW_USING_HOUR
WHERE LOC_CODE='L000001';

--?—‹ ?‹œ?„¤?•ˆ?‚´
SELECT F.FACILITY_CODE, F.LOC_BASIC_INFO_CODE, F.FACILITY_CONTENT
, L.LOC_CODE 
FROM FACILITY_INFO F
JOIN LOC_BASIC_INFO L
ON F.LOC_BASIC_INFO_CODE = L.LOC_BASIC_INFO_CODE
WHERE LOC_CODE='L000001';
--> ë·?
SELECT FACILITY_CONTENT FROM VIEW_FACILITY_INFO WHERE LOC_CODE='L000001'
;


--?—‹ ì£¼ì˜?‚¬?•­
SELECT CAUTION_CONTENT
FROM CAUTION C
JOIN LOC_BASIC_INFO L
ON C.LOC_BASIC_INFO_CODE = L.LOC_BASIC_INFO_CODE
WHERE LOC_CODE='L000001';
--> ë·?
SELECT CAUTION_CONTENT FROM VIEW_CAUTION_CONTENT 
WHERE LOC_CODE='L000001'
;

--?—‹ ?•´?‹¹ ê³µê°„?— ? ?š©?œ ?Œ¨?‚¤ì§? 
--> ë·? ?ƒ?„±
SELECT LOC_CODE, PACKAGE_NAME, PACKAGE_START, PACKAGE_END
, PACKAGE_PRICE, APPLY_DATE, APPLY_PACKAGE_CODE
, COUNT
FROM VIEW_APPLY_PACKAGE_INFO;
WHERE LOC_CODE = 'L000006' AND APPLY_DATE='2021-02-02' AND COUNT=0;

--?—‹ ?‚¬?—…?ž? •ë³?
SELECT BIZ_NAME, BIZ_CEO, BIZ_CEO_TYPE,
BIZ_MAIN_TYPE, BIZ_SUB_TYPE, BIZ_LICENSE_NUMBER
FROM BIZ_INFO B
WHERE LOC_CODE='L000001';
    



--?—‹ QNA ì¡°íšŒ
SELECT Q.LOC_CODE, Q.QNA_CODE, Q.MEMBER_CODE, Q.QNA_CONTENT, Q.QNA_DATE
, NVL(M.MEMBER_NICKNAME, '(?•Œ?ˆ˜?—†?Œ)') AS MEMBER_NICKNAME
, (SELECT COUNT(*) FROM QNA_REPLY QR WHERE Q.QNA_CODE=QR.QNA_CODE) AS REPLYCOUNT
, (SELECT COUNT(*) FROM QNA_REMOVE QRM WHERE Q.QNA_CODE=QRM.QNA_CODE) AS QNAREMOVECOUNT
, (SELECT COUNT(*) FROM QNA_REPLY_REMOVE QRM WHERE QR.QNA_REPLY_CODE=QRM.QNA_REPLY_CODE) AS QNAREPLYREMOVECOUNT
, L.HOST_CODE, QR.QNA_REPLY_CONTENT, QR.QNA_REPLY_DATE, L.HOST_CODE, QR.QNA_REPLY_CODE
FROM QNA Q
LEFT JOIN MEMBER_PROFILE M      -- LEFT ì¡°ì¸ ?•´?•¼ ?ƒˆ?‡´?šŒ?›?´ë¦? ?‘œ?‹œê°??Š¥
ON Q.MEMBER_CODE = M.MEMBER_CODE
    LEFT JOIN QNA_REPLY QR
    ON Q.QNA_CODE = QR.QNA_CODE
        JOIN LOC L
        ON Q.LOC_CODE = L.LOC_CODE;
--> ë·? ë§Œë“¤ê¸?
SELECT QNA_CODE, MEMBER_NICKNAME, QNA_CONTENT, QNA_DATE, MEMBER_CODE, REPLYCOUNT
, QNAREMOVECOUNT, QNAREPLYREMOVECOUNT
, HOST_CODE, QNA_REPLY_CONTENT, QNA_REPLY_DATE, QNA_REPLY_CODE
FROM VIEW_QNA
WHERE LOC_CODE='L000001';


--?—‹ ?•´?‹¹ ê³µê°„?˜ q&a ê°??ˆ˜
SELECT COUNT(*) AS COUNT FROM VIEW_QNA WHERE LOC_CODE='L000001'
;


--?—‹ QNA ?‹µê¸? ì¡°íšŒ
SELECT QNA_REPLY_CONTENT, QNA_REPLY_DATE
FROM QNA_REPLY QR;

--?—‹ ë¦¬ë·° ì¡°íšŒ
SELECT R.REVIEW_CODE, NVL(M.MEMBER_NICKNAME, '(?•Œ?ˆ˜?—†?Œ)') AS MEMBER_NICKNAME
, R.LOC_CODE, R.REVIEW_RATE, R.REVIEW_CONTENT, R.REVIEW_DATE
, RVIMG.REVIEW_IMG_URL
, (SELECT COUNT(*) FROM REVIEW_IMG RVIMG
    WHERE R.REVIEW_CODE=RVIMG.REVIEW_CODE) AS RVIMGCOUNT
, (SELECT COUNT(*) FROM REVIEW_REMOVE RVRM 
    WHERE R.REVIEW_CODE=RVRM.REVIEW_CODE) AS REVIEWREMOVECOUNT
, (SELECT COUNT(*) FROM REVIEW_REPLY RR 
    WHERE R.REVIEW_CODE=RR.REVIEW_CODE) AS REPLYCOUNT
, (SELECT COUNT(*) FROM REVIEW_REPLY_REMOVE RRM 
    WHERE RR.REVIEW_REPLY_CODE=RRM.REVIEW_REPLY_CODE) AS REPLYREMOVECOUNT
, M.MEMBER_CODE, RR.REVIEW_REPLY_CONTENT, RR.REVIEW_REPLY_DATE, L.HOST_CODE
, RR.REVIEW_REPLY_CODE
FROM REVIEW R
LEFT JOIN MEMBER_PROFILE M
ON R.MEMBER_CODE = M.MEMBER_CODE
    LEFT JOIN REVIEW_IMG RVIMG
    ON R.REVIEW_CODE = RVIMG.REVIEW_CODE
        LEFT JOIN REVIEW_REPLY RR
        ON R.REVIEW_CODE = RR.REVIEW_CODE
            JOIN LOC L
            ON R.LOC_CODE = L.LOC_CODE
ORDER BY R.REVIEW_DATE DESC;
-->ë·?
SELECT REVIEW_CODE, MEMBER_NICKNAME, REVIEW_RATE, REVIEW_CONTENT, REVIEW_DATE
, REVIEW_IMG_URL, RVIMGCOUNT, REVIEWREMOVECOUNT, REPLYCOUNT, REPLYREMOVECOUNT
, MEMBER_CODE, REVIEW_REPLY_CONTENT, REVIEW_REPLY_DATE, HOST_CODE, REVIEW_REPLY_CODE
FROM VIEW_REVIEW WHERE LOC_CODE='L000003'
;


--?—‹ ?•´?‹¹ ê³µê°„?˜ ë¦¬ë·° ê°??ˆ˜
SELECT * FROM VIEW_REVIEW WHERE LOC_CODE='L000001'
;

--?—‹ ?´?š©?ž : QnA ?ž‘?„±
INSERT INTO QNA(QNA_CODE, LOC_CODE, MEMBER_CODE, QNA_CONTENT, QNA_DATE)
VALUES(F_CODE('Q', Q_SEQ.NEXTVAL), 'L000001' ,'M000001', '?ž…? ¥ë°›ì? ?‚´?š© ?„˜ê¸°ê¸°', SYSDATE)
;

--?—‹ ?´?š©?ž : QnA ?ˆ˜? •?•  ?‚´?š© ê°?? ¸?˜¤ê¸?
SELECT QNA_CODE, LOC_CODE, QNA_CONTENT
FROM QNA
WHERE QNA_CODE='Q000024';


--?—‹ ?´?š©?ž : QnA ?ˆ˜? •
UPDATE QNA SET QNA_CONTENT = '?ˆ˜? •?•œ ì½˜í…ì¸ ìž…?‹ˆ?‹¤.', QNA_DATE=SYSDATE WHERE QNA_CODE = 'Q000001';
;

--?—‹ ?´?š©?ž : QnA ?‚­? œ
INSERT INTO QNA_REMOVE (QNA_REMOVE_CODE, QNA_CODE, QNA_REMOVE_DATE) VALUES(F_CODE('QRM', QRM_SEQ.NEXTVAL), 'Q000001', SYSDATE)
;

--?—‹ ?´?š©?ž ?´?š©?‚´?—­?—¬ë¶? ?™•?¸(?›„ê¸°ìž‘?„± ë²„íŠ¼ ì¶œë ¥?—¬ë¶?)
SELECT B.MEMBER_CODE, A.APPLY_PACKAGE_CODE, F.LOC_CODE
, A.APPLY_DATE
FROM BOOK_LIST B
JOIN APPLY_PACKAGE A
ON B.APPLY_PACKAGE_CODE = A.APPLY_PACKAGE_CODE
    JOIN PACKAGE P
    ON A.PACKAGE_CODE = P.PACKAGE_CODE
        JOIN PACKAGE_FORM F
        ON P.PACKAGE_FORM_CODE = F.PACKAGE_FORM_CODE
WHERE NOT EXISTS (SELECT MCL.BOOK_CODE FROM MEMBER_CANCEL_LIST MCL);
-- ë·? ?™•?¸
SELECT COUNT(*) AS COUNT
FROM VIEW_MEMBER_BOOK
WHERE MEMBER_CODE='M000001';

SELECT BOOK_CODE
FROM MEMBER_CANCEL_LIST;


-- 1. ?•´?‹¹ ê³µê°„?— ???•´ ì·¨ì†Œ?˜ì§? ?•Š?? ?˜ˆ?•½ ?šŸ?ˆ˜ê°?... 1 ?´?ƒ?´ê³? 
-- 2. ?•´?‹¹ ê³µê°„?— ???•´ ?ž‘?„±?•œ ë¦¬ë·°ê°œìˆ˜ê°? ?˜ˆ?•½?šŸ?ˆ˜ë³´ë‹¤ ?ž‘?œ¼ë©?...!

----------------------------------------------------------------------------------------------
/*
* bookApply 5
?—
1. ê³µê°„?…Œ?´ë¸”ì—?„œ ?˜ˆ?•½?•  ê³µê°„?˜ ? •ë³´ë?? ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬?
   1-1. ê¸°ë³¸?„¤ëª? : ê³µê°„?„¤ëª?(ê³µê°„?•œì¤„ì†Œê°?), ê³µê°„?œ ?˜•, ?˜ˆ?•½?¸?›(ìµœì†Œ,ìµœë?)
   1-2. ?˜ˆ?•½? •ë³? : ?˜ˆ?•½?‚ ì§?(? ?š©?Œ¨?‚¤ì§?.? ?š©?¼?ž), ?˜ˆ?•½?¸?›(? „?Ž˜?´ì§?ë¡œë??„° ë°›ì•„?˜´)
   1-3. ?˜ˆ?•½?ž? •ë³? : (?””?´?Š¸ê°’ìœ¼ë¡? ?•˜?Š”ê²½ìš°)?šŒ?›? •ë³?(?´ë¦?, ?´ë©”ì¼, ?—°?½ì²?)
   1-4. ?˜¸?Š¤?Š¸? •ë³? : ê³µê°„?ƒ?˜¸ëª?, ???‘œ?žëª?, ?†Œ?ž¬ì§?, ?‚¬?—…?žë²ˆí˜¸, ?—°?½ì²?(?´ë©”ì¼, ?œ´???°, ???‘œ? „?™”)
   1-5. ì£¼ì˜?‚¬?•­ : ì£¼ì˜?‚¬?•­.ì£¼ì˜?‚¬?•­ ?‚´?š©
?™¥
1. ?˜ˆ?•½?ž? •ë³´ëŠ” ì§ì ‘ ?ž…? ¥?„ ê°??Š¥?•˜ì§?ë§? ì²´í¬ ë²„íŠ¼?„ ?†µ?•´ ?˜„?ž¬ ë¡œê·¸?¸?•œ ?šŒ?›?˜ ? •ë³´ë?? ?””?´?Š¸ê°’ìœ¼ë¡? ë°›ì•„?˜¬ ?ˆ˜ ?žˆ?„ë¡? 
2. ?•„?ˆ˜?ž…? ¥?‚¬?•­ ë¯¸ìž…? ¥, ?„œë¹„ìŠ¤ ?™?˜ë¥? ?•˜ì§? ?•Š?œ¼ë©? ê²°ì œ ë¶ˆê??Š¥
*/


--?—‹ ?˜ˆ?•½?ž? •ë³?
SELECT MEMBER_NAME, MEMBER_EMAIL, MEMBER_TEL, MEMBER_CODE, 
FROM MEMBER_PROFILE;

--?—‹ ?‚¬?—…?ž? •ë³?
SELECT B.BIZ_NAME, B.BIZ_CEO, B.BIZ_CEO_TYPE,
B.BIZ_MAIN_TYPE, B.BIZ_SUB_TYPE, B.BIZ_LICENSE_NUMBER
, LC.LOC_EMAIL, LC.LOC_TEL, LC.LOC_MAIN_TEL
, B.BIZ_ADDR, B.LOC_CODE
FROM BIZ_INFO B
    JOIN LOC_CONTACT LC
    ON B.LOC_CODE = LC.LOC_CODE
WHERE B.LOC_CODE='L000001';
--
SELECT LOC_CODE, BIZ_NAME, BIZ_CEO, BIZ_LICENSE_NUMBER
, BIZ_ADDR, LOC_EMAIL, LOC_TEL, LOC_MAIN_TEL 
FROM VIEW_BIZ_CONTACT
WHERE LOC_CODE = 'L000001';

--?—‹ ë©¤ë²„ ?”„ë¡œí•„ ê°?? ¸?˜¤ê¸?
SELECT MEMBER_CODE, MEMBER_NAME, MEMBER_TEL
FROM MEMBER_PROFILE
WHERE MEMBER_CODE='M000004';


--?—‹ ?„ ?ƒ?•œ ?Œ¨?‚¤ì§? ? •ë³? ì¡°íšŒ(?Œ¨?‚¤ì§?ì½”ë“œ ?ž…? ¥?‹œ ?™•?¸ê°??Š¥)
SELECT PF.LOC_CODE, P.PACKAGE_CODE, P.PACKAGE_FORM_CODE, P.PACKAGE_NAME
, P.PACKAGE_START, P.PACKAGE_END, P.PACKAGE_PRICE, AP.APPLY_DATE, AP.APPLY_PACKAGE_CODE
FROM PACKAGE P
JOIN PACKAGE_FORM PF
ON P.PACKAGE_FORM_CODE = PF.PACKAGE_FORM_CODE
    JOIN APPLY_PACKAGE AP
    ON P.PACKAGE_CODE = AP.PACKAGE_CODE;
--> ë·°ë¡œ ë³´ê¸°
SELECT PACKAGE_NAME, APPLY_PACKAGE_CODE
, PACKAGE_START, PACKAGE_END, PACKAGE_PRICE, APPLY_DATE
, NVL(PACKAGE_END, 0) - NVL(PACKAGE_START, 0) AS HOURS
FROM VIEW_APPLY_PACKAGE_INFO
WHERE APPLY_PACKAGE_CODE = 'AP000004';


--?—‹ ë§ˆì¼ë¦¬ì? ?žˆ?œ¼ë©? ?˜ˆ?•½ ?‚´?—­?…Œ?´ë¸? insert
INSERT INTO BOOK_LIST (BOOK_CODE, MEMBER_CODE, APPLY_PACKAGE_CODE
, BOOK_PEOPLE, BOOK_DATE, BOOK_REQ)
VALUES(F_CODE('BC', BC_SEQ.NEXTVAL), 'M000001', 'AP000001', 3, SYSDATE, '?ž˜?•´ì£¼ì„¸?š”');

--?—‹ ë°©ê¸ˆ ?•œ ?˜ˆ?•½ë²ˆí˜¸ ê°?? ¸?˜´
SELECT BOOK_CODE
FROM 
(SELECT BOOK_CODE FROM BOOK_LIST WHERE MEMBER_CODE='M000001' ORDER BY BOOK_CODE DESC)
WHERE ROWNUM=1;

--?—‹ ?‹¤?˜ˆ?•½?ž ?…Œ?´ë¸? insert
INSERT INTO ACTUAL_BOOKER (ACTUAL_BOOKER_CODE, BOOK_CODE, ACTUAL_BOOKER
, ACTUAL_BOOKER_TEL)
VALUES(F_CODE('AB', AB_SEQ.NEXTVAL), 'BC000006', 'ì§„ì§œ?˜??', '010-3690-7828');


--?—‹ ?˜ˆ?•½ê²°ì œ?‚´?—­ ?…Œ?´ë¸? insert
INSERT INTO BOOK_PAY_LIST(BOOK_PAY_CODE, BOOK_CODE, BOOK_PAY_DATE)
VALUES(F_CODE('BP', BP_SEQ.NEXTVAL), 'BC000006', SYSDATE);


--?—‹ ë§ˆì¼ë¦¬ì? ?—†?œ¼ë©? ê²°ì œ?Ž˜?´ì§?ë¡? ?´?™

insert into load_reg(load_reg_code, member_code, load_amount, load_reg_date)
values(F_CODE('LR',LR_SEQ.NEXTVAL), 'M000002', '500000', SYSDATE);

COMMIT;

INSERT INTO LOAD_PROC(LOAD_PROC_CODE, LOAD_REG_CODE, LOAD_TYPE_CODE, LOAD_PROC_DATE)
VALUES(F_CODE('LP', LP_SEQ.NEXTVAL), 'LR000008', 'LT000001', SYSDATE);

update apply_package
set 
apply_date = to_date('2021-02-02', 'yyyy-mm-dd')
where apply_package_code='AP000004';

select *
from book_list;

EXEC PRC_BOOK_CODE_INSERT('M000002', 'ê¹??•„ë¬´ê°œ', '010-3690-7828');


--------------------------------------------------------------------------------
--?? BookApplyNotice.jsp
/*
ê²°ì œ?‚´?—­ ?™•?¸
?˜ˆ?•½?žëª?
ì§„ì˜??
?—°?½ì²?
010-1234-1234
?´ë©”ì¼
papajon@lookation.com
?¸?›?ˆ˜
3ëª?
?š”ì²??‚¬?•­
ê³ í†µ?„ ë©ˆì¶°ì£¼ì„¸?š”
ê²°ì œê¸ˆì•¡
200,000

*/
SELECT A.ACTUAL_BOOKER, A.ACTUAL_BOOKER_TEL, B.BOOK_PEOPLE, B.BOOK_DATE, B.BOOK_REQ
, AP.APPLY_DATE, P.PACKAGE_NAME, P.PACKAGE_START, P.PACKAGE_END
, P.PACKAGE_PRICE
FROM BOOK_LIST B
    JOIN ACTUAL_BOOKER A
    ON B.BOOK_CODE = A.BOOK_CODE
        JOIN APPLY_PACKAGE AP
        ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
            LEFT JOIN PACKAGE P
            ON AP.PACKAGE_CODE = P.PACKAGE_CODE;

SELECT BOOK_CODE, ACTUAL_BOOKER, ACTUAL_BOOKER_TEL, BOOK_PEOPLE, BOOK_REQ
, APPLY_DATE, PACKAGE_NAME, PACKAGE_START, PACKAGE_END
, PACKAGE_PRICE
FROM VIEW_BOOKAPPLYNOTICE
WHERE BOOK_CODE = (SELECT BOOK_CODE
                     FROM 
                    (SELECT BOOK_CODE 
                       FROM BOOK_LIST 
                      WHERE MEMBER_CODE='M000005' 
                   ORDER BY BOOK_CODE DESC)
                   WHERE ROWNUM=1);
                   
                   
/*
* bookList 5
?—
1. ?˜ˆ?•½ ?…Œ?´ë¸? ? •ë³´ë?? ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬?
   (?˜ˆ?•½ì½”ë“œ, ?˜ˆ?•½?žëª?, ê³µê°„ëª?, ?¼?ž, ?¸?›?ˆ˜, ê°?ê²?, ?š”ì²??‚¬?•­, ?ƒ?ƒœ)
2. ?˜ˆ?•½ì·¨ì†Œ ?´ë¦??‹œ ?˜ˆ?•½ì·¨ì†Œ ?…Œ?´ë¸”ì— ?°?´?„° INSERT ì¿¼ë¦¬ë¬? 
?™¥
1. ê²??ƒ‰?? ?• ?•„?š” ?—†?Œ
2. ìµœì‹  ?ˆœ?œ¼ë¡? ? •? ¬ ?•„?š”.
3. ê³µê°„ëª…ì„ ?‚˜?˜¤ê²? ?•˜ê³? ?ƒ?„¸ë³´ê¸° ?Œ?—…?œ¼ë¡?(?˜ˆ?•½?¸?›?ˆ˜, ?š”ì²??‚¬?•­, ê°?ê²?)
   ?‚˜ë¨¸ì?(?˜ˆ?•½ì½”ë“œ, ?˜ˆ?•½?žëª?, ?˜ˆ?•½?˜„?™©, ?˜ˆ?•½ì·¨ì†Œ)?Š” ë¦¬ìŠ¤?Š¸ë¡? ë³´ì—¬ì¤?
4. ì·¨ì†Œ ?´ë¦??‹œ ì·¨ì†Œ?‚¬?œ ë¥? ?ž…? ¥?•˜ê¸? ?œ„?•œ ?Œ?—…ì°½ì´ ?•„?š”


*/

-- ?˜ˆ?•½?‚´?š©(?Œ¨?‚¤ì§? ?‚ ì§?, ?‹œê°? ì´? ëª‡ì‹œê°?) ê³µê°„ëª? ?˜ˆ?•½?˜„?™©, 
SELECT DISTINCT B.BOOK_CODE, B.MEMBER_CODE, A.APPLY_PACKAGE_CODE, F.LOC_CODE
, TO_DATE(A.APPLY_DATE,'YYYY-MM-DD') AS APPLY_DATE, P.PACKAGE_CODE, P.PACKAGE_NAME
, P.PACKAGE_START, P.PACKAGE_END
, NVL(P.PACKAGE_END, 0) - NVL(P.PACKAGE_START, 0) AS BOOK_HOUR
, (SELECT COUNT(*) FROM HOST_CANCEL_LIST HC WHERE B.BOOK_CODE = HC.BOOK_CODE) AS HOST_CANCEL
, (SELECT COUNT(*) FROM MEMBER_CANCEL_LIST MC WHERE B.BOOK_CODE = MC.BOOK_CODE) AS MEMBER_CANCEL
, (SELECT COUNT(*) FROM BOOK_REFUND_LIST BRF WHERE B.BOOK_CODE = BRF.BOOK_CODE) AS REFUND
, LBIF.LOC_NAME, AB.ACTUAL_BOOKER, AB.ACTUAL_BOOKER_TEL
, B.BOOK_PEOPLE, BOOK_DATE, BOOK_REQ, P.PACKAGE_PRICE
, BZ.BIZ_NAME, BZ.BIZ_CEO, BIZ_LICENSE_NUMBER
, MC.MEMBER_CANCEL_REASON, HC.HOST_CANCEL_REASON
, MP.MEMBER_EMAIL, LBIF.LOC_ADDR, LBIF.LOC_DETAIL_ADDR
, MP.MEMBER_NICKNAME
FROM BOOK_LIST B
JOIN APPLY_PACKAGE A
ON B.APPLY_PACKAGE_CODE = A.APPLY_PACKAGE_CODE
    JOIN PACKAGE P
    ON A.PACKAGE_CODE = P.PACKAGE_CODE
        JOIN PACKAGE_FORM F
        ON P.PACKAGE_FORM_CODE = F.PACKAGE_FORM_CODE
            JOIN REVIEW R
            ON B.MEMBER_CODE = R.MEMBER_CODE
                JOIN LOC_BASIC_INFO LBIF
                ON F.LOC_CODE = LBIF.LOC_CODE
                    JOIN ACTUAL_BOOKER AB
                    ON B.BOOK_CODE=AB.BOOK_CODE
                        JOIN BIZ_INFO BZ
                        ON F.LOC_CODE = BZ.LOC_CODE
                            LEFT JOIN HOST_CANCEL_LIST HC
                            ON B.BOOK_CODE = HC.BOOK_CODE
                                LEFT JOIN MEMBER_CANCEL_LIST MC
                                ON B.BOOK_CODE = MC.BOOK_CODE
                                    JOIN MEMBER_PROFILE MP
                                    ON B.MEMBER_CODE = MP.MEMBER_CODE;
--?—‹ ?‚´?š©ë³´ê¸°
SELECT BOOK_CODE, MEMBER_CODE, APPLY_PACKAGE_CODE, LOC_CODE
, APPLY_DATE, PACKAGE_CODE, PACKAGE_NAME
, PACKAGE_START, PACKAGE_END
, BOOK_HOUR, HOST_CANCEL, MEMBER_CANCEL, REFUND, LOC_NAME
FROM VIEW_BOOKLIST
WHERE MEMBER_CODE = 'M000001'
ORDER BY APPLY_DATE;


--?—‹ ?˜ˆ?•½?ƒ?„¸
SELECT BOOK_CODE, MEMBER_CODE
, APPLY_DATE, PACKAGE_NAME
, PACKAGE_START, PACKAGE_END
, BOOK_HOUR, HOST_CANCEL, MEMBER_CANCEL, REFUND, LOC_NAME
, ACTUAL_BOOKER, ACTUAL_BOOKER_TEL
, BOOK_PEOPLE, BOOK_DATE, BOOK_REQ, PACKAGE_PRICE
, BIZ_NAME, BIZ_CEO, BIZ_LICENSE_NUMBER
, MEMBER_CANCEL_REASON, HOST_CANCEL_REASON
, MEMBER_EMAIL, LOC_ADDR, LOC_DETAIL_ADDR
, MEMBER_NICKNAME
FROM VIEW_BOOKLIST
WHERE BOOK_CODE = 'BC000001';



--?—‹ ?™˜ë¶ˆê³„?‚°
/*
?´?š©?‹œ?ž‘?¼?ž 4?¼ ? „?´ë¯?ë¡?
?˜ˆ?•½ ê°?ê²©ì˜ 50%?¸ 100,000?›?´ ë§ˆì¼ë¦¬ì?ë¡? ?™˜ë¶ˆë©?‹ˆ?‹¤.
*/
--?—‹ ì·¨ì†Œ?Œ?—… ?™˜ë¶? ê³„ì‚°
SELECT BOOK_CODE, BOOK_HOUR, LOC_NAME
, APPLY_DATE, PACKAGE_START, PACKAGE_END
, PACKAGE_PRICE
, TO_DATE(APPLY_DATE, 'YYYY-MM-DD')- TRUNC(TO_DATE(SYSDATE, 'YYYY-MM-DD')) AS DAYS --0 ?´ë©? ?‹¹?¼// ì·¨ì†Œë²„íŠ¼ ë¹„í™œ
FROM VIEW_BOOKLIST;
WHERE BOOK_CODE = 'BC000001';

--?—‹ ì·¨ì†Œë²„íŠ¼ ?´ë¦??‹œ ì·¨ì†Œ?‚´?—­ ì¶”ê?
INSERT INTO MEMBER_CANCEL_LIST (MEMBER_CANCEL_CODE, BOOK_CODE, MEMBER_CANCEL_REASON, MEMBER_CANCEL_DATE)
VALUES(F_CODE('MC', MC_SEQ.NEXTVAL), 'BC000003', '?ž˜?“¤?–´?„œ ?•ˆê°ˆëž?‹ˆ?‹¤', SYSDATE);

--?—‹ ?˜ˆ?•½ ?™˜ë¶? ?‚´?—­ ì¶”ê? 
INSERT INTO BOOK_REFUND_LIST (BOOK_REFUND_CODE, BOOK_CODE, BOOK_REFUND_DATE)
VALUES(F_CODE('BRF', BRF_SEQ.NEXTVAL), 'BC000003', SYSDATE);

--?—‹ ?‹‰?„¤?ž„ ê²??ƒ‰
SELECT MEMBER_NICKNAME
FROM MEMBER_PROFILE
WHERE MEMBER_CODE='M000002';


--------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
--?—‹ userReviewList

SELECT *
FROM REVIEW;

--?—‹ ?´?š©?ž : ë¦¬ë·° ?ž‘?„±
INSERT INTO REVIEW(REVIEW_CODE, LOC_CODE, MEMBER_CODE, REVIEW_RATE, REVIEW_CONTENT, REVIEW_DATE)
VALUES(F_CODE('RV', RV_SEQ.NEXTVAL), 'L000003', 'M000005', 3, '?°?´?„°ë² ì´?Š¤ë¡? ë¦¬ë·°ë¥? ?¨ë´…ë‹ˆ?‹¤... ?š°?•˜?•˜', SYSDATE);


--?—‹ ?´?š©?ž : ë¦¬ë·° ?ˆ˜? •?¼ ?‚´?š© ê°?? ¸?˜¤ê¸?
SELECT REVIEW_CODE, LOC_CODE, REVIEW_CONTENT, REVIEW_RATE
FROM REVIEW
WHERE REVIEW_CODE='RV000001';

--?—‹ ?´?š©?ž : ë¦¬ë·° ?ˆ˜? •
UPDATE REVIEW
SET REVIEW_RATE=4, REVIEW_CONTENT='?´? ‡ê²?', REVIEW_DATE=SYSDATE
WHERE REVIEW_CODE = 'RV000001';

--?—‹ ?´?š©?ž : ë¦¬ë·° ?‚­? œ
INSERT INTO REVIEW_REMOVE(REVIEW_REMOVE_CODE, REVIEW_CODE, REVIEW_REMOVE_DATE)
VALUES(F_CODE('RVRM', RV_SEQ.NEXTVAL), 'RV000010', SYSDATE);


--?—‹ ?˜¸?Š¤?Š¸ : ë¦¬ë·° ?‹µê¸? ?ž‘?„±
INSERT INTO REVIEW_REPLY (REVIEW_REPLY_CODE, REVIEW_CODE, REVIEW_REPLY_CONTENT, REVIEW_REPLY_DATE)
VALUES(F_CODE('RVRE', RVRE_SEQ.NEXTVAL), 'RV000006', 'ì»¨í…ì¸?', SYSDATE);

--?—‹ ?˜¸?Š¤?Š¸ : ë¦¬ë·° ?ˆ˜? •?¼ ë¶ˆëŸ¬?˜¤ê¸?
SELECT REVIEW_REPLY_CODE, REVIEW_REPLY_CONTENT
FROM REVIEW_REPLY
WHERE REVIEW_REPLY_CODE='RVRE000001';

--?—‹ ?˜¸?Š¤?Š¸ : ë¦¬ë·° ?‹µê¸? ?ˆ˜? •
UPDATE REVIEW_REPLY
SET REVIEW_REPLY_CONTENT='?´? ‡ê²?', REVIEW_REPLY_DATE=SYSDATE
WHERE REVIEW_REPLY_CODE='RVRE000001';


--?—‹ ?˜¸?Š¤?Š¸ : ë¦¬ë·°?‹µê¸? ?‚­? œ?‹œ
INSERT INTO REVIEW_REPLY_REMOVE (REVIEW_REPLY_REMOVE_CODE, REVIEW_REPLY_CODE, REVIEW_REPLY_REMOVE_DATE)
VALUES(F_CODE('RVRERM', RVRERM_SEQ.NEXTVAL), 'RVRE000004', SYSDATE);


--?—‹ ?˜¸?Š¤?Š¸ : QNA ?‹µê¸? ?ž‘?„±
INSERT INTO QNA_REPLY (QNA_REPLY_CODE, QNA_CODE, QNA_REPLY_CONTENT, QNA_REPLY_DATE)
VALUES(F_CODE('QRE', QRE_SEQ.NEXTVAL), 'Q000001', '?‹µê¸? ?‹µ?‹ˆ?‹¤.', SYSDATE);


--?—‹ ?˜¸?Š¤?Š¸ : QNA ?ˆ˜? •?¼ ë¶ˆëŸ¬?˜¤ê¸?
SELECT QNA_REPLY_CODE, QNA_REPLY_CONTENT
FROM QNA_REPLY
WHERE QNA_REPLY_CODE ='QRE000001';

--?—‹ ?˜¸?Š¤?Š¸ : QNA ?‹µê¸? ?ˆ˜? •
UPDATE QNA_REPLY
SET QNA_REPLY_CONTENT='?•ˆ?…•', QNA_REPLY_DATE=SYSDATE
WHERE QNA_REPLY_CODE='QRE000001';


--?—‹ ?˜¸?Š¤?Š¸ : QNA ?‹µê¸? ?‚­? œ
INSERT INTO QNA_REPLY_REMOVE(QNA_REPLY_REMOVE_CODE, QNA_REPLY_CODE, QNA_REPLY_REMOVE_DATE)
VALUES(F_CODE('QRERM', QRERM_SEQ.NEXTVAL), 'QRE000001', SYSDATE); 


--?—‹ ë¦¬ë·° ?‰ê·? ë³„ì  êµ¬í•˜ê¸?
SELECT ROUND(AVG(NVL(REVIEW_RATE, 0)), 2) AS AVGSTAR
FROM REVIEW
WHERE LOC_CODE='L000007';

SELECT *
FROM REVIEW;

--------------------------------------------------------------------------------
/*
*userQnaList 6(X)
?—
1. ?´?š©?žê°? ?ž‘?„±?•œ QnAë¥? ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬?
    (Q&Aì½”ë“œ, ?•´?‹¹ê³µê°„ëª?, ?‚´?š©, ?ž‘?„±?¼)
   1-1. ?‚­? œ?œ QnA?? ì¡°ì¸?•˜?—¬ ?‚­? œ?—¬ë¶?ë¥? ?•Œ?ˆ˜ ?žˆê²?
2. ?‚­? œë²„íŠ¼ ?´ë¦??‹œ ?‚­? œ?‚´?—­?— ?•´?‹¹ QnAì½”ë“œë¥? ì°¸ì¡°?•˜?Š” ?°?´?„°ë¥? INSERT
?™¥
1. ?‚­? œ?œ Q&A ê²½ìš°?—?Š” ë³´ì—¬ì£¼ì? ?•Š?Š”?‹¤.
2. ?‚­? œ?‹œ?—?„ ?•Œë¦?
*/

--?—‹ ?´?š©?žê°? ?ž‘?„±?•œ QnA
SELECT Q.QNA_CODE, Q.LOC_CODE, Q.MEMBER_CODE
, Q.QNA_CONTENT, Q.QNA_DATE, LBIF.LOC_NAME
, (SELECT COUNT(*) FROM QNA_REMOVE QRM WHERE Q.QNA_CODE = QRM.QNA_CODE) AS REMOVECOUNT
FROM QNA Q
JOIN LOC L
ON Q.LOC_CODE = L.LOC_CODE
    JOIN LOC_BASIC_INFO LBIF
    ON L.LOC_CODE = LBIF.LOC_CODE;
    
-- ë·°ì—?„œ
SELECT QNA_CODE, LOC_CODE, MEMBER_CODE
, QNA_CONTENT, QNA_DATE, LOC_NAME
, REMOVECOUNT
FROM VIEW_USER_QNA
WHERE MEMBER_CODE='M000002'
ORDER BY QNA_CODE DESC;

--?—‹ ?‚­? œë²„íŠ¼ ?´ë¦??‹œ QNA REMOVE
INSERT INTO QNA_REMOVE (QNA_REMOVE_CODE, QNA_CODE, QNA_REMOVE_DATE)
VALUES(F_CODE('QRM', QRM_SEQ.NEXTVAL), 'Q000001', SYSDATE);

--?—‹ ?œ ?? ?‹‰?„¤?ž„ ê²??ƒ‰
SELECT MEMBER_NICKNAME
FROM MEMBER_PROFILE
WHERE MEMBER_CODE = 'M000002';


--?—‹ ?´?š©?žê°? ?ž‘?„±?•œ ë¦¬ë·°
SELECT R.REVIEW_CODE, R.MEMBER_CODE
, R.REVIEW_CONTENT, R.REVIEW_RATE, R.REVIEW_DATE, LBIF.LOC_NAME
, (SELECT COUNT(*) FROM REVIEW_REMOVE RVRM WHERE R.REVIEW_CODE = RVRM.REVIEW_CODE) AS REMOVECOUNT
FROM REVIEW R
JOIN LOC L
ON R.LOC_CODE = L.LOC_CODE
    JOIN LOC_BASIC_INFO LBIF
    ON L.LOC_CODE = LBIF.LOC_CODE;
-- ë·? ?ž‘?„±
SELECT REVIEW_CODE, MEMBER_CODE
, REVIEW_CONTENT, REVIEW_RATE, REVIEW_DATE, LOC_NAME
, REMOVECOUNT
FROM VIEW_USER_REVIEW
WHERE MEMBER_CODE = 'M000001';

----------------------------------------------------------------------------------------------

/*

* hostAccountManager(?˜¸?Š¤?Š¸?šŒ?›ê´?ë¦?) 7
?—
1. ?˜¸?Š¤?Š¸ ?…Œ?´ë¸”ë¡œ ë¶??„° ?°?´?„°ë¥? ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬?
   (?šŒ?›ì½”ë“œ, ?•„?´?””, ?‹‰?„¤?ž„, ë¸”ëž™?—¬ë¶?, [ë¸”ëž™ì²˜ë¦¬?‚¬?œ ])
   1-1. ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?…Œ?´ë¸”ì„ ?†µ?•´ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?—¬ë¶? ?™•?¸ ?•„?š”
2. ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?„¤? •?‹œ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?…Œ?´ë¸”ì— INSERT?•˜?Š” ì¿¼ë¦¬ë¬?
3. ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?•´? œ?‹œ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?…Œ?´ë¸”ì—?„œ DELETE?•˜?Š” ì¿¼ë¦¬ë¬?
4. ?‹ ê³ ë‚´?—­(ê³µê°„) ?…Œ?´ë¸”ë¡œ ë¶??„° ?°?´?„°ë¥? ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬?
   (?‹ ê³ ì¼?ž, ?‹ ê³ ì‚¬?œ , ?‹ ê³ ì²˜ë¦¬ìƒ?ƒœ, ?‹ ê³ ìœ ?˜•) 

?™¥
1. ?‹ ê³ ë‚´?—­ ë²„íŠ¼?ˆ„ë¥´ë©´ ëª¨ë“  ?‹ ê³ ë‚´?—­?´ ?Œ?—…ì°½ìœ¼ë¡? ?‚˜???•¼?•¨.
2. ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?„¤? •?‹œ ?Œ?—…ì°½ìœ¼ë¡? ?‚¬?œ ë¥? ? ?„ ?ˆ˜ ?žˆê²?, ?•´? œ?‹œ?—?Š” ?•Œë¦¼ìœ¼ë¡? ?‹¤?‹œ?•œë²? ?™•?¸
*/

--?—‹ ?˜¸?Š¤?Š¸ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?™•?¸?•˜?Š” ì¿¼ë¦¬
SELECT H.HOST_EMAIL, H.HOST_NICKNAME
, HB.HOST_BLACKLIST_REASON
, (SELECT COUNT(*) FROM HOST_BLACKLIST HB 
    WHERE H.HOST_EMAIL=HB.HOST_EMAIL) AS YESBLACK
FROM HOST_PROFILE H
    LEFT JOIN HOST_BLACKLIST HB
    ON H.HOST_EMAIL = HB.HOST_EMAIL;
-- ë·?
SELECT HOST_CODE, HOST_EMAIL, HOST_NICKNAME
, HOST_BLACKLIST_REASON, YESBLACK
FROM VIEW_HOSTBLACKLIST;


--?—‹ ?˜¸?Š¤?Š¸ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?„¤? •?‹œ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?…Œ?´ë¸? INSERT
SELECT HOST_EMAIL
FROM HOST_PROFILE
WHERE HOST_CODE = 'H000001';

INSERT INTO HOST_BLACKLIST(HOST_EMAIL, HOST_BLACKLIST_REASON, HOST_BLACKLIST_DATE)
VALUES('good1@test.com', '?‚¬?œ ?¼?„¸', SYSDATE);

-- ?—‹ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?•´? œ?‹œ DELETE
DELETE 
FROM HOST_BLACKLIST
WHERE HOST_EMAIL = 'good1@test.com';


--?—‹ ?˜¸?Š¤?Š¸ ?‹ ê³ ë‚´?—­ ?Œ?—…
-- ?‹ ê³ íšŸ?ˆ˜, ?šŒ?›ì½”ë“œ, ?‹ ê³ ì½”?“œ, ?‹ ê³ ìœ ?˜•,?‹ ê³ ì‚¬?œ ,?‹ ê³ ì¼?ž
SELECT H.HOST_CODE, L.LOC_CODE, LR.LOC_REPORT_CODE
, LR.MEMBER_CODE, LR.LOC_REPORT_REASON, LR.LOC_REPORT_DATE
, LRPT.LOC_REPORT_TYPE, RPPT.REPORT_PROC_TYPE
FROM HOST H
LEFT JOIN LOC L
ON H.HOST_CODE = L.HOST_CODE
    JOIN LOC_REPORT LR
    ON L.LOC_CODE = LR.LOC_CODE
        JOIN LOC_REPORT_TYPE LRPT
        ON LR.LOC_REPORT_TYPE_CODE=LRPT.LOC_REPORT_TYPE_CODE
            LEFT JOIN LOC_REPORT_PROC LRPP
            ON LR.LOC_REPORT_CODE=LRPP.LOC_REPORT_CODE
                LEFT JOIN REPORT_PROC_TYPE RPPT
                ON LRPP.REPORT_PROC_TYPE_CODE=RPPT.REPORT_PROC_TYPE_CODE;

-- ë·?
SELECT HOST_CODE, LOC_CODE, LOC_REPORT_CODE
, LOC_REPORT_REASON, LOC_REPORT_DATE
, LOC_REPORT_TYPE, REPORT_PROC_TYPE
FROM VIEW_HOST_REPORTDETAILS
WHERE HOST_CODE ='H000007';
/*

* userAccountManager(?´?š©?ž?šŒ?›ê´?ë¦?) 7
?—
1. ?´?š©?ž ?…Œ?´ë¸”ë¡œ ë¶??„° ?°?´?„°ë¥? ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬?
   (?šŒ?›ì½”ë“œ, ?•„?´?””, ?‹‰?„¤?ž„, ë¸”ëž™?—¬ë¶?, [ë¸”ëž™ì²˜ë¦¬?‚¬?œ ])
   1-1. ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?…Œ?´ë¸”ì„ ?†µ?•´ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?—¬ë¶? ?™•?¸ ?•„?š”
2. ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?„¤? •?‹œ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?…Œ?´ë¸”ì— INSERT?•˜?Š” ì¿¼ë¦¬ë¬?
3. ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?•´? œ?‹œ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?…Œ?´ë¸”ì—?„œ DELETE?•˜?Š” ì¿¼ë¦¬ë¬?
4. ?‹ ê³ ë‚´?—­(?˜ˆ?•½) ?…Œ?´ë¸”ë¡œ ë¶??„° ?°?´?„°ë¥? ì¡°íšŒ?•˜?Š” ì¿¼ë¦¬ë¬?
   (?‹ ê³ ì¼?ž, ?‹ ê³ ì‚¬?œ , ?‹ ê³ ì²˜ë¦¬ìƒ?ƒœ, ?‹ ê³ ìœ ?˜•) 

?™¥
1. ?‹ ê³ ë‚´?—­ ë²„íŠ¼?ˆ„ë¥´ë©´ ëª¨ë“  ?‹ ê³ ë‚´?—­?´ ?Œ?—…ì°½ìœ¼ë¡? ?‚˜???•¼?•¨.
2. ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?„¤? •?‹œ ?Œ?—…ì°½ìœ¼ë¡? ?‚¬?œ ë¥? ? ?„ ?ˆ˜ ?žˆê²?, ?•´? œ?‹œ?—?Š” ?•Œë¦¼ìœ¼ë¡? ?‹¤?‹œ?•œë²? ?™•?¸

* blacklistPopup.jsp 7

* reportDetailPopupHost.jsp 7
* reportDetailPopupUser.jsp 7

*/

--?—‹ ?´?š©?ž ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?—¬ë¶? ?™•?¸?•˜?Š” ì¿¼ë¦¬
SELECT M.MEMBER_CODE, M.MEMBER_EMAIL, M.MEMBER_NICKNAME
, MB.MEMBER_BLACKLIST_REASON
, (SELECT COUNT(*) FROM MEMBER_BLACKLIST MB 
    WHERE M.MEMBER_EMAIL=MB.MEMBER_EMAIL) AS YESBLACK
FROM MEMBER_PROFILE M
    LEFT JOIN MEMBER_BLACKLIST MB
    ON M.MEMBER_EMAIL = MB.MEMBER_EMAIL;
-- ë·?
SELECT MEMBER_CODE, MEMBER_EMAIL, MEMBER_NICKNAME
, MEMBER_BLACKLIST_REASON, YESBLACK
FROM VIEW_MEMBERBLACKLIST;




--?—‹ ë©¤ë²„ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?„¤? •?‹œ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?…Œ?´ë¸? INSERT
SELECT MEMBER_EMAIL
FROM MEMBER_PROFILE
WHERE MEMBER_CODE = 'M000001';

INSERT INTO MEMBER_BLACKLIST(MEMBER_EMAIL, MEMBER_BLACKLIST_REASON, MEMBER_BLACKLIST_DATE)
VALUES('test2@test.com', '?‚¬?œ ?¼?„¸', SYSDATE);

-- ?—‹ ë¸”ëž™ë¦¬ìŠ¤?Š¸ ?•´? œ?‹œ DELETE
DELETE 
FROM MEMBER_BLACKLIST
WHERE MEMBER_EMAIL = 'test2@test.com';


--?—‹ ?´?š©?ž ?‹ ê³ ë‚´?—­ ?Œ?—…
-- ?šŒ?›ì½”ë“œ, ?‹ ê³ ì½”?“œ, ?‹ ê³ ìœ ?˜•,?‹ ê³ ì‚¬?œ ,?‹ ê³ ì¼?ž
SELECT B.BOOK_REPORT_CODE, B.BOOK_CODE, BR.BOOK_REPORT_TYPE
, B.BOOK_REPORT_REASON, B.BOOK_REPORT_DATE, BL.MEMBER_CODE
FROM BOOK_REPORT B
JOIN BOOK_REPORT_TYPE BR
ON B.BOOK_REPORT_TYPE_CODE = BR.BOOK_REPORT_TYPE_CODE
    LEFT JOIN BOOK_REPORT_PROC BRP
    ON B.BOOK_REPORT_CODE = BRP.BOOK_REPORT_CODE
        JOIN BOOK_LIST BL
        ON B.BOOK_CODE = BL.BOOK_CODE;

-- ë·?
SELECT BOOK_REPORT_CODE, BOOK_CODE, BOOK_REPORT_TYPE
, BOOK_REPORT_REASON, BOOK_REPORT_DATE, MEMBER_CODE
FROM VIEW_MEMBER_REPORTDETAILS
WHERE MEMBER_CODE = 'M000001';


----------------------------------------------------------------------------------------------
SELECT *
FROM HOST_MSG_INFO;

-- ?˜¸?Š¤?Š¸ ë©”ì‹ ?? ì¡°íšŒ
SELECT DISTINCT H.HOST_MSG_INFO_CODE, H.MSG_CODE
, H.HOST_MSG_CONTENT, H.HOST_MSG_DATE
, M.BOOK_CODE
, AP.APPLY_DATE
, B.MEMBER_CODE -- ?ˆ˜?‹ ?ž
, M.MEMBER_NICKNAME
, HP.HOST_CODE
, HP.HOST_NICKNAME -- ?†¡?‹ ?ž
, (SELECT COUNT(*) FROM HOST_MSG_IMG HI
    WHERE H.HOST_MSG_INFO_CODE = HI.HOST_MSG_INFO_CODE) AS H_IMGCOUNT
, HI.HOST_MSG_IMG_URL
FROM MSG M
    JOIN HOST_MSG_INFO H
    ON M.MSG_CODE = H.MSG_CODE
        JOIN BOOK_LIST B
        ON M.BOOK_CODE = B.BOOK_CODE
            JOIN APPLY_PACKAGE AP
            ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
                JOIN PACKAGE P
                ON AP.PACKAGE_CODE = P.PACKAGE_CODE
                    JOIN PACKAGE_FORM PF
                    ON P.PACKAGE_FORM_CODE = PF.PACKAGE_FORM_CODE
                        JOIN LOC L
                        ON PF.LOC_CODE = L.LOC_CODE
                            JOIN HOST_PROFILE HP
                            ON L.HOST_CODE = HP.HOST_CODE
                                JOIN MEMBER_PROFILE M  -- ë©¤ë²„?ƒˆ?‡´?‹œ ?•ˆë³´ìž„
                                ON B.MEMBER_CODE = M.MEMBER_CODE
                                    LEFT JOIN HOST_MSG_IMG HI
                                    ON H.HOST_MSG_INFO_CODE = HI.HOST_MSG_INFO_CODE;



-- ë·? ?ž‘?„±
SELECT HOST_MSG_INFO_CODE, MSG_CODE
, HOST_MSG_CONTENT, HOST_MSG_DATE
, HOST_CODE, HOST_NICKNAME
, BOOK_CODE, APPLY_DATE
, MEMBER_CODE, MEMBER_NICKNAME
, H_IMGCOUNT, HOST_MSG_IMG_URL
FROM VIEW_HOST_MESSENGER;


-- ë©¤ë²„ ?ž…?ž¥?—?„œ ë©”ì‹œì§? ì¡°íšŒ 
SELECT MM.MEMBER_MSG_INFO_CODE, MM.MSG_CODE
, MM.MEMBER_MSG_CONTENT, MM.MEMBER_MSG_DATE
, M.BOOK_CODE
, AP.APPLY_DATE
, B.MEMBER_CODE -- ?†¡?‹ ?ž
, M.MEMBER_NICKNAME
, HP.HOST_CODE
, HP.HOST_NICKNAME -- ?†¡?‹ ?ž
, (SELECT COUNT(*) FROM MEMBER_MSG_IMG MI
    WHERE MM.MEMBER_MSG_INFO_CODE = MI.MEMBER_MSG_INFO_CODE) AS M_IMGCOUNT
, MI.MEMBER_MSG_IMG_URL
FROM MEMBER_MSG_INFO MM
    JOIN MSG M
    ON MM.MSG_CODE = M.MSG_CODE
        JOIN BOOK_LIST B
        ON M.BOOK_CODE = B.BOOK_CODE
            JOIN APPLY_PACKAGE AP
            ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
                JOIN PACKAGE P
                ON AP.PACKAGE_CODE = P.PACKAGE_CODE
                    JOIN PACKAGE_FORM PF
                    ON P.PACKAGE_FORM_CODE = PF.PACKAGE_FORM_CODE
                        JOIN LOC L
                        ON PF.LOC_CODE = L.LOC_CODE
                            JOIN HOST_PROFILE HP
                            ON L.HOST_CODE = HP.HOST_CODE
                                JOIN MEMBER_PROFILE M  -- ë©¤ë²„?ƒˆ?‡´?‹œ ?•ˆë³´ìž„
                                ON B.MEMBER_CODE = M.MEMBER_CODE
                                    LEFT JOIN MEMBER_MSG_IMG MI
                                    ON MM.MEMBER_MSG_INFO_CODE = MI.MEMBER_MSG_INFO_CODE;

--?—‹ ë©”ì‹œì§? ? „ì²? ?‹¤ ë³´ëŠ” ë·?
SELECT MSG_CODE, MSG_CONTENT, MSG_DATE
, SENDER_CODE, SENDER
, IMGCOUNT, MSG_IMG_URL
, BOOK_CODE, APPLY_DATE, HORM
FROM VIEW_MESSENGER;

--?—‹ ?˜¸?Š¤?Š¸ ?‹‰?„¤?ž„ ì°¾ê¸°
--?˜ˆ?•½ì½”ë“œë¡? ?„œë¡? ?‹‰ ì°¾ì•„ë³´ê¸° 
SELECT HOST_NICKNAME
FROM VIEW_BOOK_NICKNAME
WHERE BOOK_CODE='BC000001';

--?—‹ ë©”ì‹ ??ì½”ë“œ ê²??ƒ‰
SELECT MSG_CODE FROM ( SELECT ROWNUM, MSG_CODE
FROM VIEW_MESSENGER
WHERE BOOK_CODE='BC000001')
WHERE ROWNUM <= 1;

--?—‹ ?´?š©?žê°? ë©”ì‹œì§? ? „?†¡?•˜?Š” ê²½ìš°
INSERT INTO MEMBER_MSG_INFO(MEMBER_MSG_INFO_CODE, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE)
VALUES(F_CODE('MMIF', MMIF_SEQ.NEXTVAL), 'MSG000001', '?–´ì§¸ì„œ!!', SYSDATE);

--?—‹ ?´?š©?žê°? ?´ë¯¸ì? ? „?†¡?•˜?Š” ê²½ìš°
-- ?”„ë¡œì‹œ?? 
CALL PRC_M_MSG_IMG('BC000001', '?•ˆ?ƒ¥');

--------------------------------------------------------------------------------
--?—‹ ?˜¸?Š¤?Š¸ 
--?—‹ ?ƒ??ë°? ?‹‰?„¤?ž„ ì°¾ê¸°
SELECT MEMBER_NICKNAME
FROM VIEW_BOOK_NICKNAME
WHERE BOOK_CODE='BC000001';

--?—‹ ë©”ì‹ ??ì½”ë“œ ê²??ƒ‰
SELECT MSG_CODE FROM ( SELECT ROWNUM, MSG_CODE
FROM VIEW_MESSENGER
WHERE BOOK_CODE='BC000001')
WHERE ROWNUM <= 1;

--?—‹ ?˜¸?Š¤?Š¸ê°? ë©”ì‹œì§? ? „?†¡?•˜?Š” ê²½ìš°
INSERT INTO HOST_MSG_INFO(HOST_MSG_INFO_CODE, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE)
VALUES(F_CODE('HMIF', HMIF_SEQ.NEXTVAL), 'MSG000001', '?–´ì§¸ì„œ!!', SYSDATE);


select *
from view_messenger
where book_code='BC000001';

--?—‹ ?˜¸?Š¤?Š¸ê°? ?´ë¯¸ì? ? „?†¡?•˜?Š” ê²½ìš°
-- ?”„ë¡œì‹œ?? 
CALL PRC_H_MSG_IMG('BC000001', '?´ê±? ?´ë¯¸ì? ì£¼ì†Œ?š”!');

SELECT * FROM MSG;

SELECT * FROM REVIEW_IMG;


INSERT INTO REVIEW_IMG(REVIEW_IMG_CODE, REVIEW_CODE, REVIEW_IMG_URL)
VALUES(F_CODE('RVIMG', RVIMG_SEQ.NEXTVAL), 'RV000085', '¹¹½Ã±â');

ROLLBACK;
SELECT REVIEW_CODE
    FROM
    (SELECT A.REVIEW_CODE, A.MEMBER_CODE
    FROM REVIEW A
    ORDER BY A.REVIEW_DATE DESC)
    WHERE ROWNUM = 1 AND MEMBER_CODE='M000001';


EXEC PRC_REVIEW_IMG('L000001', 'M000002', 4, '¾È³çÇÏ¼¼¿ë', 'too.png');