/*
deleteAccount(호스트, 이용자 동일) 1

이용자
0. 프로필정보에서 회원코드 확인
1. 예약내역 남아있으면 탈퇴 불가
2. / 마일리지 남아있으면 탈퇴 불가능
3. 환전계좌 테이블에서 해당 계좌번호로 이루어진 것들 삭제
4. 충전신청계좌에서 해당계좌번호로 이루어진것들 
   찾아서 삭제
5. 계좌번호 테이블에서 계좌 삭제
6. 프로필정보에서 회원코드 찾아 삭제
7. 탈퇴회원 테이블 insert
*/

--※ 이용자 삭제 순서 
-- ○ 프로필정보에서 회원코드 확인
SELECT MEMBER_CODE
FROM MEMBER_PROFILE
WHERE MEMBER_NICKNAME='김감자';
-->
SELECT MEMBER_CODE FROM MEMBER_PROFILE WHERE MEMBER_NICKNAME='김감자'
;
SELECT * FROM MEMBER_BANK_INFO;

--○ 멤버프로필 테이블에 있는지 확인 → 없으면 등록하지 않은 멤버
SELECT COUNT(*) AS COUNT
FROM MEMBER_PROFILE
WHERE MEMBER_CODE = 'M000009';
-->
SELECT COUNT(*) AS COUNT FROM MEMBER_PROFILE WHERE MEMBER_CODE = 'M000009'
;

--○ 예약내역 있는지 확인 
SELECT B.BOOK_CODE, B.MEMBER_CODE, AP.APPLY_PACKAGE_CODE, AP.APPLY_DATE
, P.PACKAGE_CODE, PF.LOC_CODE
FROM BOOK_LIST B
JOIN APPLY_PACKAGE AP
ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
JOIN PACKAGE P
ON AP.PACKAGE_CODE = P.PACKAGE_CODE
JOIN PACKAGE_FORM PF
ON P.PACKAGE_FORM_CODE = PF.PACKAGE_FORM_CODE
WHERE AP.APPLY_DATE > SYSDATE AND B.MEMBER_CODE='M000002';
-->
SELECT COUNT(*) AS COUNT FROM BOOK_LIST B JOIN APPLY_PACKAGE AP ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE JOIN PACKAGE P ON AP.PACKAGE_CODE = P.PACKAGE_CODE JOIN PACKAGE_FORM PF ON P.PACKAGE_FORM_CODE = PF.PACKAGE_FORM_CODE WHERE AP.APPLY_DATE > SYSDATE AND B.MEMBER_CODE='M000002'
;


--------------------------------------------------------------------- 마일리지
--○ 마일리지 내역 확인 방법 
-- 충전처리내역(처리된것만) 조인 / 충전처리코드 LOAD_TYPE_CODE='LT000001'
-- - 예약결제내역 차감
-- + 이용자가 취소한 예약 환불 내역
-- + 호스트가 취소한 예약 환불 내역
-- - 이용자 환전 금액
-------------------------------------------


-- 마일리지 충전 내역
SELECT NVL(SUM(LR.LOAD_AMOUNT), 0)
FROM LOAD_PROC LP
JOIN LOAD_REG LR
ON LP.LOAD_REG_CODE = LR.LOAD_REG_CODE
WHERE LP.LOAD_TYPE_CODE='LT000001' AND LR.MEMBER_CODE='M000003';

-- 예약 결제 내역
SELECT NVL(SUM(P.PACKAGE_PRICE), 0)
FROM BOOK_PAY_LIST BP
JOIN BOOK_LIST B
ON BP.BOOK_CODE = B.BOOK_CODE
JOIN APPLY_PACKAGE AP
ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
JOIN PACKAGE P 
ON AP.PACKAGE_CODE = P.PACKAGE_CODE
WHERE B.MEMBER_CODE='M000002';

          
-- 호스트가 취소한 예약의 경우        
SELECT NVL(SUM(P.PACKAGE_PRICE), 0) AS HOST_CANCEL
FROM HOST_CANCEL_LIST HC
JOIN BOOK_REFUND_LIST BR
ON HC.BOOK_CODE = BR.BOOK_CODE
    JOIN BOOK_LIST B
    ON BR.BOOK_CODE = B.BOOK_CODE
        JOIN APPLY_PACKAGE AP
        ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
            JOIN PACKAGE P
            ON AP.PACKAGE_CODE = P.PACKAGE_CODE
            WHERE B.MEMBER_CODE = 'M000002';

-- 이용자가 취소한 예약의 경우
-- 이용자 취소시 7일전 - 100% 환불, 6~1일전 - 50% 환불
SELECT NVL(SUM
(CASE WHEN (TO_DATE(AP.APPLY_DATE, 'YYYY-MM-DD') - TO_DATE(MC.MEMBER_CANCEL_DATE, 'YYYY-MM-DD')) < 7 
      THEN TRUNC(P.PACKAGE_PRICE * 0.5, -1) -- 이용자 취소일자가 패키지 적용일 6일 전일 경우 50프로
      ELSE TRUNC(P.PACKAGE_PRICE * 1, -1)   -- 아닐경우 100프로 환불, 나머지 예외상황은 웹에서 처리
      END), 0) AS MEMBER_CANCEL
FROM MEMBER_CANCEL_LIST MC
JOIN BOOK_REFUND_LIST BR
ON MC.BOOK_CODE = BR.BOOK_CODE
    JOIN BOOK_LIST B
    ON BR.BOOK_CODE = B.BOOK_CODE
        JOIN APPLY_PACKAGE AP
        ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
            JOIN PACKAGE P
            ON AP.PACKAGE_CODE = P.PACKAGE_CODE;
            --WHERE B.MEMBER_CODE = 'M000002';

-- 이용자가 환전한 금액
SELECT NVL(SUM(MEMBER_EXCHANGE_AMOUNT), 0)
FROM MEMBER_EXCHANGE_LIST
WHERE MEMBER_CODE = 'M000002';

--○ 마일리지 프로시저
VARIABLE V_CHANGE NUMBER;

CALL PRC_MEMBER_MILEAGE('M000005', :V_CHANGE);

----------------------------------------------------------------------- 마일리지


-- 계좌정보 있는지 확인 (MEMBER_BANK_INFO)
SELECT MEMBER_BANK_NUMBER
FROM MEMBER_BANK_INFO
WHERE MEMBER_CODE='M000003';
--> 
SELECT MEMBER_BANK_NUMBER, MEMBER_CODE FROM MEMBER_BANK_INFO WHERE MEMBER_CODE='M000001'
;

--○ MEMBER_EXCHANGE_BANK_INFO에서 계좌정보 삭제 
DELETE MEMBER_EXCHANGE_BANK_INFO
WHERE MEMBER_BANK_NUMBER 
IN ( SELECT MEMBER_BANK_NUMBER
     FROM MEMBER_BANK_INFO
     WHERE MEMBER_CODE='M000003');
--> 
DELETE MEMBER_EXCHANGE_BANK_INFO WHERE MEMBER_BANK_NUMBER IN ( SELECT MEMBER_BANK_NUMBER FROM MEMBER_BANK_INFO WHERE MEMBER_CODE='M000003')
;

--○ 충전신청계좌에서 해당계좌번호로 이루어진것들 찾아서 삭제
DELETE LOAD_REG_BANK_INFO
WHERE MEMBER_BANK_NUMBER
IN ( SELECT MEMBER_BANK_NUMBER
     FROM MEMBER_BANK_INFO
     WHERE MEMBER_CODE='M000003');
-->
DELETE LOAD_REG_BANK_INFO WHERE MEMBER_BANK_NUMBER IN ( SELECT MEMBER_BANK_NUMBER FROM MEMBER_BANK_INFO WHERE MEMBER_CODE='M000003')
;

--○ 멤버계좌정보에서 해당계좌번호 찾아 삭제
DELETE FROM MEMBER_BANK_INFO WHERE MEMBER_CODE='M000003';

--○ 멤버프로필에서 해당멤버 삭제
DELETE FROM MEMBER_PROFILE WHERE MEMBER_CODE='M000003';

--○ 탈퇴 테이블 INSERT 
INSERT INTO MEMBER_WITHDRAW(MEMBER_WITHDRAW_CODE, MEMBER_CODE, MEMBER_WITHDRAW_DATE) 
VALUES(F_CODE('MW', MW_SEQ.NEXTVAL), 'M000003' ,SYSDATE);
;
--> 한줄
INSERT INTO MEMBER_WITHDRAW(MEMBER_WITHDRAW_CODE, MEMBER_CODE, MEMBER_WITHDRAW_DATE) VALUES(F_CODE('MW', MW_SEQ.NEXTVAL), 'M000003',SYSDATE)
;
