/*
* bookList 5
●
1. 예약 테이블 정보를 조회하는 쿼리문
   (예약코드, 예약자명, 공간명, 일자, 인원수, 가격, 요청사항, 상태)
2. 예약취소 클릭시 예약취소 테이블에 데이터 INSERT 쿼리문 
♥
1. 검색은 할필요 없음
2. 최신 순으로 정렬 필요.
3. 공간명을 나오게 하고 상세보기 팝업으로(예약인원수, 요청사항, 가격)
   나머지(예약코드, 예약자명, 예약현황, 예약취소)는 리스트로 보여줌
4. 취소 클릭시 취소사유를 입력하기 위한 팝업창이 필요


*/

-- 예약내용(패키지 날짜, 시간 총 몇시간) 공간명 예약현황, 
SELECT DISTINCT B.BOOK_CODE, B.MEMBER_CODE, A.APPLY_PACKAGE_CODE, F.LOC_CODE
, TO_DATE(A.APPLY_DATE,'YYYY-MM-DD') AS APPLY_DATE, P.PACKAGE_CODE, P.PACKAGE_NAME
, P.PACKAGE_START, P.PACKAGE_END
, NVL(P.PACKAGE_END, 0) - NVL(P.PACKAGE_START, 0) AS BOOK_HOUR
, (SELECT COUNT(*) FROM HOST_CANCEL_LIST HC WHERE B.BOOK_CODE = HC.BOOK_CODE) AS HOST_CANCEL
, (SELECT COUNT(*) FROM MEMBER_CANCEL_LIST MC WHERE B.BOOK_CODE = MC.BOOK_CODE) AS MEMBER_CANCEL
, (SELECT COUNT(*) FROM BOOK_REFUND_LIST BRF WHERE B.BOOK_CODE = BRF.BOOK_CODE) AS REFUND
, LBIF.LOC_NAME, AB.ACTUAL_BOOKER, AB.ACTUAL_BOOKER_TEL
, B.BOOK_PEOPLE, BOOK_DATE, BOOK_REQ, P.PACKAGE_PRICE
, BZ.BIZ_NAME, BZ.BIZ_CEO, BIZ_LICENSE_NUMBER
, MC.MEMBER_CANCEL_REASON, HC.HOST_CANCEL_REASON
, MP.MEMBER_EMAIL, LBIF.LOC_ADDR, LBIF.LOC_DETAIL_ADDR
FROM BOOK_LIST B
JOIN APPLY_PACKAGE A
ON B.APPLY_PACKAGE_CODE = A.APPLY_PACKAGE_CODE
    JOIN PACKAGE P
    ON A.PACKAGE_CODE = P.PACKAGE_CODE
        JOIN PACKAGE_FORM F
        ON P.PACKAGE_FORM_CODE = F.PACKAGE_FORM_CODE
            JOIN REVIEW R
            ON B.MEMBER_CODE = R.MEMBER_CODE
                JOIN LOC_BASIC_INFO LBIF
                ON F.LOC_CODE = LBIF.LOC_CODE
                    JOIN ACTUAL_BOOKER AB
                    ON B.BOOK_CODE=AB.BOOK_CODE
                        JOIN BIZ_INFO BZ
                        ON F.LOC_CODE = BZ.LOC_CODE
                            LEFT JOIN HOST_CANCEL_LIST HC
                            ON B.BOOK_CODE = HC.BOOK_CODE
                                LEFT JOIN MEMBER_CANCEL_LIST MC
                                ON B.BOOK_CODE = MC.BOOK_CODE
                                    JOIN MEMBER_PROFILE MP
                                    ON B.MEMBER_CODE = MP.MEMBER_CODE;
--○ 내용보기
SELECT BOOK_CODE, MEMBER_CODE, APPLY_PACKAGE_CODE, LOC_CODE
, APPLY_DATE, PACKAGE_CODE, PACKAGE_NAME
, PACKAGE_START, PACKAGE_END
, BOOK_HOUR, HOST_CANCEL, MEMBER_CANCEL, REFUND, LOC_NAME
FROM VIEW_BOOKLIST
WHERE MEMBER_CODE = 'M000001'
ORDER BY APPLY_DATE;


--○ 예약상세
SELECT BOOK_CODE, MEMBER_CODE
, APPLY_DATE, PACKAGE_NAME
, PACKAGE_START, PACKAGE_END
, BOOK_HOUR, HOST_CANCEL, MEMBER_CANCEL, REFUND, LOC_NAME
, ACTUAL_BOOKER, ACTUAL_BOOKER_TEL
, BOOK_PEOPLE, BOOK_DATE, BOOK_REQ, PACKAGE_PRICE
, BIZ_NAME, BIZ_CEO, BIZ_LICENSE_NUMBER
, MEMBER_CANCEL_REASON, HOST_CANCEL_REASON
, MEMBER_EMAIL, LOC_ADDR, LOC_DETAIL_ADDR
, MEMBER_NICKNAME
FROM VIEW_BOOKLIST
WHERE BOOK_CODE = 'BC000001';
