/*
deleteAccount(호스트, 이용자 동일) 1
●
1. 탈퇴하기 누른 경우 호스트 회원의 모든 개인정보 삭제
   (사업자정보(공간), 연락처(공간), 프로필정보, 계좌정보)
2. 삭제 후 탈퇴 테이블에 INSERT
♥
사업자정보, 연락처는 지우고 공간은 삭제 테이블로 insert...
호스트

1. 예약내역 있으면 탈퇴 불가능
2. 마일리지 남아있으면 탈퇴 불가능 
3. 탈퇴내역에 해당 호스트 있는지 확인
4. LOC_CONTACT에서 연락처 삭제
5. BIZ_INFO에서 사업자정보 삭제
6. LOC_REMOVE(LRM)에 삭제된 공간으로 INSERT
7. 환전계좌에서 해당 계좌정보 DELETE
8. HOST_BANK_INFO에서 해당 회원코드의 계좌정보 DELETE
9. HOST_PROFILE에서 해당 회원코드인 회원정보 DELETE
10. HOST_WITHDRAW(HW) 에 해당 회원코드 회원 INSERT

*/

--★ 호스트 삭제 순서

-- !!! 여러 개 - 해당 공간의 예약내역 확인
SELECT B.BOOK_CODE, AP.APPLY_PACKAGE_CODE, AP.APPLY_DATE
, P.PACKAGE_CODE, PF.LOC_CODE, L.HOST_CODE
FROM BOOK_LIST B
JOIN APPLY_PACKAGE AP
ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
JOIN PACKAGE P
ON AP.PACKAGE_CODE = P.PACKAGE_CODE
JOIN PACKAGE_FORM PF
ON P.PACKAGE_FORM_CODE = PF.PACKAGE_FORM_CODE
JOIN LOC L
ON PF.LOC_CODE = L.LOC_CODE
WHERE AP.APPLY_DATE > SYSDATE AND L.HOST_CODE='H000003';
-->
SELECT COUNT(*) AS COUNT FROM BOOK_LIST B JOIN APPLY_PACKAGE AP ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE JOIN PACKAGE P ON AP.PACKAGE_CODE = P.PACKAGE_CODE JOIN PACKAGE_FORM PF ON P.PACKAGE_FORM_CODE = PF.PACKAGE_FORM_CODE JOIN LOC L ON PF.LOC_CODE = L.LOC_CODE WHERE AP.APPLY_DATE > SYSDATE AND L.HOST_CODE='H000003'
;

-- ???????????마일리지 내역 확인
-- 보류

--○ 탈퇴내역에 해당 호스트 있는지 확인
SELECT COUNT(*) AS COUNT
FROM HOST_WITHDRAW
WHERE HOST_CODE='H000002';


-- !! 여러개] LOC 테이블에서 해당 회원코드의 공간코드 찾기(RETURN 객체)
SELECT LOC_CODE
FROM LOC
WHERE HOST_CODE = 'H000006';
-->
SELECT LOC_CODE FROM LOC WHERE HOST_CODE = 'H000004'
;

--○ 받아온 공간코드들로 LOC_CONTACT에서 연락처 삭제
DELETE LOC_CONTACT WHERE LOC_CODE IN (SELECT LOC_CODE FROM LOC WHERE HOST_CODE = 'H000004')
;

--○ 받아온 공간코드들로 BIZ_INFO에서 사업자정보 삭제
DELETE BIZ_INFO WHERE LOC_CODE IN (SELECT LOC_CODE FROM LOC WHERE HOST_CODE = 'H000004')
;

--○ LOC_REMOVE(LRM)에 삭제된 공간으로 INSERT (여러번 해줘야함 )
CALL PRC_DEL_LOC_INSERT('H000006')
;
--INSERT INTO LOC_REMOVE(LOC_REMOVE_CODE, LOC_CODE, LOC_REMOVE_DATE)
--VALUES(F_CODE('LRM', LRM_SEQ.NEXTVAL), 'L000001', SYSDATE);


-- !! 여러개] 계좌정보 있는지 확인 (HOST_BANK_INFO)
SELECT HOST_BANK_NUMBER, HOST_CODE
FROM HOST_BANK_INFO
WHERE HOST_CODE='H000004';
--> 
SELECT HOST_BANK_NUMBER FROM HOST_BANK_INFO WHERE HOST_CODE='H000004'
;
-- 여기서 HOST_BANK_NUMBER 받아옴

--○ 환전계좌에서 해당 계좌정보 DELETE
DELETE 
FROM HOST_EXCHANGE_BANK_INFO
WHERE HOST_BANK_NUMBER IN (SELECT HOST_BANK_NUMBER FROM HOST_BANK_INFO WHERE HOST_CODE='H000001');
-->
DELETE FROM HOST_EXCHANGE_BANK_INFO WHERE HOST_BANK_NUMBER IN (SELECT HOST_BANK_NUMBER FROM HOST_BANK_INFO WHERE HOST_CODE='H000001')
;

--○ HOST_BANK_INFO에서 계좌번호 삭제
DELETE FROM HOST_BANK_INFO WHERE HOST_CODE='H000004';

--○ HOST_PROFILE에서 호스트번호 삭제 
DELETE FROM HOST_PROFILE WHERE HOST_CODE='H000004';

--○ 탈퇴 테이블 INSERT 
INSERT INTO HOST_WITHDRAW(HOST_WITHDRAW_CODE, HOST_CODE, HOST_WITHDRAW_DATE) 
VALUES(F_CODE('HW', HW_SEQ.NEXTVAL), 'H000002' ,SYSDATE);
--> 한줄
INSERT INTO HOST_WITHDRAW(HOST_WITHDRAW_CODE, HOST_CODE, HOST_WITHDRAW_DATE) VALUES(F_CODE('HW', HW_SEQ.NEXTVAL), 'H000002' ,SYSDATE)
;
