-- 승범 

--######################################### 1. SIGNUP
--○ 확인용
DESC HOST;
SELECT * FROM HOST_PROFILE;

DESC MEMBER;
SELECT * FROM MEMBER_PROFILE;

--○ HOST 중복검사
SELECT COUNT(*) AS COUNT
FROM HOST_PROFILE
WHERE HOST_EMAIL='good1@test.com';
--> 한줄
SELECT COUNT(*) AS COUNT FROM HOST_PROFILE WHERE HOST_EMAIL=?
;
SELECT COUNT(*) AS COUNT
FROM HOST_PROFILE
WHERE HOST_NICKNAME='퉁퉁볼';
--> 한줄
SELECT COUNT(*) AS COUNT FROM HOST_PROFILE WHERE HOST_NICKNAME=?
;

--○ MEMBER 중복검사
SELECT COUNT(*) AS COUNT
FROM MEMBER_PROFILE
WHERE MEMBER_EMAIL='test1@test.com';
--> 한줄
SELECT COUNT(*) AS COUNT FROM MEMBER_PROFILE WHERE MEMBER_EMAIL=?
;
SELECT COUNT(*) AS COUNT
FROM MEMBER_PROFILE
WHERE MEMBER_NICKNAME='탱탱볼';
--> 한줄
SELECT COUNT(*) AS COUNT FROM MEMBER_PROFILE WHERE MEMBER_NICKNAME=?
;

--○ HOST 회원가입
-- 회원코드 등록
SELECT H_SEQ.NEXTVAL
FROM DUAL;

INSERT INTO HOST(HOST_CODE, HOST_SIGN_UP_DATE)
VALUES(F_CODE('H', H_SEQ.NEXTVAL), SYSDATE);
--> 한줄
INSERT INTO HOST(HOST_CODE, HOST_SIGN_UP_DATE) VALUES(F_CODE('H', H_SEQ.NEXTVAL), SYSDATE)
;
-- 프로필정보 등록
INSERT INTO HOST_PROFILE(HOST_EMAIL, HOST_CODE
                       , HOST_PW, HOST_NICKNAME
                       , HOST_NAME, HOST_TEL)
VALUES('이메일', F_CODE('H', H_SEQ.CURRVAL), '비번'
      , '닉네임', '이름', '연락처');
--> 한줄
INSERT INTO HOST_PROFILE(HOST_EMAIL, HOST_CODE, HOST_PW, HOST_NICKNAME, HOST_NAME, HOST_TEL) VALUES(?, F_CODE('H', H_SEQ.CURRVAL), ?, ?, ?, ?)
;

-- 프로시저 호출
EXEC CREATE_HOST_ACCOUNT('sb4411@gmail.com', 'JAVA006$', '테스트홍다', '퐁퐁풍', '010-4444-4444');


--○ MEMBER 회원가입
-- 회원코드 등록
SELECT M_SEQ.NEXTVAL
FROM DUAL;

INSERT INTO MEMBER(MEMBER_CODE, MEMBER_SIGN_UP_DATE)
VALUES(F_CODE('M', M_SEQ.NEXTVAL), SYSDATE);
--> 한줄
INSERT INTO MEMBER(MEMBER_CODE, MEMBER_SIGN_UP_DATE) VALUES(F_CODE('M', M_SEQ.NEXTVAL), SYSDATE)
;
-- 프로필정보 등록
INSERT INTO MEMBER_PROFILE(MEMBER_EMAIL, MEMBER_CODE
                         , MEMBER_PW, MEMBER_NICKNAME
                         , MEMBER_NAME, MEMBER_TEL)
VALUES('이메일', F_CODE('M', M_SEQ.CURRVAL), '비번'
      , '닉네임', '이름', '연락처');
--> 한줄
INSERT INTO MEMBER_PROFILE(MEMBER_EMAIL, MEMBER_CODE, MEMBER_PW, MEMBER_NICKNAME, MEMBER_NAME, MEMBER_TEL) VALUES(?, F_CODE('M', M_SEQ.CURRVAL), ?, ?, ?, ?)
;

-- 프로시저 호출
EXEC CREATE_MEMBER_ACCOUNT('sb9229@gmail.com', 'JAVA0006$', '테3트다', '홍1훙', '010-9949-9999');

SELECT *
FROM MEMBER_PROFILE;

--######################################### 2. LOGIN

--○ MEMBER 로그인 검사
SELECT MEMBER_CODE
FROM MEMBER_PROFILE
WHERE MEMBER_EMAIL = 'test1@test.com'
  AND MEMBER_PW = 'test12345@';

--○ HOST 로그인 검사
SELECT HOST_CODE
FROM HOST_PROFILE
WHERE HOST_EMAIL = 'good1@test.com'
  AND HOST_PW = 'test12345@';

--○ MEMBER 패스워드 검사
SELECT COUNT(*) AS COUNT
FROM MEMBER_PROFILE
WHERE MEMBER_CODE = 'M000001'
  AND MEMBER_PW = 'test12345@';

--○ HOST 패스워드 검사
SELECT COUNT(*) AS COUNT
FROM HOST_PROFILE
WHERE HOST_CODE = 'H000001'
  AND HOST_PW = 'test12345@';


--######################################### 3. PROFILE

--○ MEMBER 프로필 가져오기
CREATE OR REPLACE VIEW MEMBER_PROFILEVIEW
AS
SELECT MP.MEMBER_EMAIL AS EMAIL, MP.MEMBER_CODE AS CODE
     , MP.MEMBER_PW AS PW, MP.MEMBER_NICKNAME AS NICK
     , MP.MEMBER_NAME AS NAME, MP.MEMBER_TEL AS TEL
     , TO_CHAR(M.MEMBER_SIGN_UP_DATE, 'YYYY-MM-DD') AS CREATEDATE
FROM MEMBER_PROFILE MP, MEMBER M
WHERE MP.MEMBER_CODE = M.MEMBER_CODE;

SELECT EMAIL, CODE, PW, NICK, NAME, TEL, CREATEDATE
FROM MEMBER_PROFILEVIEW
WHERE CODE = 'M000001';

--○ HOST 프로필 가져오기
CREATE OR REPLACE VIEW HOST_PROFILEVIEW
AS
SELECT HP.HOST_EMAIL AS EMAIL, HP.HOST_CODE AS CODE
     , HP.HOST_PW AS PW, HP.HOST_NICKNAME AS NICK
     , HP.HOST_NAME AS NAME, HP.HOST_TEL AS TEL
     , TO_CHAR(H.HOST_SIGN_UP_DATE, 'YYYY-MM-DD') AS CREATEDATE
FROM HOST_PROFILE HP,  HOST H
WHERE HP.HOST_CODE = H.HOST_CODE;

SELECT EMAIL, CODE, PW, NICK, NAME, TEL, CREATEDATE
FROM HOST_PROFILEVIEW
WHERE CODE = 'H000001';


--○ MEMBER 전화번호 수정
UPDATE MEMBER_PROFILE
SET MEMBER_TEL = '010-1212-1212'
WHERE MEMBER_CODE = 'M000001';

--○ HOST 전화번호 수정
UPDATE HOST_PROFILE
SET HOST_TEL = '010-1212-1212'
WHERE HOST_CODE = 'H000001';


--○ MEMBER 블랙리스트 전환일
SELECT TO_CHAR(MB.MEMBER_BLACKLIST_DATE, 'YYYY-MM-DD')
FROM MEMBER_BLACKLIST MB JOIN MEMBER_PROFILE MP
ON MB.MEMBER_EMAIL = MP.MEMBER_EMAIL
WHERE MP.MEMBER_CODE = 'M000003'
;


--○ HOST 블랙리스트 전환일
SELECT TO_CHAR(HB.HOST_BLACKLIST_DATE, 'YYYY-MM-DD')
FROM HOST_BLACKLIST HB JOIN HOST_PROFILE HP
ON HB.HOST_EMAIL = HP.HOST_EMAIL
WHERE HP.HOST_CODE = 'H000004'
;

--○ MEMBER 비밀번호 수정
UPDATE MEMBER_PROFILE
SET MEMBER_PW = '비밀번호'
WHERE MEMBER_CODE = '코드';

--○ HOST 비밀번호 수정
UPDATE HOST_PROFILE
SET HOST_PW = '비밀번호'
WHERE HOST_CODE = '코드';


--○ MEMBER 이메일 존재여부 확인
SELECT COUNT(*) AS COUNT
FROM MEMBER_PROFILE
WHERE MEMBER_EMAIL = 'sb9212@kpu.ac.kr';

--○ HOST 이메일 존재여부 확인
SELECT COUNT(*) AS COUNT
FROM HOST_PROFILE
WHERE HOST_EMAIL = 'sb921204@naver.com';


--○ MEMBER 비밀번호 변경(MEMBER)
UPDATE MEMBER_PROFILE
SET MEMBER_PW = 'java006$'
WHERE MEMBER_EMAIL = 'sb92120@gmail.com';

--○ HOST 비밀번호 변경(HOST)
UPDATE HOST_PROFILE
SET HOST_PW = 'java006$'
WHERE HOST_EMAIL = 'sb921204@naver.com';



