--○ 패키지 선언
CREATE OR REPLACE PACKAGE CRYPTPACK
AS
    FUNCTION ENCRYPT(STR VARCHAR2, HASH VARCHAR2) RETURN VARCHAR2;
    FUNCTION DECRYPT(XCRYPT VARCHAR2, HASH VARCHAR2) RETURN VARCHAR2;
END CRYPTPACK;
--==>> Package CRYPTPACK이(가) 컴파일되었습니다.


--○ 패키지 몸체 구성
CREATE OR REPLACE PACKAGE BODY CRYPTPACK
AS
    -- 전역 변수
    CRYPTED_STRING VARCHAR2(2000);
    
    -- 암호화 함수
    FUNCTION ENCRYPT(STR VARCHAR2, HASH VARCHAR2) 
    RETURN VARCHAR2
    IS
        PIECES_OF_EIGHT NUMBER := ((FLOOR(LENGTH(STR)/8+.9))*8);
    BEGIN
        DBMS_OBFUSCATION_TOOLKIT.DESENCRYPT
        ( INPUT_STRING      => RPAD(STR, PIECES_OF_EIGHT)
        , KEY_STRING        => RPAD(HASH, 8, '#')
        , ENCRYPTED_STRING  => CRYPTED_STRING
        );
        RETURN CRYPTED_STRING;
    END;
    
    -- 복호화 함수
    FUNCTION DECRYPT(XCRYPT VARCHAR2, HASH VARCHAR2) 
    RETURN VARCHAR2
    IS
    BEGIN
        DBMS_OBFUSCATION_TOOLKIT.DESDECRYPT
        ( INPUT_STRING      => XCRYPT
        , KEY_STRING        => RPAD(HASH, 8, '#')
        , DECRYPTED_STRING  => CRYPTED_STRING
        );
        RETURN TRIM(CRYPTED_STRING);
    END;
END CRYPTPACK;
--==>> Package Body CRYPTPACK이(가) 컴파일되었습니다.


-- member 계정 생성 프로시저 
CREATE OR REPLACE PROCEDURE CREATE_MEMBER_ACCOUNT
(
V_EMAIL     IN  VARCHAR2,
V_PW        IN  VARCHAR2,
V_NICK      IN  VARCHAR2,
V_NAME      IN  VARCHAR2,
V_TEL       IN  VARCHAR2
)
IS
BEGIN
    INSERT INTO MEMBER(MEMBER_CODE, MEMBER_SIGN_UP_DATE)
    VALUES(F_CODE('M', M_SEQ.NEXTVAL), SYSDATE);

    INSERT INTO MEMBER_PROFILE(MEMBER_EMAIL, MEMBER_CODE
                         , MEMBER_PW, MEMBER_NICKNAME
                         , MEMBER_NAME, MEMBER_TEL)
    VALUES(V_EMAIL, F_CODE('M', M_SEQ.CURRVAL)
         , V_PW, V_NICK
         , V_NAME, V_TEL);
         
    COMMIT;
END;


CREATE OR REPLACE PROCEDURE CREATE_HOST_ACCOUNT
(
V_EMAIL     IN  VARCHAR2,
V_PW        IN  VARCHAR2,
V_NICK      IN  VARCHAR2,
V_NAME      IN  VARCHAR2,
V_TEL       IN  VARCHAR2
)
IS
BEGIN
    INSERT INTO HOST(HOST_CODE, HOST_SIGN_UP_DATE)
    VALUES(F_CODE('H', H_SEQ.NEXTVAL), SYSDATE);

    INSERT INTO HOST_PROFILE(HOST_EMAIL, HOST_CODE
                       , HOST_PW, HOST_NICKNAME
                       , HOST_NAME, HOST_TEL)
    VALUES(V_EMAIL, F_CODE('H', H_SEQ.CURRVAL)
         , V_PW, V_NICK
         , V_NAME, V_TEL);
         
    COMMIT;
END;








