-- DUMMY DATA
-- ※※※ 돌리기 전에 F_CODE 함수를 먼저 만들어 주세요.
--============================================================= 0. ADMIN

-- ADMIN(관리자)
INSERT INTO ADMIN(ADMIN_ID, ADMIN_PW, ADMIN_NICKNAME)
VALUES('admin_lookation01', 'java006$', '관리자_1');

--============================================================= 1. FAQ, NOTICE
-- IMPORTANT_NOTICE(중요공지 분류, 숫자)
INSERT INTO IMPORTANT_NOTICE(IMPORTANT_NOTICE_CODE, IMPORTANT_NOTICE)
VALUES(F_CODE('IN', 1), '중요공지');

INSERT INTO IMPORTANT_NOTICE(IMPORTANT_NOTICE_CODE, IMPORTANT_NOTICE)
VALUES(F_CODE('IN', 2), '일반공지');


-- NOTICE(공지사항, N)
CREATE SEQUENCE N_SEQ
NOCACHE;

INSERT INTO NOTICE(NOTICE_CODE, IMPORTANT_NOTICE_CODE, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE)
VALUES(F_CODE('N', N_SEQ.NEXTVAL), 'IN000002', '안내드립니다.', '코로나로 인해 장사 안하는 집이 많습니다. 확인 부탁드립니다.', SYSDATE);

INSERT INTO NOTICE(NOTICE_CODE, IMPORTANT_NOTICE_CODE, NOTICE_TITLE, NOTICE_CONTENT, NOTICE_DATE)
VALUES(F_CODE('N', N_SEQ.NEXTVAL), 'IN000001', '개인정보유출이슈', '저희는 개인정보 유출을 안했는데 어쩌고...', SYSDATE);

-- ATTACHMENT(첨부파일(공지사항), AT)
CREATE SEQUENCE AT_SEQ
NOCACHE;

INSERT INTO ATTACHMENT
VALUES(F_CODE('AT', AT_SEQ.NEXTVAL), 'N000001', 'AT_TEST01');


-- BOARD_TYPE(게시물 분류, 코드)
INSERT INTO BOARD_TYPE (BOARD_TYPE_CODE, BOARD_TYPE) 
VALUES (F_CODE('BT',1), '호스트되기');

INSERT INTO BOARD_TYPE (BOARD_TYPE_CODE, BOARD_TYPE) 
VALUES (F_CODE('BT',2), '공간등록');

INSERT INTO BOARD_TYPE (BOARD_TYPE_CODE, BOARD_TYPE) 
VALUES (F_CODE('BT',3), '공간조회');

INSERT INTO BOARD_TYPE (BOARD_TYPE_CODE, BOARD_TYPE) 
VALUES (F_CODE('BT',4), '공간정보관리');

INSERT INTO BOARD_TYPE (BOARD_TYPE_CODE, BOARD_TYPE) 
VALUES (F_CODE('BT',5), '예약및결제');

INSERT INTO BOARD_TYPE (BOARD_TYPE_CODE, BOARD_TYPE) 
VALUES (F_CODE('BT',6), '취소및환불');

INSERT INTO BOARD_TYPE (BOARD_TYPE_CODE, BOARD_TYPE) 
VALUES (F_CODE('BT',7), '공간이용및후기');

INSERT INTO BOARD_TYPE (BOARD_TYPE_CODE, BOARD_TYPE) 
VALUES (F_CODE('BT',8), '공간정보관리');

INSERT INTO BOARD_TYPE (BOARD_TYPE_CODE, BOARD_TYPE) 
VALUES (F_CODE('BT',9), '기타');


-- HELP(도움말, HLP)
CREATE SEQUENCE HLP_SEQ
NOCACHE;

INSERT INTO HELP(HELP_CODE, BOARD_TYPE_CODE, HELP_TITLE, HELP_CONTENT, HELP_DATE)
VALUES(F_CODE('HLP', HLP_SEQ.NEXTVAL), 'BT000001', '호스트가 되고 싶어요.'
, '바로 LOOKATION에서 공간등록을 하세요.', TO_DATE('2021-01-01','YYYY-MM-DD'));

INSERT INTO HELP(HELP_CODE, BOARD_TYPE_CODE, HELP_TITLE, HELP_CONTENT, HELP_DATE)
VALUES(F_CODE('HLP', HLP_SEQ.NEXTVAL), 'BT000002', '공간 등록을 하고싶어요.'
, '회원 가입 후 공간 등록을 할 수 있습니다.', TO_DATE('2021-01-02','YYYY-MM-DD'));


-- NOTICE_IMG(이미지(공지사항), NIMG)
CREATE SEQUENCE NIMG_SEQ
NOCACHE;

INSERT INTO NOTICE_IMG(NOTICE_IMG_CODE, NOTICE_CODE, NOTICE_IMG_URL)
VALUES(F_CODE('NIMG', NIMG_SEQ.NEXTVAL), 'N000001' , '공지사항사진.JPG');


-- HELP_IMG(이미지(도움말), HLPIMG)
CREATE SEQUENCE HLPIMG_SEQ
NOCACHE;

INSERT INTO HELP_IMG(HELP_IMG_CODE, HELP_CODE, HELP_IMG_URL)
VALUES(F_CODE('HLPIMG', HLPIMG_SEQ.NEXTVAL), 'HLP000001' , '도움말사진.JPG');


--============================================================= 2. USER

-- MEMBER(회원(이용자), M)
CREATE SEQUENCE M_SEQ
NOCACHE;

INSERT INTO MEMBER(MEMBER_CODE, MEMBER_SIGN_UP_DATE)
VALUES(F_CODE('M', M_SEQ.NEXTVAL), TO_DATE('2019-08-03', 'YYYY-MM-DD'));

INSERT INTO MEMBER(MEMBER_CODE, MEMBER_SIGN_UP_DATE)
VALUES(F_CODE('M', M_SEQ.NEXTVAL), TO_DATE('2019-08-17', 'YYYY-MM-DD'));

INSERT INTO MEMBER(MEMBER_CODE, MEMBER_SIGN_UP_DATE)
VALUES(F_CODE('M', M_SEQ.NEXTVAL), TO_DATE('2019-08-18', 'YYYY-MM-DD'));

INSERT INTO MEMBER(MEMBER_CODE, MEMBER_SIGN_UP_DATE)
VALUES(F_CODE('M', M_SEQ.NEXTVAL), TO_DATE('2019-09-01', 'YYYY-MM-DD'));

INSERT INTO MEMBER(MEMBER_CODE, MEMBER_SIGN_UP_DATE)
VALUES(F_CODE('M', M_SEQ.NEXTVAL), TO_DATE('2019-11-21', 'YYYY-MM-DD'));


-- MEMBER_PROFILE(프로필정보(이용자))
INSERT INTO MEMBER_PROFILE(MEMBER_EMAIL, MEMBER_CODE, MEMBER_PW
                         , MEMBER_NICKNAME, MEMBER_NAME, MEMBER_TEL)
VALUES('test1@test.com', 'M000001', 'test12345@'
     , '탱탱볼', '홍길동', '010-1111-1111');

INSERT INTO MEMBER_PROFILE(MEMBER_EMAIL, MEMBER_CODE, MEMBER_PW
                         , MEMBER_NICKNAME, MEMBER_NAME, MEMBER_TEL)
VALUES('test2@test.com', 'M000002', 'hello7777!'
     , '와이라노', '권소윤', '010-2222-2222');

INSERT INTO MEMBER_PROFILE(MEMBER_EMAIL, MEMBER_CODE, MEMBER_PW
                         , MEMBER_NICKNAME, MEMBER_NAME, MEMBER_TEL)
VALUES('test3@test.com', 'M000003', 'tbqkffjal33#'
     , '고구마', '김감자', '010-3333-3333');

INSERT INTO MEMBER_PROFILE(MEMBER_EMAIL, MEMBER_CODE, MEMBER_PW
                         , MEMBER_NICKNAME, MEMBER_NAME, MEMBER_TEL)
VALUES('lookation1@naver.com', 'M000004', 'java006!'
     , '베짱이', '주재완', '010-1234-4567');

INSERT INTO MEMBER_PROFILE(MEMBER_EMAIL, MEMBER_CODE, MEMBER_PW
                , MEMBER_NICKNAME, MEMBER_NAME, MEMBER_TEL)
VALUES('lookation2@daum.com', 'M000005', 'java006@'
     , '개미', '김일웅', '010-2345-6789');
     
-- MEMBER_BANK_INFO(계좌정보(이용자))
INSERT INTO MEMBER_BANK_INFO(MEMBER_BANK_NUMBER, MEMBER_CODE
                           , MEMBER_BANK, MEMBER_BANK_HOLDER)
VALUES('110-343-936673', 'M000001', '신한은행', '김승범');

INSERT INTO MEMBER_BANK_INFO(MEMBER_BANK_NUMBER, MEMBER_CODE
                           , MEMBER_BANK, MEMBER_BANK_HOLDER)
VALUES('1002-048-273134', 'M000001', '국민은행', '신승범');

INSERT INTO MEMBER_BANK_INFO(MEMBER_BANK_NUMBER, MEMBER_CODE
                          , MEMBER_BANK, MEMBER_BANK_HOLDER)
VALUES('554602-04-076182', 'M000002', '국민은행', '조윤상');

INSERT INTO MEMBER_BANK_INFO(MEMBER_BANK_NUMBER, MEMBER_CODE
                          , MEMBER_BANK, MEMBER_BANK_HOLDER)
VALUES('545777-48488-76182', 'M000003', '우리은행', '진영은');

INSERT INTO MEMBER_BANK_INFO(MEMBER_BANK_NUMBER, MEMBER_CODE
                          , MEMBER_BANK, MEMBER_BANK_HOLDER)
VALUES('878117-9897-171533', 'M000004', '신한은행', '김호진');


-- MEMBER_WITHDRAW(탈퇴(이용자), MW)
CREATE SEQUENCE MW_SEQ
NOCACHE;

INSERT INTO MEMBER_WITHDRAW (MEMBER_WITHDRAW_CODE, MEMBER_CODE, MEMBER_WITHDRAW_DATE) 
VALUES (F_CODE('MW',MW_SEQ.NEXTVAL), 'M000001', TO_DATE('2021-01-02','YYYY-MM-DD'));


-- MEMBER_BLACKLIST(블랙리스트(이용자))
INSERT INTO MEMBER_BLACKLIST (MEMBER_EMAIL, MEMBER_BLACKLIST_REASON
                            , MEMBER_BLACKLIST_DATE) 
VALUES ('test3@test.com', '블랙리스트사유',TO_DATE('2020-12-02','YYYY-MM-DD'));

--============================================================== 3. HOST

-- HOST(회원(호스트), H) 
CREATE SEQUENCE H_SEQ
NOCACHE;

INSERT INTO HOST(HOST_CODE, HOST_SIGN_UP_DATE)
VALUES(F_CODE('H', H_SEQ.NEXTVAL), TO_DATE('2019-03-08', 'YYYY-MM-DD'));

INSERT INTO HOST(HOST_CODE, HOST_SIGN_UP_DATE)
VALUES(F_CODE('H', H_SEQ.NEXTVAL), TO_DATE('2019-07-18', 'YYYY-MM-DD'));

INSERT INTO HOST(HOST_CODE, HOST_SIGN_UP_DATE)
VALUES(F_CODE('H', H_SEQ.NEXTVAL), TO_DATE('2019-01-08', 'YYYY-MM-DD'));

INSERT INTO HOST(HOST_CODE, HOST_SIGN_UP_DATE)
VALUES(F_CODE('H', H_SEQ.NEXTVAL), TO_DATE('2019-05-05', 'YYYY-MM-DD'));

INSERT INTO HOST(HOST_CODE, HOST_SIGN_UP_DATE)
VALUES(F_CODE('H', H_SEQ.NEXTVAL), TO_DATE('2019-12-04', 'YYYY-MM-DD'));


-- HOST_PROFILE(프로필정보(호스트)) 
INSERT INTO HOST_PROFILE(HOST_EMAIL, HOST_CODE, HOST_PW
                         , HOST_NICKNAME, HOST_NAME, HOST_TEL)
VALUES('good1@test.com', 'H000001', 'test12345@'
     , '퉁퉁볼', '고길동', '010-1111-1111');

INSERT INTO HOST_PROFILE(HOST_EMAIL, HOST_CODE, HOST_PW
                         , HOST_NICKNAME, HOST_NAME, HOST_TEL)
VALUES('good2@test.com', 'H000002', 'hello7777!'
     , '노라이와', '권순자', '010-2222-2222');

INSERT INTO HOST_PROFILE(HOST_EMAIL, HOST_CODE, HOST_PW
                         , HOST_NICKNAME, HOST_NAME, HOST_TEL)
VALUES('good3@test.com', 'H000003', 'tbqkffjal33#'
     , '감자', '김고구마', '010-3333-3333');

INSERT INTO HOST_PROFILE(HOST_EMAIL, HOST_CODE, HOST_PW
                         , HOST_NICKNAME, HOST_NAME, HOST_TEL)
VALUES('lookationgood1@naver.com', 'H000004', 'java006!'
     , '기타리스트', '주꾸미', '010-1234-4567');

INSERT INTO HOST_PROFILE(HOST_EMAIL, HOST_CODE, HOST_PW
                         , HOST_NICKNAME, HOST_NAME, HOST_TEL)
VALUES('lookationgood2@daum.com', 'H000005', 'java006@'
     , '거미', '곽두팔', '010-2345-6789');
     
     
-- HOST_BANK_INFO(계좌정보(호스트))
INSERT INTO HOST_BANK_INFO(HOST_BANK_NUMBER, HOST_CODE
                           , HOST_BANK, HOST_BANK_HOLDER)
VALUES('601245-02-201535', 'H000001', '우체국은행', '신용자');

INSERT INTO HOST_BANK_INFO(HOST_BANK_NUMBER, HOST_CODE
                           , HOST_BANK, HOST_BANK_HOLDER)
VALUES('010-3441-0260', 'H000001', '기업은행', '김범승');

INSERT INTO HOST_BANK_INFO(HOST_BANK_NUMBER, HOST_CODE
                           , HOST_BANK, HOST_BANK_HOLDER)
VALUES('345-1245235-986', 'H000002', '시티은행', '이다도시');

INSERT INTO HOST_BANK_INFO(HOST_BANK_NUMBER, HOST_CODE
                           , HOST_BANK, HOST_BANK_HOLDER)
VALUES('542-7824-6386-44', 'H000003', '부산은행', '갈매기');

INSERT INTO HOST_BANK_INFO(HOST_BANK_NUMBER, HOST_CODE
                           , HOST_BANK, HOST_BANK_HOLDER)
VALUES('7754-45-3547875', 'H000004', '카카오뱅크', '제이지');

-- HOST_BLACKLIST(탈퇴(이용자), HW)
CREATE SEQUENCE HW_SEQ
NOCACHE;

INSERT INTO HOST_WITHDRAW (HOST_WITHDRAW_CODE, HOST_CODE, HOST_WITHDRAW_DATE) 
VALUES (F_CODE('HW', HW_SEQ.NEXTVAL), 'H000001', TO_DATE('2020-09-02','YYYY-MM-DD'));

-- 블랙리스트
INSERT INTO HOST_BLACKLIST (HOST_EMAIL, HOST_BLACKLIST_REASON, HOST_BLACKLIST_DATE) 
VALUES ('lookationgood1@naver.com', '블랙리스트사유', TO_DATE('2021-01-08','YYYY-MM-DD'));


--============================================================= 4. LOCATION

-- LOC(공간, L)
CREATE SEQUENCE L_SEQ
NOCACHE;

INSERT INTO LOC(LOC_CODE, HOST_CODE, LOC_REG_DATE)
VALUES(F_CODE('L', L_SEQ.NEXTVAL), 'H000001', TO_DATE('2020-01-21', 'YYYY-MM-DD'));

INSERT INTO LOC(LOC_CODE, HOST_CODE, LOC_REG_DATE)
VALUES(F_CODE('L', L_SEQ.NEXTVAL), 'H000002', TO_DATE('2020-04-23', 'YYYY-MM-DD'));

INSERT INTO LOC(LOC_CODE, HOST_CODE, LOC_REG_DATE)
VALUES(F_CODE('L', L_SEQ.NEXTVAL), 'H000003', TO_DATE('2020-04-29', 'YYYY-MM-DD'));

INSERT INTO LOC(LOC_CODE, HOST_CODE, LOC_REG_DATE)
VALUES(F_CODE('L', L_SEQ.NEXTVAL), 'H000004', TO_DATE('2020-06-30', 'YYYY-MM-DD'));

INSERT INTO LOC(LOC_CODE, HOST_CODE, LOC_REG_DATE)
VALUES(F_CODE('L', L_SEQ.NEXTVAL), 'H000005', TO_DATE('2020-08-01', 'YYYY-MM-DD'));


-- BIZ_INFO(사업자정보, BZ)
CREATE SEQUENCE BZ_SEQ
NOCACHE;

INSERT INTO BIZ_INFO(BIZ_INFO_CODE, LOC_CODE, BIZ_NAME
                            , BIZ_CEO, BIZ_LICENSE_URL, BIZ_CEO_TYPE, BIZ_MAIN_TYPE
                            , BIZ_SUB_TYPE, BIZ_ADDR, BIZ_LICENSE_NUMBER)
VALUES(F_CODE('BZ', BZ_SEQ.NEXTVAL), 'L000001', '쌍용주식회사'
          , '김일웅', '쌍용사업자등록증.jpg', '개인사업자', '요식업'
          , '이자카야', '서울시 마포구 서교동 18-18', '123-45-67890');

INSERT INTO BIZ_INFO(BIZ_INFO_CODE, LOC_CODE, BIZ_NAME
                            , BIZ_CEO, BIZ_LICENSE_URL, BIZ_CEO_TYPE, BIZ_MAIN_TYPE
                            , BIZ_SUB_TYPE, BIZ_ADDR, BIZ_LICENSE_NUMBER)
VALUES(F_CODE('BZ', BZ_SEQ.NEXTVAL), 'L000002', '몬스터주식회사'
          , '김괴물', '몬스터사업자등록증.jpg', '법인사업자', '농업'
          , '벼농사', '인천광역시 미추홀구 낙섬중로 10-10', '234-44-45890');

INSERT INTO BIZ_INFO(BIZ_INFO_CODE, LOC_CODE, BIZ_NAME
                            , BIZ_CEO, BIZ_LICENSE_URL, BIZ_CEO_TYPE, BIZ_MAIN_TYPE
                            , BIZ_SUB_TYPE, BIZ_ADDR, BIZ_LICENSE_NUMBER)
VALUES(F_CODE('BZ', BZ_SEQ.NEXTVAL), 'L000003', '삼성전자'
          , '이재용', '삼성전자사업자등록증.jpg', '법인사업자', 'IT'
          , 'JAVA', '서울시 동대문구 답십리동 1-2', '321-24-55890');

INSERT INTO BIZ_INFO(BIZ_INFO_CODE, LOC_CODE, BIZ_NAME
                            , BIZ_CEO, BIZ_LICENSE_URL, BIZ_CEO_TYPE, BIZ_MAIN_TYPE
                            , BIZ_SUB_TYPE, BIZ_ADDR, BIZ_LICENSE_NUMBER)
VALUES(F_CODE('BZ', BZ_SEQ.NEXTVAL), 'L000004', '호반건설'
          , '김수한무', '호반사업자등록증.jpg', '간이과세자', '건설업'
          , 'CAD', '서울시 송파구 장지동 10-20', '369-96-78945');

INSERT INTO BIZ_INFO(BIZ_INFO_CODE, LOC_CODE, BIZ_NAME
                            , BIZ_CEO, BIZ_LICENSE_URL, BIZ_CEO_TYPE, BIZ_MAIN_TYPE
                            , BIZ_SUB_TYPE, BIZ_ADDR, BIZ_LICENSE_NUMBER)
VALUES(F_CODE('BZ', BZ_SEQ.NEXTVAL), 'L000005', '자반주식회사'
          , '김자반', '자반사업자등록증.jpg', '면세사업자', '상업'
          , '해조류판매', '전라남도 신안군 지도읍 30-50', '789-98-45644');


-- LOC_CONTACT(연락처, LC)
CREATE SEQUENCE LC_SEQ
NOCACHE;

INSERT INTO LOC_CONTACT(LOC_CONTACT_CODE, LOC_CODE
                      , LOC_EMAIL, LOC_TEL, LOC_MAIN_TEL)
VALUES(F_CODE('LC', LC_SEQ.NEXTVAL), 'L000001'
         , 'test1@test.com', '010-1234-5678', '02-736-1234');

INSERT INTO LOC_CONTACT(LOC_CONTACT_CODE, LOC_CODE
                      , LOC_EMAIL, LOC_TEL, LOC_MAIN_TEL)
VALUES(F_CODE('LC', LC_SEQ.NEXTVAL), 'L000002'
         , 'test2@test.com', '010-2234-5678', '032-123-2345');

INSERT INTO LOC_CONTACT(LOC_CONTACT_CODE, LOC_CODE
                      , LOC_EMAIL, LOC_TEL, LOC_MAIN_TEL)
VALUES(F_CODE('LC', LC_SEQ.NEXTVAL), 'L000003'
         , 'test3@test.com', '010-3234-5678', '02-123-2345');

INSERT INTO LOC_CONTACT(LOC_CONTACT_CODE, LOC_CODE
                      , LOC_EMAIL, LOC_TEL, LOC_MAIN_TEL)
VALUES(F_CODE('LC', LC_SEQ.NEXTVAL), 'L000004'
         , 'test4@test.com', '010-4234-5678', '02-123-2345');

INSERT INTO LOC_CONTACT(LOC_CONTACT_CODE, LOC_CODE
                      , LOC_EMAIL, LOC_TEL, LOC_MAIN_TEL)
VALUES(F_CODE('LC', LC_SEQ.NEXTVAL), 'L000005'
         , 'test5@test.com', '010-5234-5678', '061-275-1234');


-- LOC_DETAIL_INFO
CREATE SEQUENCE LDIF_SEQ
NOCACHE;

INSERT INTO LOC_DETAIL_INFO (LOC_DETAIL_INFO_CODE, LOC_CODE, MIN_PEOPLE, MAX_PEOPLE) 
VALUES (F_CODE('LDIF',LDIF_SEQ.NEXTVAL), 'L000001', 5, 15);

INSERT INTO LOC_DETAIL_INFO (LOC_DETAIL_INFO_CODE, LOC_CODE, MIN_PEOPLE, MAX_PEOPLE) 
VALUES (F_CODE('LDIF',LDIF_SEQ.NEXTVAL), 'L000002', 3, 12);

INSERT INTO LOC_DETAIL_INFO (LOC_DETAIL_INFO_CODE, LOC_CODE, MIN_PEOPLE, MAX_PEOPLE) 
VALUES (F_CODE('LDIF',LDIF_SEQ.NEXTVAL), 'L000003', 7, 10);

INSERT INTO LOC_DETAIL_INFO (LOC_DETAIL_INFO_CODE, LOC_CODE, MIN_PEOPLE, MAX_PEOPLE) 
VALUES (F_CODE('LDIF',LDIF_SEQ.NEXTVAL), 'L000004', 8, 15);

INSERT INTO LOC_DETAIL_INFO (LOC_DETAIL_INFO_CODE, LOC_CODE, MIN_PEOPLE, MAX_PEOPLE) 
VALUES (F_CODE('LDIF',LDIF_SEQ.NEXTVAL), 'L000005', 5, 10);


-- LOC_DETAIL_IMG

CREATE SEQUENCE LDIMG_SEQ
NOCACHE;

INSERT INTO LOC_DETAIL_IMG (LOC_DETAIL_IMG_CODE, LOC_DETAIL_INFO_CODE
, LOC_DETAIL_IMG_URL) 
VALUES (F_CODE('LDIMG',LDIMG_SEQ.NEXTVAL), 'LDIF000001', 'IMGURL1');

INSERT INTO LOC_DETAIL_IMG (LOC_DETAIL_IMG_CODE, LOC_DETAIL_INFO_CODE
, LOC_DETAIL_IMG_URL) 
VALUES (F_CODE('LDIMG',LDIMG_SEQ.NEXTVAL), 'LDIF000001', 'IMGURL2');

INSERT INTO LOC_DETAIL_IMG (LOC_DETAIL_IMG_CODE, LOC_DETAIL_INFO_CODE
, LOC_DETAIL_IMG_URL) 
VALUES (F_CODE('LDIMG',LDIMG_SEQ.NEXTVAL), 'LDIF000002', 'IMGURL3');

INSERT INTO LOC_DETAIL_IMG (LOC_DETAIL_IMG_CODE, LOC_DETAIL_INFO_CODE
, LOC_DETAIL_IMG_URL) 
VALUES (F_CODE('LDIMG',LDIMG_SEQ.NEXTVAL), 'LDIF000002', 'IMGURL4');

INSERT INTO LOC_DETAIL_IMG (LOC_DETAIL_IMG_CODE, LOC_DETAIL_INFO_CODE
, LOC_DETAIL_IMG_URL) 
VALUES (F_CODE('LDIMG',LDIMG_SEQ.NEXTVAL), 'LDIF000003', 'IMGURL5');

INSERT INTO LOC_DETAIL_IMG (LOC_DETAIL_IMG_CODE, LOC_DETAIL_INFO_CODE
, LOC_DETAIL_IMG_URL) 
VALUES (F_CODE('LDIMG',LDIMG_SEQ.NEXTVAL), 'LDIF000003', 'IMGURL6');

INSERT INTO LOC_DETAIL_IMG (LOC_DETAIL_IMG_CODE, LOC_DETAIL_INFO_CODE
, LOC_DETAIL_IMG_URL) 
VALUES (F_CODE('LDIMG',LDIMG_SEQ.NEXTVAL), 'LDIF000004', 'IMGURL7');

INSERT INTO LOC_DETAIL_IMG (LOC_DETAIL_IMG_CODE, LOC_DETAIL_INFO_CODE
, LOC_DETAIL_IMG_URL) 
VALUES (F_CODE('LDIMG',LDIMG_SEQ.NEXTVAL), 'LDIF000004', 'IMGURL8');

INSERT INTO LOC_DETAIL_IMG (LOC_DETAIL_IMG_CODE, LOC_DETAIL_INFO_CODE
, LOC_DETAIL_IMG_URL) 
VALUES (F_CODE('LDIMG',LDIMG_SEQ.NEXTVAL), 'LDIF000005', 'IMGURL9');

INSERT INTO LOC_DETAIL_IMG (LOC_DETAIL_IMG_CODE, LOC_DETAIL_INFO_CODE
, LOC_DETAIL_IMG_URL) 
VALUES (F_CODE('LDIMG',LDIMG_SEQ.NEXTVAL), 'LDIF000005', 'IMGURL10');


-- LOC_USE_INFO
CREATE SEQUENCE LUI_SEQ
NOCACHE;

INSERT INTO LOC_USE_INFO (LOC_USE_INFO_CODE, LOC_CODE, LOC_USE_HOUR
                            , LOC_USE_DAY_OFF, LOC_USE_APPOINT_DAY_OFF) 
VALUES (F_CODE('LUI', LUI_SEQ.NEXTVAL), 'L000001', '11:00 ~ 22:00', '매주일요일', '12/21, 12/27');

INSERT INTO LOC_USE_INFO (LOC_USE_INFO_CODE, LOC_CODE, LOC_USE_HOUR
                            , LOC_USE_DAY_OFF, LOC_USE_APPOINT_DAY_OFF) 
VALUES (F_CODE('LUI', LUI_SEQ.NEXTVAL), 'L000002', '10:00 ~ 23:00', '연중무휴', '연중무휴');

INSERT INTO LOC_USE_INFO (LOC_USE_INFO_CODE, LOC_CODE, LOC_USE_HOUR
                            , LOC_USE_DAY_OFF, LOC_USE_APPOINT_DAY_OFF) 
VALUES (F_CODE('LUI', LUI_SEQ.NEXTVAL), 'L000003', '11:00 ~ 22:00', '둘째 넷째 수요일', '12/28, 1/3, 2/8, 3/16');

INSERT INTO LOC_USE_INFO (LOC_USE_INFO_CODE, LOC_CODE, LOC_USE_HOUR
                            , LOC_USE_DAY_OFF, LOC_USE_APPOINT_DAY_OFF) 
VALUES (F_CODE('LUI', LUI_SEQ.NEXTVAL), 'L000004', '11:00 ~ 24:00', '매주 월요일', '없음');

INSERT INTO LOC_USE_INFO (LOC_USE_INFO_CODE, LOC_CODE, LOC_USE_HOUR
                            , LOC_USE_DAY_OFF, LOC_USE_APPOINT_DAY_OFF) 
VALUES (F_CODE('LUI', LUI_SEQ.NEXTVAL), 'L000005', '14:00 ~ 22:00', '매주 화요일', '2/11,4/15');


--LOC_TYPE(공간분류, LOCT)
		INSERT INTO LOC_TYPE (LOC_TYPE_CODE, LOC_TYPE) 
		VALUES (F_CODE('LOCT',1), '파티룸');
		
		INSERT INTO LOC_TYPE (LOC_TYPE_CODE, LOC_TYPE) 
		VALUES (F_CODE('LOCT',2), '클럽');
		
		INSERT INTO LOC_TYPE (LOC_TYPE_CODE, LOC_TYPE) 
		VALUES (F_CODE('LOCT',3), '엠티장소');
		
		INSERT INTO LOC_TYPE (LOC_TYPE_CODE, LOC_TYPE) 
		VALUES (F_CODE('LOCT',4), '워크샵장소');

		INSERT INTO LOC_TYPE (LOC_TYPE_CODE, LOC_TYPE) 
		VALUES (F_CODE('LOCT',5), '루프탑');

		INSERT INTO LOC_TYPE (LOC_TYPE_CODE, LOC_TYPE) 
		VALUES (F_CODE('LOCT',6), '브라이덜샤워');

--LOC_BASIC_INFO(기본정보, LBIF) 
CREATE SEQUENCE LBIF_SEQ
NOCACHE;

INSERT INTO LOC_BASIC_INFO (LOC_BASIC_INFO_CODE, LOC_CODE, LOC_TYPE_CODE
, LOC_NAME, LOC_SHORT_INTRO, LOC_INTRO, LOC_ADDR, LOC_DETAIL_ADDR) 
VALUES (F_CODE('LBIF', LBIF_SEQ.NEXTVAL), 'L000001','LOCT000001'
, '어승승일산', '일산최고의핫플레이스', '공간소개', '경기도 고양시 덕양구 주교동', '고양시청로 10');

INSERT INTO LOC_BASIC_INFO (LOC_BASIC_INFO_CODE, LOC_CODE, LOC_TYPE_CODE
, LOC_NAME, LOC_SHORT_INTRO, LOC_INTRO, LOC_ADDR, LOC_DETAIL_ADDR) 
VALUES (F_CODE('LBIF', LBIF_SEQ.NEXTVAL), 'L000002','LOCT000002'
, '어승승홍대', '홍대최고의핫플레이스', '공간소개', '서울시 마포구 서교동', '201호');

INSERT INTO LOC_BASIC_INFO (LOC_BASIC_INFO_CODE, LOC_CODE, LOC_TYPE_CODE
, LOC_NAME, LOC_SHORT_INTRO, LOC_INTRO, LOC_ADDR, LOC_DETAIL_ADDR) 
VALUES (F_CODE('LBIF', LBIF_SEQ.NEXTVAL), 'L000003','LOCT000002'
, '어승승응암', '응암최고의핫플레이스', '공간소개', '서울시 서대문구 응암동', '301호');

INSERT INTO LOC_BASIC_INFO (LOC_BASIC_INFO_CODE, LOC_CODE, LOC_TYPE_CODE
, LOC_NAME, LOC_SHORT_INTRO, LOC_INTRO, LOC_ADDR, LOC_DETAIL_ADDR) 
VALUES (F_CODE('LBIF', LBIF_SEQ.NEXTVAL), 'L000004','LOCT000004'
, '어승승오산', '오산최고의핫플레이스', '공간소개', '경기도 오산시 오산동', '401호');

INSERT INTO LOC_BASIC_INFO (LOC_BASIC_INFO_CODE, LOC_CODE, LOC_TYPE_CODE
, LOC_NAME, LOC_SHORT_INTRO, LOC_INTRO, LOC_ADDR, LOC_DETAIL_ADDR) 
VALUES (F_CODE('LBIF', LBIF_SEQ.NEXTVAL), 'L000005','LOCT000003'
, '어승승인천', '인천최고의핫플레이스', '공간소개', '인천광역시 부평구 부평6동 ', '501호');


--THUMBNAIL(썸네일(기본정보), TH) 

CREATE SEQUENCE TH_SEQ
NOCACHE;

INSERT INTO THUMBNAIL (THUMBNAIL_CODE, LOC_BASIC_INFO_CODE, THUMBNAIL_URL) 
VALUES (F_CODE('TH', TH_SEQ.NEXTVAL),  'LBIF000001', '썸네일링크1');

INSERT INTO THUMBNAIL (THUMBNAIL_CODE, LOC_BASIC_INFO_CODE, THUMBNAIL_URL) 
VALUES (F_CODE('TH', TH_SEQ.NEXTVAL),  'LBIF000002', '썸네일링크2');

INSERT INTO THUMBNAIL (THUMBNAIL_CODE, LOC_BASIC_INFO_CODE, THUMBNAIL_URL) 
VALUES (F_CODE('TH', TH_SEQ.NEXTVAL),  'LBIF000003', '썸네일링크3');

INSERT INTO THUMBNAIL (THUMBNAIL_CODE, LOC_BASIC_INFO_CODE, THUMBNAIL_URL) 
VALUES (F_CODE('TH', TH_SEQ.NEXTVAL),  'LBIF000004', '썸네일링크4');

INSERT INTO THUMBNAIL (THUMBNAIL_CODE, LOC_BASIC_INFO_CODE, THUMBNAIL_URL) 
VALUES (F_CODE('TH', TH_SEQ.NEXTVAL),  'LBIF000005', '썸네일링크5');


-- FACILITY_INFO
CREATE SEQUENCE FIF_SEQ
NOCACHE;

INSERT INTO FACILITY_INFO(FACILITY_CODE, LOC_BASIC_INFO_CODE
                        , FACILITY_CONTENT)
VALUES(F_CODE('FIF', FIF_SEQ.NEXTVAL), 'LBIF000001', '파티용풍 무료지급');

INSERT INTO FACILITY_INFO(FACILITY_CODE, LOC_BASIC_INFO_CODE
                        , FACILITY_CONTENT)
VALUES(F_CODE('FIF', FIF_SEQ.NEXTVAL), 'LBIF000002', '카메라 대여 가능(추가결제 필요)');

INSERT INTO FACILITY_INFO(FACILITY_CODE, LOC_BASIC_INFO_CODE
                        , FACILITY_CONTENT)
VALUES(F_CODE('FIF', FIF_SEQ.NEXTVAL), 'LBIF000003', '웰컴음료 드립니다.');

INSERT INTO FACILITY_INFO(FACILITY_CODE, LOC_BASIC_INFO_CODE
                        , FACILITY_CONTENT)
VALUES(F_CODE('FIF', FIF_SEQ.NEXTVAL), 'LBIF000004', '내부 흡연실 완비');

INSERT INTO FACILITY_INFO(FACILITY_CODE, LOC_BASIC_INFO_CODE
                        , FACILITY_CONTENT)
VALUES(F_CODE('FIF', FIF_SEQ.NEXTVAL), 'LBIF000005', '사진 찍을 때 소품 구비');


-- CAUTION
CREATE SEQUENCE CAU_SEQ
NOCACHE;

INSERT INTO CAUTION(CAUTION_CODE, LOC_BASIC_INFO_CODE
                  , CAUTION_CONTENT)
VALUES(F_CODE('CAU', CAU_SEQ.NEXTVAL), 'LBIF000001', '내부 흡연 불가');
INSERT INTO CAUTION(CAUTION_CODE, LOC_BASIC_INFO_CODE
                  , CAUTION_CONTENT)
VALUES(F_CODE('CAU', CAU_SEQ.NEXTVAL), 'LBIF000002', '연장 불가능합니다. 퇴실시간 엄수');
INSERT INTO CAUTION(CAUTION_CODE, LOC_BASIC_INFO_CODE
                  , CAUTION_CONTENT)
VALUES(F_CODE('CAU', CAU_SEQ.NEXTVAL), 'LBIF000003', '건물 내 주차공간 협소. 자차 이용시 공영주차장 이용 바람.');
INSERT INTO CAUTION(CAUTION_CODE, LOC_BASIC_INFO_CODE
                  , CAUTION_CONTENT)
VALUES(F_CODE('CAU', CAU_SEQ.NEXTVAL), 'LBIF000004', '주변이 주택가라 밤에는 소음에 주의해주세요.');
INSERT INTO CAUTION(CAUTION_CODE, LOC_BASIC_INFO_CODE
                  , CAUTION_CONTENT)
VALUES(F_CODE('CAU', CAU_SEQ.NEXTVAL), 'LBIF000005', '코로나로 인해 5인 이상 예약 불가');


-- PACKAGE_FORM
CREATE SEQUENCE PF_SEQ
NOCACHE;

INSERT INTO PACKAGE_FORM(PACKAGE_FORM_CODE, LOC_CODE)
VALUES(F_CODE('PF', PF_SEQ.NEXTVAL), 'L000001');

INSERT INTO PACKAGE_FORM(PACKAGE_FORM_CODE, LOC_CODE)
VALUES(F_CODE('PF', PF_SEQ.NEXTVAL), 'L000002');

INSERT INTO PACKAGE_FORM(PACKAGE_FORM_CODE, LOC_CODE)
VALUES(F_CODE('PF', PF_SEQ.NEXTVAL), 'L000003');

INSERT INTO PACKAGE_FORM(PACKAGE_FORM_CODE, LOC_CODE)
VALUES(F_CODE('PF', PF_SEQ.NEXTVAL), 'L000004');

INSERT INTO PACKAGE_FORM(PACKAGE_FORM_CODE, LOC_CODE)
VALUES(F_CODE('PF', PF_SEQ.NEXTVAL), 'L000005');


-- PACKAGE(패키지, P)
CREATE SEQUENCE P_SEQ
NOCACHE;

INSERT INTO PACKAGE(PACKAGE_CODE, PACKAGE_FORM_CODE, PACKAGE_NAME
                  , PACKAGE_START, PACKAGE_END, PACKAGE_PRICE)
VALUES(F_CODE('P', P_SEQ.NEXTVAL), 'PF000001', '지옥', 18, 24, 50000);

INSERT INTO PACKAGE(PACKAGE_CODE, PACKAGE_FORM_CODE, PACKAGE_NAME
                  , PACKAGE_START, PACKAGE_END, PACKAGE_PRICE)
VALUES(F_CODE('P', P_SEQ.NEXTVAL), 'PF000001', '극락', 21, 34, 100000);

INSERT INTO PACKAGE(PACKAGE_CODE, PACKAGE_FORM_CODE, PACKAGE_NAME
                  , PACKAGE_START, PACKAGE_END, PACKAGE_PRICE)
VALUES(F_CODE('P', P_SEQ.NEXTVAL), 'PF000001', '중립', 10, 18, 150000);

INSERT INTO PACKAGE(PACKAGE_CODE, PACKAGE_FORM_CODE, PACKAGE_NAME
                  , PACKAGE_START, PACKAGE_END, PACKAGE_PRICE)
VALUES(F_CODE('P', P_SEQ.NEXTVAL), 'PF000002', '안졸림?', 1, 12, 200000);

INSERT INTO PACKAGE(PACKAGE_CODE, PACKAGE_FORM_CODE, PACKAGE_NAME
                  , PACKAGE_START, PACKAGE_END, PACKAGE_PRICE)
VALUES(F_CODE('P', P_SEQ.NEXTVAL), 'PF000003', '아침형인간', 6, 15, 250000);

INSERT INTO PACKAGE(PACKAGE_CODE, PACKAGE_FORM_CODE, PACKAGE_NAME
                  , PACKAGE_START, PACKAGE_END, PACKAGE_PRICE)
VALUES(F_CODE('P', P_SEQ.NEXTVAL), 'PF000004', '노는게죠아', 12, 20, 80000);

INSERT INTO PACKAGE(PACKAGE_CODE, PACKAGE_FORM_CODE, PACKAGE_NAME
                  , PACKAGE_START, PACKAGE_END, PACKAGE_PRICE)
VALUES(F_CODE('P', P_SEQ.NEXTVAL), 'PF000005', '막간', 20, 24, 90000);


-- APPLY_PACKAGE(적용된 패키지, AP)
CREATE SEQUENCE AP_SEQ
NOCACHE;

INSERT INTO APPLY_PACKAGE(APPLY_PACKAGE_CODE, PACKAGE_CODE, APPLY_DATE)
VALUES(F_CODE('AP', AP_SEQ.NEXTVAL), 'P000002', TO_DATE('2021-01-02', 'YYYY-MM-DD'));

INSERT INTO APPLY_PACKAGE(APPLY_PACKAGE_CODE, PACKAGE_CODE, APPLY_DATE)
VALUES(F_CODE('AP', AP_SEQ.NEXTVAL), 'P000003', TO_DATE('2021-01-02', 'YYYY-MM-DD'));

INSERT INTO APPLY_PACKAGE(APPLY_PACKAGE_CODE, PACKAGE_CODE, APPLY_DATE)
VALUES(F_CODE('AP', AP_SEQ.NEXTVAL), 'P000005', TO_DATE('2021-02-16', 'YYYY-MM-DD'));


-- PACKAGE_REMOVE(폐기 패키지, PRM)
--■ 폐기 패키지로 등록되는 트리거시점 고려 필요
CREATE SEQUENCE PRM_SEQ
NOCACHE;

/*
INSERT INTO PACKAGE_REMOVE(PACKAGE_REMOVE_CODE, PACKAGE_CODE, PACKAGE_REMOVE_DATE)
VALUES(F_CODE('PRM', PRM_SEQ.NEXTVAL), 'P000001', '지우는 날짜(마지막으로 패키지가 적용된 날짜)');
*/

-- LOC_BLIND(블라인드내역(공간게시물), LB) 
CREATE SEQUENCE LB_SEQ
NOCACHE;

INSERT INTO LOC_BLIND(LOC_BLIND_CODE, LOC_CODE, LOC_BLIND_REASON, LOC_BLIND_DATE)
VALUES(F_CODE('LB', LB_SEQ.NEXTVAL), 'L000003', '허위매물', SYSDATE);


-- LOC_WEB(공간웹사이트(상세정보), LW) 
CREATE SEQUENCE LW_SEQ
NOCACHE;

INSERT INTO LOC_WEB(LOC_WEB_CODE, LOC_DETAIL_INFO_CODE, LOC_WEB_URL)
VALUES(F_CODE('LW', LW_SEQ.NEXTVAL), 'LDIF000001', 'http://www.xxlarge.com');

INSERT INTO LOC_WEB(LOC_WEB_CODE, LOC_DETAIL_INFO_CODE, LOC_WEB_URL)
VALUES(F_CODE('LW', LW_SEQ.NEXTVAL), 'LDIF000002', 'http://ggomggom.com');

INSERT INTO LOC_WEB(LOC_WEB_CODE, LOC_DETAIL_INFO_CODE, LOC_WEB_URL)
VALUES(F_CODE('LW', LW_SEQ.NEXTVAL), 'LDIF000004', 'http://birthday-party.kr');


-- LOC_REMOVE(삭제내역(공간), LRM)
CREATE SEQUENCE LRM_SEQ
NOCACHE;

INSERT INTO LOC_REMOVE(LOC_REMOVE_CODE, LOC_CODE, LOC_REMOVE_DATE)
VALUES(F_CODE('LRM', LRM_SEQ.NEXTVAL), 'L000005', SYSDATE);


--============================================================= 5. BOOK

-- BOOK_LIST(예약내역, BC) 
CREATE SEQUENCE BC_SEQ 
NOCACHE;

INSERT INTO BOOK_LIST(BOOK_CODE, MEMBER_CODE, APPLY_PACKAGE_CODE, BOOK_PEOPLE
                    , BOOK_DATE, BOOK_REQ)
VALUES(F_CODE('BC', BC_SEQ.NEXTVAL), 'M000005', 'AP000001', 6
     , TO_DATE('2020-12-11 18:18:18', 'YYYY-MM-DD HH24:MI:SS'), '없음');

INSERT INTO BOOK_LIST(BOOK_CODE, MEMBER_CODE, APPLY_PACKAGE_CODE, BOOK_PEOPLE
                    , BOOK_DATE, BOOK_REQ)
VALUES(F_CODE('BC', BC_SEQ.NEXTVAL), 'M000001', 'AP000002', 4
     , TO_DATE('2020-12-30 19:05:18', 'YYYY-MM-DD HH24:MI:SS'), '에어컨 잘 되나요?');

INSERT INTO BOOK_LIST(BOOK_CODE, MEMBER_CODE, APPLY_PACKAGE_CODE, BOOK_PEOPLE
                    , BOOK_DATE, BOOK_REQ)
VALUES(F_CODE('BC', BC_SEQ.NEXTVAL), 'M000002', 'AP000003', 3
     , TO_DATE('2021-02-01 07:05:29', 'YYYY-MM-DD HH24:MI:SS'), '배달음식 시켜먹어도 되나요?');


-- HOST_CANCEL_LIST(예약취소내역(호스트), HC)
CREATE SEQUENCE HC_SEQ
NOCACHE;

INSERT INTO HOST_CANCEL_LIST(HOST_CANCEL_CODE, BOOK_CODE
                           , HOST_CANCEL_REASON, HOST_CANCEL_DATE)
VALUES(F_CODE('HC', HC_SEQ.NEXTVAL), 'BC000001', '그냥', TO_DATE('2020-12-15')); 


-- BOOK_REFUND_LIST(예약환불내역(이용자))
CREATE SEQUENCE BRF_SEQ
NOCACHE;

INSERT INTO BOOK_REFUND_LIST(BOOK_REFUND_CODE, BOOK_CODE, BOOK_REFUND_DATE)
VALUES(F_CODE('BRF', BRF_SEQ.NEXTVAL), 'BC000003', TO_DATE('2021-02-10', 'YYYY-MM-DD'));


--BOOK_PAY_LIST(예약 결제 내역(이용자), BP)
CREATE SEQUENCE BP_SEQ
NOCACHE;

INSERT INTO BOOK_PAY_LIST (BOOK_PAY_CODE, BOOK_CODE, BOOK_PAY_DATE) 
VALUES (F_CODE('BP', BP_SEQ.NEXTVAL), 'BC000001',TO_DATE('2020-12-11 18:18:18', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO BOOK_PAY_LIST (BOOK_PAY_CODE, BOOK_CODE, BOOK_PAY_DATE) 
VALUES (F_CODE('BP', BP_SEQ.NEXTVAL), 'BC000002', TO_DATE('2020-12-30 19:05:18', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO BOOK_PAY_LIST (BOOK_PAY_CODE, BOOK_CODE, BOOK_PAY_DATE) 
VALUES (F_CODE('BP', BP_SEQ.NEXTVAL), 'BC000003', TO_DATE('2021-02-01 07:05:29', 'YYYY-MM-DD HH24:MI:SS'));


-- ACTUAL_BOOKER(실예약자, AB)
CREATE SEQUENCE AB_SEQ
NOCACHE;

INSERT INTO ACTUAL_BOOKER(ACTUAL_BOOKER_CODE, BOOK_CODE
                , ACTUAL_BOOKER, ACTUAL_BOOKER_TEL)
VALUES(F_CODE('AB', AB_SEQ.NEXTVAL), 'BC000001', '이구아나', '010-2351-4564');
INSERT INTO ACTUAL_BOOKER(ACTUAL_BOOKER_CODE, BOOK_CODE
                , ACTUAL_BOOKER, ACTUAL_BOOKER_TEL)
VALUES(F_CODE('AB', AB_SEQ.NEXTVAL), 'BC000002', '이구아나', '010-2351-4564');
INSERT INTO ACTUAL_BOOKER(ACTUAL_BOOKER_CODE, BOOK_CODE
                , ACTUAL_BOOKER, ACTUAL_BOOKER_TEL)
VALUES(F_CODE('AB', AB_SEQ.NEXTVAL), 'BC000003', '다람쥐', '010-7777-7878');
         
         
-- MEMBER_CANCEL_LIST(예약취소내역(이용자), MC)
CREATE SEQUENCE MC_SEQ
NOCACHE;

INSERT INTO MEMBER_CANCEL_LIST(MEMBER_CANCEL_CODE, BOOK_CODE
                            , MEMBER_CANCEL_REASON, MEMBER_CANCEL_DATE)
VALUES(F_CODE('MC', MC_SEQ.NEXTVAL),'BC000003', '가기싫어졌어요', TO_DATE('2021-02-10','YYYY-MM-DD'));


--=========================================================== 6. INSPECT 

-- INSPECT_TYPE(검수분류, IT)
CREATE SEQUENCE IT_SEQ
NOCACHE;

INSERT INTO INSPECT_TYPE(INSPECT_TYPE_CODE, INSPECT_TYPE)
VALUES(F_CODE('IT', IT_SEQ.NEXTVAL), '검수승인');

INSERT INTO INSPECT_TYPE(INSPECT_TYPE_CODE, INSPECT_TYPE)
VALUES(F_CODE('IT', IT_SEQ.NEXTVAL), '검수반려');


-- INSPECT_REG_LIST(검수신청내역, IR)
CREATE SEQUENCE IR_SEQ
NOCACHE;

INSERT INTO INSPECT_REG_LIST(INSPECT_REG_CODE, LOC_CODE, INSPECT_REG_DATE)
VALUES(F_CODE('IR', IR_SEQ.NEXTVAL), 'L000001', TO_DATE('2020-01-21', 'YYYY-MM-DD'));

INSERT INTO INSPECT_REG_LIST(INSPECT_REG_CODE, LOC_CODE, INSPECT_REG_DATE)
VALUES(F_CODE('IR', IR_SEQ.NEXTVAL), 'L000002', TO_DATE('2020-04-23', 'YYYY-MM-DD'));

INSERT INTO INSPECT_REG_LIST(INSPECT_REG_CODE, LOC_CODE, INSPECT_REG_DATE)
VALUES(F_CODE('IR', IR_SEQ.NEXTVAL), 'L000003', TO_DATE('2020-04-29', 'YYYY-MM-DD'));

INSERT INTO INSPECT_REG_LIST(INSPECT_REG_CODE, LOC_CODE, INSPECT_REG_DATE)
VALUES(F_CODE('IR', IR_SEQ.NEXTVAL), 'L000004', TO_DATE('2020-06-30', 'YYYY-MM-DD'));

INSERT INTO INSPECT_REG_LIST(INSPECT_REG_CODE, LOC_CODE, INSPECT_REG_DATE)
VALUES(F_CODE('IR', IR_SEQ.NEXTVAL), 'L000005', TO_DATE('2020-08-01', 'YYYY-MM-DD'));


-- INSPECT_PROC_LIST(검수처리내역, IP)
CREATE SEQUENCE IP_SEQ
NOCACHE;

INSERT INTO INSPECT_PROC_LIST(INSPECT_PROC_CODE, INSPECT_REG_CODE
                    , INSPECT_TYPE_CODE, INSPECT_PROC_REASON, INSPECT_PROC_DATE)
VALUES(F_CODE('IP', IP_SEQ.NEXTVAL), 'IR000001'
         , 'IT000001', '검수 승인을 축하합니다!'
         , TO_DATE('2020-02-01', 'YYYY-MM-DD'));

INSERT INTO INSPECT_PROC_LIST(INSPECT_PROC_CODE, INSPECT_REG_CODE
                    , INSPECT_TYPE_CODE, INSPECT_PROC_REASON, INSPECT_PROC_DATE)
VALUES(F_CODE('IP', IP_SEQ.NEXTVAL), 'IR000002'
         , 'IT000001', '검수 승인을 축하합니다!'
         , TO_DATE('2020-04-25', 'YYYY-MM-DD'));

INSERT INTO INSPECT_PROC_LIST(INSPECT_PROC_CODE, INSPECT_REG_CODE
                    , INSPECT_TYPE_CODE, INSPECT_PROC_REASON, INSPECT_PROC_DATE)
VALUES(F_CODE('IP', IP_SEQ.NEXTVAL), 'IR000003'
         , 'IT000001', '검수 승인을 축하합니다!'
         , TO_DATE('2020-05-06', 'YYYY-MM-DD'));

INSERT INTO INSPECT_PROC_LIST(INSPECT_PROC_CODE, INSPECT_REG_CODE
                    , INSPECT_TYPE_CODE, INSPECT_PROC_REASON, INSPECT_PROC_DATE)
VALUES(F_CODE('IP', IP_SEQ.NEXTVAL), 'IR000004'
         , 'IT000002', '테스트 계정은 검수가 반려됩니다.'
         , TO_DATE('2020-08-06', 'YYYY-MM-DD'));


--=========================================================== 7. MILEAGE
     
     
-- LOAD_TYPE(마일리지 충전 분류, LT)
INSERT INTO LOAD_TYPE(LOAD_TYPE_CODE, LOAD_TYPE)
VALUES(F_CODE('LT', 1), '충전성공');

INSERT INTO LOAD_TYPE(LOAD_TYPE_CODE, LOAD_TYPE)
VALUES(F_CODE('LT', 2), '충전실패');

     
-- LOAD_REG(마일리지 충전신청 내역(이용자), LR)
CREATE SEQUENCE LR_SEQ
NOCACHE;

INSERT INTO LOAD_REG(LOAD_REG_CODE, MEMBER_CODE, LOAD_AMOUNT
                   , LOAD_REG_DATE)
VALUES(F_CODE('LR', LR_SEQ.NEXTVAL), 'M000001', 170000
     , TO_DATE('2020-11-01', 'YYYY-MM-DD'));
INSERT INTO LOAD_REG(LOAD_REG_CODE, MEMBER_CODE, LOAD_AMOUNT
                   , LOAD_REG_DATE)
VALUES(F_CODE('LR', LR_SEQ.NEXTVAL), 'M000001', 150000
     , TO_DATE('2020-11-21', 'YYYY-MM-DD'));
INSERT INTO LOAD_REG(LOAD_REG_CODE, MEMBER_CODE, LOAD_AMOUNT
                   , LOAD_REG_DATE)
VALUES(F_CODE('LR', LR_SEQ.NEXTVAL), 'M000001', 130000
     , TO_DATE('2020-12-04', 'YYYY-MM-DD'));
INSERT INTO LOAD_REG(LOAD_REG_CODE, MEMBER_CODE, LOAD_AMOUNT
                   , LOAD_REG_DATE)
VALUES(F_CODE('LR', LR_SEQ.NEXTVAL), 'M000002', 200000
     , TO_DATE('2020-12-15', 'YYYY-MM-DD'));
INSERT INTO LOAD_REG(LOAD_REG_CODE, MEMBER_CODE, LOAD_AMOUNT
                   , LOAD_REG_DATE)
VALUES(F_CODE('LR', LR_SEQ.NEXTVAL), 'M000003', 250000
     , TO_DATE('2020-12-20', 'YYYY-MM-DD'));
INSERT INTO LOAD_REG(LOAD_REG_CODE, MEMBER_CODE, LOAD_AMOUNT
                   , LOAD_REG_DATE)
VALUES(F_CODE('LR', LR_SEQ.NEXTVAL), 'M000001', 210000
     , TO_DATE('2020-12-31', 'YYYY-MM-DD'));
     
     
-- LOAD_REG_BANK_INFO(충전신청계좌정보 LRBIF)
CREATE SEQUENCE LRBIF_SEQ
NOCACHE;

INSERT INTO LOAD_REG_BANK_INFO(LOAD_REG_BANK_INFO_CODE, LOAD_REG_CODE
                              , MEMBER_BANK_NUMBER)
VALUES(F_CODE('LRBI', LRBIF_SEQ.NEXTVAL), 'LR000001', '110-343-936673'); 
INSERT INTO LOAD_REG_BANK_INFO(LOAD_REG_BANK_INFO_CODE, LOAD_REG_CODE
                              , MEMBER_BANK_NUMBER)
VALUES(F_CODE('LRBI', LRBIF_SEQ.NEXTVAL), 'LR000002', '110-343-936673'); 
INSERT INTO LOAD_REG_BANK_INFO(LOAD_REG_BANK_INFO_CODE, LOAD_REG_CODE
                              , MEMBER_BANK_NUMBER)
VALUES(F_CODE('LRBI', LRBIF_SEQ.NEXTVAL), 'LR000003', '110-343-936673');
INSERT INTO LOAD_REG_BANK_INFO(LOAD_REG_BANK_INFO_CODE, LOAD_REG_CODE
                              , MEMBER_BANK_NUMBER)
VALUES(F_CODE('LRBI', LRBIF_SEQ.NEXTVAL), 'LR000004', '554602-04-076182');
INSERT INTO LOAD_REG_BANK_INFO(LOAD_REG_BANK_INFO_CODE, LOAD_REG_CODE
                              , MEMBER_BANK_NUMBER)
VALUES(F_CODE('LRBI', LRBIF_SEQ.NEXTVAL), 'LR000005', '545777-48488-76182');
INSERT INTO LOAD_REG_BANK_INFO(LOAD_REG_BANK_INFO_CODE, LOAD_REG_CODE
                              , MEMBER_BANK_NUMBER)
VALUES(F_CODE('LRBI', LRBIF_SEQ.NEXTVAL), 'LR000006', '1002-048-273134');

     
-- LOAD_PROC(충전처리내역(이용자), LP)
CREATE SEQUENCE LP_SEQ
NOCACHE;

INSERT INTO LOAD_PROC(LOAD_PROC_CODE, LOAD_REG_CODE
                    , LOAD_TYPE_CODE, LOAD_PROC_DATE)
VALUES(F_CODE('LP', LP_SEQ.NEXTVAL), 'LR000001'
     , 'LT000002', TO_DATE('2020-11-02', 'YYYY-MM-DD'));
INSERT INTO LOAD_PROC(LOAD_PROC_CODE, LOAD_REG_CODE
                    , LOAD_TYPE_CODE, LOAD_PROC_DATE)
VALUES(F_CODE('LP', LP_SEQ.NEXTVAL), 'LR000002'
     , 'LT000001', TO_DATE('2020-11-22', 'YYYY-MM-DD'));
INSERT INTO LOAD_PROC(LOAD_PROC_CODE, LOAD_REG_CODE
                    , LOAD_TYPE_CODE, LOAD_PROC_DATE)
VALUES(F_CODE('LP', LP_SEQ.NEXTVAL), 'LR000003'
     , 'LT000001', TO_DATE('2020-12-05', 'YYYY-MM-DD'));
INSERT INTO LOAD_PROC(LOAD_PROC_CODE, LOAD_REG_CODE
                    , LOAD_TYPE_CODE, LOAD_PROC_DATE)
VALUES(F_CODE('LP', LP_SEQ.NEXTVAL), 'LR000004'
     , 'LT000002', TO_DATE('2020-12-16', 'YYYY-MM-DD'));
INSERT INTO LOAD_PROC(LOAD_PROC_CODE, LOAD_REG_CODE
                    , LOAD_TYPE_CODE, LOAD_PROC_DATE)
VALUES(F_CODE('LP', LP_SEQ.NEXTVAL), 'LR000005'
     , 'LT000001', TO_DATE('2020-12-21', 'YYYY-MM-DD'));


-- MEMBER_EXCHANGE_LIST(마일리지 환전 내역(이용자), ME)
CREATE SEQUENCE ME_SEQ
NOCACHE;

INSERT INTO MEMBER_EXCHANGE_LIST(MEMBER_EXCHANGE_CODE, MEMBER_CODE
                              , MEMBER_EXCHANGE_AMOUNT, MEMBER_EXCHANGE_DATE)
VALUES(F_CODE('ME', ME_SEQ.NEXTVAL), 'M000001'
    , 20000, TO_DATE('2021-01-08', 'YYYY-MM-DD'));

INSERT INTO MEMBER_EXCHANGE_LIST(MEMBER_EXCHANGE_CODE, MEMBER_CODE
                              , MEMBER_EXCHANGE_AMOUNT, MEMBER_EXCHANGE_DATE)
VALUES(F_CODE('ME', ME_SEQ.NEXTVAL), 'M000002'
    , 25000, TO_DATE('2021-01-09', 'YYYY-MM-DD'));

INSERT INTO MEMBER_EXCHANGE_LIST(MEMBER_EXCHANGE_CODE, MEMBER_CODE
                              , MEMBER_EXCHANGE_AMOUNT, MEMBER_EXCHANGE_DATE)
VALUES(F_CODE('ME', ME_SEQ.NEXTVAL), 'M000003'
    , 30000, TO_DATE('2021-01-09', 'YYYY-MM-DD'));

INSERT INTO MEMBER_EXCHANGE_LIST(MEMBER_EXCHANGE_CODE, MEMBER_CODE
                              , MEMBER_EXCHANGE_AMOUNT, MEMBER_EXCHANGE_DATE)
VALUES(F_CODE('ME', ME_SEQ.NEXTVAL), 'M000001'
    , 10000, TO_DATE('2021-01-11', 'YYYY-MM-DD'));


--MEMBER_EXCHANGE_BANK_INFO(환전계좌정보(이용자), MEBIF)
CREATE SEQUENCE MEBIF_SEQ
NOCACHE;

INSERT INTO MEMBER_EXCHANGE_BANK_INFO (MEMBER_EXCHANGE_BANK_INFO_CODE, MEMBER_EXCHANGE_CODE, MEMBER_BANK_NUMBER) 
VALUES (F_CODE('MEBIF', MEBIF_SEQ.NEXTVAL), 'ME000001', '110-343-936673');

INSERT INTO MEMBER_EXCHANGE_BANK_INFO (MEMBER_EXCHANGE_BANK_INFO_CODE, MEMBER_EXCHANGE_CODE, MEMBER_BANK_NUMBER) 
VALUES (F_CODE('MEBIF', MEBIF_SEQ.NEXTVAL), 'ME000002', '554602-04-076182');

INSERT INTO MEMBER_EXCHANGE_BANK_INFO (MEMBER_EXCHANGE_BANK_INFO_CODE, MEMBER_EXCHANGE_CODE, MEMBER_BANK_NUMBER) 
VALUES (F_CODE('MEBIF', MEBIF_SEQ.NEXTVAL), 'ME000003', '545777-48488-76182');

INSERT INTO MEMBER_EXCHANGE_BANK_INFO (MEMBER_EXCHANGE_BANK_INFO_CODE, MEMBER_EXCHANGE_CODE, MEMBER_BANK_NUMBER) 
VALUES (F_CODE('MEBIF', MEBIF_SEQ.NEXTVAL), 'ME000004', '1002-048-273134');


-- CAL(정산내역, C)
CREATE SEQUENCE C_SEQ
NOCACHE;

INSERT INTO CAL(CAL_CODE, BOOK_CODE, HOST_CODE, CAL_DATE)
VALUES(F_CODE('C', C_SEQ.NEXTVAL), 'BC000002', 'H000001'
     , TO_DATE('2021-05-05', 'YYYY-MM-DD'));
     
     
-- HOST_EXCHANGE_LIST(마일리지 환전 내역(호스트), HE)
CREATE SEQUENCE HE_SEQ
NOCACHE;

INSERT INTO HOST_EXCHANGE_LIST(HOST_EXCHANGE_CODE, HOST_CODE
                             , HOST_EXCHANGE_AMOUNT, HOST_EXCHANGE_DATE)
VALUES(F_CODE('HE', HE_SEQ.NEXTVAL), 'H000001'
     , 150000, TO_DATE('2021-05-06', 'YYYY-MM-DD'));


--HOST_EXCHANGE_BANK_INFO(환전계좌정보(호스트), HEBIF)
CREATE SEQUENCE HEBIF_SEQ
NOCACHE;

INSERT INTO HOST_EXCHANGE_BANK_INFO (HOST_EXCHANGE_BANK_INFO_CODE, HOST_EXCHANGE_CODE, HOST_BANK_NUMBER)
VALUES (F_CODE('HEBIF',HEBIF_SEQ.NEXTVAL), 'HE000001', '601245-02-201535');

     
--=========================================================== 8. CONTENTS

-- QNA(QNA(이용자), Q)
CREATE SEQUENCE Q_SEQ
NOCACHE;

INSERT INTO QNA (QNA_CODE, LOC_CODE, MEMBER_CODE, QNA_CONTENT, QNA_DATE)
VALUES (F_CODE('Q', Q_SEQ.NEXTVAL), 'L000001', 'M000001', 
            '여기 뜨거운 물나오나요?', TO_DATE('2020-12-26','YYYY-MM-DD'));

INSERT INTO QNA (QNA_CODE, LOC_CODE, MEMBER_CODE, QNA_CONTENT, QNA_DATE)
VALUES (F_CODE('Q',Q_SEQ.NEXTVAL), 'L000001', 'M000002', 
            '주차장 있나요?', TO_DATE('2020-12-27','YYYY-MM-DD'));
            
INSERT INTO QNA (QNA_CODE, LOC_CODE, MEMBER_CODE, QNA_CONTENT, QNA_DATE)
VALUES (F_CODE('Q', Q_SEQ.NEXTVAL), 'L000001', 'M000003', 
            '자판기 있나요?', TO_DATE('2020-12-28','YYYY-MM-DD'));

INSERT INTO QNA (QNA_CODE, LOC_CODE, MEMBER_CODE, QNA_CONTENT, QNA_DATE)
VALUES (F_CODE('Q', Q_SEQ.NEXTVAL), 'L000001', 'M000004', 
            '숟가락 있나요?', TO_DATE('2020-12-28','YYYY-MM-DD'));

INSERT INTO QNA (QNA_CODE, LOC_CODE, MEMBER_CODE, QNA_CONTENT, QNA_DATE)
VALUES (F_CODE('Q', Q_SEQ.NEXTVAL), 'L000002', 'M000005', 
            '젓가락 있나요?', TO_DATE('2020-12-26','YYYY-MM-DD'));
            
INSERT INTO QNA (QNA_CODE, LOC_CODE, MEMBER_CODE, QNA_CONTENT, QNA_DATE)
VALUES (F_CODE('Q', Q_SEQ.NEXTVAL), 'L000002', 'M000001'
        , '근처에 편의점 있나요?', TO_DATE('2020-12-27','YYYY-MM-DD'));
        
        
-- QNA_REMOVE(삭제내역(Q&A), QRM)
CREATE SEQUENCE QRM_SEQ
NOCACHE;

INSERT INTO QNA_REMOVE (QNA_REMOVE_CODE, QNA_CODE, QNA_REMOVE_DATE) 
VALUES (F_CODE('QRM', QRM_SEQ.NEXTVAL), 'Q000002', TO_DATE('2020-12-28','YYYY-MM-DD'));

INSERT INTO QNA_REMOVE (QNA_REMOVE_CODE, QNA_CODE, QNA_REMOVE_DATE) 
VALUES (F_CODE('QRM', QRM_SEQ.NEXTVAL), 'Q000006', TO_DATE('2020-12-28','YYYY-MM-DD'));


-- QNA_REPLY(Q&A답글(호스트), QRE)
CREATE SEQUENCE QRE_SEQ
NOCACHE;

INSERT INTO QNA_REPLY (QNA_REPLY_CODE, QNA_CODE, QNA_REPLY_CONTENT, QNA_REPLY_DATE)
VALUES (F_CODE('QRE', QRE_SEQ.NEXTVAL), 'Q000001', '네 뜨거운물 나옵니다.', TO_DATE('2020-12-27','YYYY-MM-DD'));            

INSERT INTO QNA_REPLY (QNA_REPLY_CODE, QNA_CODE, QNA_REPLY_CONTENT, QNA_REPLY_DATE)
VALUES (F_CODE('QRE', QRE_SEQ.NEXTVAL), 'Q000002', '네 주차장 있읍니다.', TO_DATE('2020-12-27','YYYY-MM-DD'));


-- QNA_REPLY_REMOVE(삭제내역(Q&A답글), QRERM)
CREATE SEQUENCE QRERM_SEQ
NOCACHE;

INSERT INTO QNA_REPLY_REMOVE (QNA_REPLY_REMOVE_CODE, QNA_REPLY_CODE, QNA_REPLY_REMOVE_DATE)
VALUES (F_CODE('QRERM', QRERM_SEQ.NEXTVAL), 'QRE000001', TO_DATE('2020-12-28','YYYY-MM-DD'));


-- REVIEW(리뷰(이용자), RV)
CREATE SEQUENCE RV_SEQ
NOCACHE;

INSERT INTO REVIEW(REVIEW_CODE, LOC_CODE, MEMBER_CODE, REVIEW_RATE
                 , REVIEW_CONTENT, REVIEW_DATE)
VALUES(F_CODE('RV', RV_SEQ.NEXTVAL), 'L000001', 'M000005', 2
    , '어승승일산 솔직후기.', TO_DATE('2021-01-03', 'YYYY-MM-DD'));
    
    
-- REVIEW_IMG(이미지(리뷰), RVIMG)
CREATE SEQUENCE RVIMG_SEQ
NOCACHE;

INSERT INTO REVIEW_IMG(REVIEW_IMG_CODE, REVIEW_CODE, REVIEW_IMG_URL)
VALUES(F_CODE('RVIMG', RVIMG_SEQ.NEXTVAL), 'RV000001', '/images/tokki_01.png');


-- REVIEW_REMOVE(삭제내역(리뷰), RVRM)
CREATE SEQUENCE RVRM_SEQ
NOCACHE;

INSERT INTO REVIEW_REMOVE(REVIEW_REMOVE_CODE, REVIEW_CODE, REVIEW_REMOVE_DATE)
VALUES(F_CODE('RVRM', RVRM_SEQ.NEXTVAL), 'RV000001', SYSDATE);


-- REVIEW_REPLY(리뷰답글(호스트), RVRE)
CREATE SEQUENCE RVRE_SEQ
NOCACHE;

INSERT INTO REVIEW_REPLY(REVIEW_REPLY_CODE, REVIEW_CODE, REVIEW_REPLY_CONTENT
          , REVIEW_REPLY_DATE)
VALUES(F_CODE('RVRE', RVRE_SEQ.NEXTVAL), 'RV000001', '와주셔서 감사합니다.'
     , TO_DATE('2021-01-04', 'YYYY-MM-DD'));
     
     
-- REVIEW_REPLY_REMOVE(삭제내역(리뷰답글), RVRERM)
CREATE SEQUENCE RVRERM_SEQ
NOCACHE;

-- 한개뿐인 리뷰 지워서 답글은 삭제 안함


--=========================================================== 9. REPORT

-- REPORT_PROC_TYPE(신고처리분류 RPPT)

INSERT INTO REPORT_PROC_TYPE(REPORT_PROC_TYPE_CODE, REPORT_PROC_TYPE)
VALUES('RPPT000001', '신고인정');

INSERT INTO REPORT_PROC_TYPE(REPORT_PROC_TYPE_CODE, REPORT_PROC_TYPE)
VALUES('RPPT000002', '신고반려');


-- BOOK_REPORT_TYPE(신고유형분류(예약내역), BRPT)

INSERT INTO BOOK_REPORT_TYPE(BOOK_REPORT_TYPE_CODE, BOOK_REPORT_TYPE)
VALUES('BRPT000001', '부적절한언행');

INSERT INTO BOOK_REPORT_TYPE(BOOK_REPORT_TYPE_CODE, BOOK_REPORT_TYPE)
VALUES('BRPT000002', '기물파손');

INSERT INTO BOOK_REPORT_TYPE(BOOK_REPORT_TYPE_CODE, BOOK_REPORT_TYPE)
VALUES('BRPT000003', '이용규정위반');

INSERT INTO BOOK_REPORT_TYPE(BOOK_REPORT_TYPE_CODE, BOOK_REPORT_TYPE)
VALUES('BRPT000004', '기타');


-- LOC_REPORT_TYPE(신고처리(이용자)(공간), LRPP)

INSERT INTO LOC_REPORT_TYPE(LOC_REPORT_TYPE_CODE, LOC_REPORT_TYPE)
VALUES('LRPP000001', '서비스미충족');

INSERT INTO LOC_REPORT_TYPE(LOC_REPORT_TYPE_CODE, LOC_REPORT_TYPE)
VALUES('LRPP000002', '추가결제 유도');

INSERT INTO LOC_REPORT_TYPE(LOC_REPORT_TYPE_CODE, LOC_REPORT_TYPE)
VALUES('LRPP000003', '공유규정위반');

INSERT INTO LOC_REPORT_TYPE(LOC_REPORT_TYPE_CODE, LOC_REPORT_TYPE)
VALUES('LRPP000004', '허위매물');

INSERT INTO LOC_REPORT_TYPE(LOC_REPORT_TYPE_CODE, LOC_REPORT_TYPE)
VALUES('LRPP000005', '기타');

-- BOOK_REPORT(신고접수(이용자)(예약), BRP)
CREATE SEQUENCE BRP_SEQ
NOCACHE;

INSERT INTO BOOK_REPORT(BOOK_REPORT_CODE, BOOK_CODE
                                   , BOOK_REPORT_TYPE_CODE, HOST_CODE
                                   , BOOK_REPORT_REASON, BOOK_REPORT_DATE)
VALUES(F_CODE('BRP', BRP_SEQ.NEXTVAL), 'BC000002'
         , 'BRPT000001', 'H000001'
         , '부적절한언행', TO_DATE('2021-01-20', 'YYYY-MM-DD'));
         
         
-- BOOK_REPORT_IMG(이미지(신고), BRPIMG)
CREATE SEQUENCE BRPIMG_SEQ
NOCACHE;

INSERT INTO BOOK_REPORT_IMG(BOOK_REPORT_IMG_CODE, BOOK_REPORT_CODE
                                        , BOOK_REPORT_IMG_URL)
VALUES(F_CODE('BRPIMG', BRPIMG_SEQ.NEXTVAL), 'BRP000001'
        , '신고내용캡쳐1.jpg');
        
        
-- BOOK_REPORT_PROC(신고처리(이용자)(예약), BRPP)
CREATE SEQUENCE BRPP_SEQ
NOCACHE;

INSERT INTO BOOK_REPORT_PROC(BOOK_REPORT_PROC_CODE, BOOK_REPORT_CODE
                                          , REPORT_PROC_TYPE_CODE, BOOK_REPORT_PROC_DATE)
VALUES(F_CODE('BRPP', BRPP_SEQ.NEXTVAL), 'BRP000001'
         , 'RPPT000001', TO_DATE('2020-09-16', 'YYYY-MM-DD'));
        
        
-- LOC_REPORT(신고접수(이용자)(공간), LRP)
CREATE SEQUENCE LRP_SEQ
NOCACHE;

INSERT INTO LOC_REPORT(LOC_REPORT_CODE, LOC_CODE, LOC_REPORT_TYPE_CODE
                                 , MEMBER_CODE, LOC_REPORT_REASON, LOC_REPORT_DATE)
VALUES(F_CODE('LRP', LRP_SEQ.NEXTVAL), 'L000001', 'LRPP000001'
         , 'M000001', '서비스를 심각하게 충족하지 못하였습니다.'
         , TO_DATE('2020-12-23', 'YYYY-MM-DD'));
        
        
-- LOC_REPORT_IMG(이미지(신고), LRPIMG)
CREATE SEQUENCE LRPIMG
NOCACHE;

INSERT INTO LOC_REPORT_IMG(LOC_REPORT_IMG_CODE, LOC_REPORT_CODE
                                       , LOC_REPORT_IMG_URL)
VALUES(F_CODE('LRPIMG', LRPIMG.NEXTVAL), 'LRP000001'
         , '캡쳐본1.PNG');    
         
         
-- LOC_REPORT_PROC(신고처리(이용자)(공간), LRPP)
CREATE SEQUENCE LRPP_SEQ
NOCACHE;

INSERT INTO LOC_REPORT_PROC(LOC_REPORT_PROC_CODE, LOC_REPORT_CODE
                                         , REPORT_PROC_TYPE_CODE, LOC_REPORT_PROC_DATE)
VALUES(F_CODE('LRPP', LRPP_SEQ.NEXTVAL), 'LRP000001'
         , 'RPPT000001', TO_DATE('2020-12-26', 'YYYY-MM-DD'));
         
         
--=========================================================== 10. MESSENGER
--MSG(메신저,M)
CREATE SEQUENCE MSG_SEQ
NOCACHE;

INSERT INTO MSG (MSG_CODE, BOOK_CODE) 
VALUES (F_CODE('MSG',MSG_SEQ.NEXTVAL), 'BC000001');

INSERT INTO MSG (MSG_CODE, BOOK_CODE) 
VALUES (F_CODE('MSG',MSG_SEQ.NEXTVAL), 'BC000002');

INSERT INTO MSG (MSG_CODE, BOOK_CODE) 
VALUES (F_CODE('MSG',MSG_SEQ.NEXTVAL), 'BC000003');


--MEMBER_MSG_INFO(메신저정보(이용자) MMIF)
CREATE SEQUENCE MMIF_SEQ
NOCACHE;

INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000001', '안녕안녕'
      , TO_DATE('2021-01-02 21:01:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000001', '거기좋은가여?' 
      , TO_DATE('2021-01-02 21:03:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000001', NULL
      , TO_DATE('2021-01-02 21:05:00', 'YYYY-MM-DD HH24:MI:SS'));
      
INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000001', '그럼이만'
      , TO_DATE('2021-01-02 21:07:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000002', '할로할로'
      , TO_DATE('2021-01-02 10:01:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000002', '아워너슬립'
      , TO_DATE('2021-01-02 10:03:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000002', '바이바이'
      , TO_DATE('2021-01-02 10:05:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000002', NULL
      , TO_DATE('2021-01-02 10:07:00', 'YYYY-MM-DD HH24:MI:SS'));
      
INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000003', NULL
      , TO_DATE('2021-02-16 06:01:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000003', '니하오니하오'
      , TO_DATE('2021-02-16 06:03:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000003', '워 헌 레이'
      , TO_DATE('2021-02-16 06:05:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO MEMBER_MSG_INFO (MEMBER_MSG_INFO_CODE
, MSG_CODE, MEMBER_MSG_CONTENT, MEMBER_MSG_DATE) 
VALUES (F_CODE('MMIF',MMIF_SEQ.NEXTVAL), 'MSG000003', '짜이찌엔짜이찌엔'
      , TO_DATE('2021-02-16 06:07:00', 'YYYY-MM-DD HH24:MI:SS'));
      

--MEMBER_MSG_IMG(이미지(메신저정보(이용자)) MMIMG)
CREATE SEQUENCE MMIMG_SEQ
NOCACHE;

INSERT INTO MEMBER_MSG_IMG (MEMBER_MSG_IMG_CODE
, MEMBER_MSG_INFO_CODE, MEMBER_MSG_IMG_URL) 
VALUES (F_CODE('MMIMG',MMIMG_SEQ.NEXTVAL), 'MMIF000003', '메신저이미지링크1');

INSERT INTO MEMBER_MSG_IMG (MEMBER_MSG_IMG_CODE
, MEMBER_MSG_INFO_CODE, MEMBER_MSG_IMG_URL) 
VALUES (F_CODE('MMIMG',MMIMG_SEQ.NEXTVAL), 'MMIF000008', '메신저이미지링크2');

INSERT INTO MEMBER_MSG_IMG (MEMBER_MSG_IMG_CODE
, MEMBER_MSG_INFO_CODE, MEMBER_MSG_IMG_URL) 
VALUES (F_CODE('MMIMG',MMIMG_SEQ.NEXTVAL), 'MMIF000009', '메신저이미지링크3');


--HOST_MSG_INFO(메신저정보(호스트) HMIF)
CREATE SEQUENCE HMIF_SEQ
NOCACHE;

INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000001', '본쥬르'
      ,TO_DATE('2021-01-02 21:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000001', '엑스꾸제므와'
      ,TO_DATE('2021-01-02 21:02:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000001', '오르브와르'
      ,TO_DATE('2021-01-02 21:04:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000001',NULL
      ,TO_DATE('2021-01-02 21:06:00', 'YYYY-MM-DD HH24:MI:SS'));
      
INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000002', '구텐모르겐'
      , TO_DATE('2021-01-02 10:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000002', '구텐탁'
      ,TO_DATE('2021-01-02 10:02:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000002', NULL
      ,TO_DATE('2021-01-02 10:04:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000002', '구텐아벤트'
      ,TO_DATE('2021-01-02 10:06:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000003', NULL
      , TO_DATE('2021-02-16 06:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000003', '올라'
      , TO_DATE('2021-02-16 06:02:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000003', '무이비엔'
      , TO_DATE('2021-02-16 06:04:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HOST_MSG_INFO (HOST_MSG_INFO_CODE
, MSG_CODE, HOST_MSG_CONTENT, HOST_MSG_DATE) 
VALUES (F_CODE('HMIF',HMIF_SEQ.NEXTVAL), 'MSG000003', '그라시아스'
      , TO_DATE('2021-02-16 06:06:00', 'YYYY-MM-DD HH24:MI:SS'));
      
      
--HOST_MSG_IMG(이미지(메신저정보(호스트)) HMIMG)
CREATE SEQUENCE HMIMG_SEQ
NOCACHE;

INSERT INTO HOST_MSG_IMG (HOST_MSG_IMG_CODE, HOST_MSG_INFO_CODE
, HOST_MSG_IMG_URL) 
VALUES (F_CODE('HMIMG',HMIMG_SEQ.NEXTVAL), 'HMIF000004', '메신저이미지링크홑1');

INSERT INTO HOST_MSG_IMG (HOST_MSG_IMG_CODE, HOST_MSG_INFO_CODE
, HOST_MSG_IMG_URL) 
VALUES (F_CODE('HMIMG',HMIMG_SEQ.NEXTVAL), 'HMIF000007', '메신저이미지링크홑2');

INSERT INTO HOST_MSG_IMG (HOST_MSG_IMG_CODE, HOST_MSG_INFO_CODE
, HOST_MSG_IMG_URL) 
VALUES (F_CODE('HMIMG',HMIMG_SEQ.NEXTVAL), 'HMIF000009', '메신저이미지링크홑3');


-- 커밋
--COMMIT;