
-- 코드 생성 함수
CREATE OR REPLACE FUNCTION F_CODE
( 
V_CODE IN VARCHAR2,
V_SEQ  IN NUMBER
)
RETURN VARCHAR2
IS
    V_RESULT VARCHAR2(15);
    V_DEFAULT VARCHAR2(15) := '000000';
    V_CHARSEQ VARCHAR2(15) := TO_CHAR(V_SEQ);
BEGIN
    V_RESULT := V_CODE 
            || SUBSTR(V_DEFAULT, 1, LENGTH(V_DEFAULT) - LENGTH(V_CHARSEQ)) 
            || V_CHARSEQ;
    
    RETURN V_RESULT;
END;

-- 테스트
SELECT F_CODE('H', 12340) AS TEST
FROM DUAL;

CREATE SEQUENCE TESTSEQ
NOCACHE;

DROP SEQUENCE TESTSEQ;

SELECT F_CODE('H', TESTSEQ.NEXTVAL) AS TEST
FROM DUAL;