SELECT USER
FROM DUAL;

-- ############################################################## 승범
-- member 계정 생성 프로시저 
CREATE OR REPLACE PROCEDURE CREATE_MEMBER_ACCOUNT
(
V_EMAIL     IN  VARCHAR2,
V_PW        IN  VARCHAR2,
V_NICK      IN  VARCHAR2,
V_NAME      IN  VARCHAR2,
V_TEL       IN  VARCHAR2
)
IS
BEGIN
    INSERT INTO MEMBER(MEMBER_CODE, MEMBER_SIGN_UP_DATE)
    VALUES(F_CODE('M', M_SEQ.NEXTVAL), SYSDATE);

    INSERT INTO MEMBER_PROFILE(MEMBER_EMAIL, MEMBER_CODE
                         , MEMBER_PW, MEMBER_NICKNAME
                         , MEMBER_NAME, MEMBER_TEL)
    VALUES(V_EMAIL, F_CODE('M', M_SEQ.CURRVAL)
         , V_PW, V_NICK
         , V_NAME, V_TEL);
         
    COMMIT;
END;

--HOST 계정 생성
CREATE OR REPLACE PROCEDURE CREATE_HOST_ACCOUNT
(
V_EMAIL     IN  VARCHAR2,
V_PW        IN  VARCHAR2,
V_NICK      IN  VARCHAR2,
V_NAME      IN  VARCHAR2,
V_TEL       IN  VARCHAR2
)
IS
BEGIN
    INSERT INTO HOST(HOST_CODE, HOST_SIGN_UP_DATE)
    VALUES(F_CODE('H', H_SEQ.NEXTVAL), SYSDATE);

    INSERT INTO HOST_PROFILE(HOST_EMAIL, HOST_CODE
                       , HOST_PW, HOST_NICKNAME
                       , HOST_NAME, HOST_TEL)
    VALUES(V_EMAIL, F_CODE('H', H_SEQ.CURRVAL)
         , V_PW, V_NICK
         , V_NAME, V_TEL);
         
    COMMIT;
END;

-- ############################################################## 윤상
--○ 계좌 삭제 (프로시저)
CREATE OR REPLACE PROCEDURE PRC_BANKINFO_DELETE
( V_IDENTIFY    IN VARCHAR2
, BANK_INFO     IN VARCHAR2
)
IS
    -- 선언부
    
BEGIN
    -- 실행부
    
    IF(V_IDENTIFY = 'member')
        THEN    
            DELETE 
            FROM MEMBER_EXCHANGE_BANK_INFO
            WHERE MEMBER_BANK_NUMBER = BANK_INFO;
        
            DELETE 
            FROM LOAD_REG_BANK_INFO
            WHERE MEMBER_BANK_NUMBER = BANK_INFO;
            
            DELETE 
            FROM MEMBER_BANK_INFO
            WHERE MEMBER_BANK_NUMBER = BANK_INFO;
            
            -- 커밋
            COMMIT;
            
    ELSIF(V_IDENTIFY = 'host')
        THEN
            DELETE
            FROM HOST_EXCHANGE_BANK_INFO
            WHERE HOST_BANK_NUMBER = BANK_INFO;
            
            DELETE
            FROM HOST_BANK_INFO
            WHERE HOST_BANK_NUMBER = BANK_INFO;
            
            -- 커밋
            COMMIT;
    ELSE    
        -- 예외 처리
        ROLLBACK;
   END IF;        
END;

-- 환전 신청시 충전신청내역 테이블과 충전신청계좌정보 테이블에 데이터가 추가되어야 한다.
--○ 호스트 환전 신청 프로시저
CREATE OR REPLACE PROCEDURE PRC_HOST_EXC_REG
( V_HOST_CODE         IN  VARCHAR
, V_HOST_BANK_NUMBER  IN  VARCHAR
, V_EXCHANGE_AMOUNT         IN  NUMBER
)
IS

V_HE_SEQ VARCHAR2(20) := F_CODE('HE', HE_SEQ.NEXTVAL);

BEGIN

INSERT INTO HOST_EXCHANGE_LIST(HOST_EXCHANGE_CODE, HOST_CODE, HOST_EXCHANGE_AMOUNT, HOST_EXCHANGE_DATE)
VALUES(V_HE_SEQ, V_HOST_CODE, V_EXCHANGE_AMOUNT, SYSDATE);

INSERT INTO HOST_EXCHANGE_BANK_INFO (HOST_EXCHANGE_BANK_INFO_CODE, HOST_EXCHANGE_CODE, HOST_BANK_NUMBER) 
VALUES (F_CODE('HEBIF', HEBIF_SEQ.NEXTVAL), V_HE_SEQ, V_HOST_BANK_NUMBER);
-- 커밋
COMMIT;
END;


-- 충전 신청시 충전신청내역 테이블과 충전신청계좌정보 테이블에 데이터가 추가되어야 한다.
--○ 충전 신청 프로시저
CREATE OR REPLACE PROCEDURE PRC_LOAD_REG
( V_MEMBER_CODE         IN  VARCHAR
, V_MEMBER_BANK_NUMBER  IN  VARCHAR
, V_LOAD_AMOUNT         IN  NUMBER
)
IS

V_LR_SEQ VARCHAR2(20) := F_CODE('LR', LR_SEQ.NEXTVAL);

BEGIN

INSERT INTO LOAD_REG(LOAD_REG_CODE, MEMBER_CODE, LOAD_AMOUNT, LOAD_REG_DATE)
VALUES(V_LR_SEQ, V_MEMBER_CODE, V_LOAD_AMOUNT, SYSDATE);
-- 예외처리

INSERT INTO LOAD_REG_BANK_INFO(LOAD_REG_BANK_INFO_CODE, LOAD_REG_CODE, MEMBER_BANK_NUMBER)
VALUES(F_CODE('LRBI', LRBIF_SEQ.NEXTVAL), V_LR_SEQ, V_MEMBER_BANK_NUMBER); 
-- 예외처리
-- 커밋
COMMIT;
END;


-- 환전 신청시 충전신청내역 테이블과 충전신청계좌정보 테이블에 데이터가 추가되어야 한다.
--○ 이용자 환전 신청 프로시저
CREATE OR REPLACE PROCEDURE PRC_USER_EXC_REG
( V_MEMBER_CODE         IN  VARCHAR
, V_MEMBER_BANK_NUMBER  IN  VARCHAR
, V_EXCHANGE_AMOUNT         IN  NUMBER
)
IS

V_ME_SEQ VARCHAR2(20) := F_CODE('ME', ME_SEQ.NEXTVAL);

BEGIN

INSERT INTO MEMBER_EXCHANGE_LIST(MEMBER_EXCHANGE_CODE, MEMBER_CODE, MEMBER_EXCHANGE_AMOUNT, MEMBER_EXCHANGE_DATE)
VALUES(V_ME_SEQ, V_MEMBER_CODE, V_EXCHANGE_AMOUNT, SYSDATE);

INSERT INTO MEMBER_EXCHANGE_BANK_INFO (MEMBER_EXCHANGE_BANK_INFO_CODE, MEMBER_EXCHANGE_CODE, MEMBER_BANK_NUMBER) 
VALUES (F_CODE('MEBIF', MEBIF_SEQ.NEXTVAL), V_ME_SEQ, V_MEMBER_BANK_NUMBER);
-- 커밋
COMMIT;
END;


-- ############################################################## 영은
--○ 호스트 탈퇴 : 삭제된 공간 테이블에 INSERT 
CREATE OR REPLACE PROCEDURE PRC_DEL_LOC_INSERT
(
    V_HOST_CODE IN LOC.HOST_CODE%TYPE
)
IS
    V_LOC_CODE LOC_REMOVE.LOC_CODE%TYPE;
    
    CURSOR C1 
    IS
        SELECT LOC_CODE
        FROM LOC 
        WHERE HOST_CODE = V_HOST_CODE;
BEGIN
    OPEN C1;
    
    LOOP
        FETCH C1 INTO V_LOC_CODE;
        EXIT WHEN C1%NOTFOUND;
    
    -- 해당 공간코드만큼 LOC_REMOVE 테이블에 INSERT 
        INSERT INTO LOC_REMOVE(LOC_REMOVE_CODE, LOC_CODE, LOC_REMOVE_DATE)
        VALUES(F_CODE('LRM', LRM_SEQ.NEXTVAL), V_LOC_CODE, SYSDATE);
    
    END LOOP;
    
    CLOSE C1;
    COMMIT;
    
END PRC_DEL_LOC_INSERT;



--○ 이용자 탈퇴 : 마일리지 잔액 확인
CREATE OR REPLACE PROCEDURE PRC_MEMBER_MILEAGE
(
    V_MEMBER_CODE IN BOOK_LIST.MEMBER_CODE%TYPE
,   V_CHANGE OUT PACKAGE.PACKAGE_PRICE%TYPE
)
IS  
    V_MILEAGE PACKAGE.PACKAGE_PRICE%TYPE;
BEGIN
    SELECT 
    (
        SELECT NVL(SUM(LR.LOAD_AMOUNT), 0)
        FROM LOAD_PROC LP
        JOIN LOAD_REG LR
        ON LP.LOAD_REG_CODE = LR.LOAD_REG_CODE
        WHERE LP.LOAD_TYPE_CODE='LT000001' AND LR.MEMBER_CODE = V_MEMBER_CODE
    )
    -
    (
        SELECT NVL(SUM(P.PACKAGE_PRICE), 0)
        FROM BOOK_PAY_LIST BP
        JOIN BOOK_LIST B
        ON BP.BOOK_CODE = B.BOOK_CODE
        JOIN APPLY_PACKAGE AP
        ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
        JOIN PACKAGE P 
        ON AP.PACKAGE_CODE = P.PACKAGE_CODE
        WHERE B.MEMBER_CODE = V_MEMBER_CODE
    )
    +                
    (
        SELECT NVL(SUM(P.PACKAGE_PRICE), 0)
        FROM HOST_CANCEL_LIST HC
        JOIN BOOK_REFUND_LIST BR
        ON HC.BOOK_CODE = BR.BOOK_CODE
            JOIN BOOK_LIST B
            ON BR.BOOK_CODE = B.BOOK_CODE
                JOIN APPLY_PACKAGE AP
                ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
                    JOIN PACKAGE P
                    ON AP.PACKAGE_CODE = P.PACKAGE_CODE
                    WHERE B.MEMBER_CODE = V_MEMBER_CODE
    )
    +
    (
        SELECT NVL(SUM
        (CASE WHEN (TO_DATE(AP.APPLY_DATE, 'YYYY-MM-DD') - TO_DATE(MC.MEMBER_CANCEL_DATE, 'YYYY-MM-DD')) < 7 
              THEN TRUNC(P.PACKAGE_PRICE * 0.5, -1) 
              ELSE TRUNC(P.PACKAGE_PRICE * 1, -1)
              END), 0)
        FROM MEMBER_CANCEL_LIST MC
        JOIN BOOK_REFUND_LIST BR
        ON MC.BOOK_CODE = BR.BOOK_CODE
            JOIN BOOK_LIST B
            ON BR.BOOK_CODE = B.BOOK_CODE
                JOIN APPLY_PACKAGE AP
                ON B.APPLY_PACKAGE_CODE = AP.APPLY_PACKAGE_CODE
                    JOIN PACKAGE P
                    ON AP.PACKAGE_CODE = P.PACKAGE_CODE
                    WHERE B.MEMBER_CODE = V_MEMBER_CODE
    )
    -
    (
        SELECT NVL(SUM(MEMBER_EXCHANGE_AMOUNT), 0)
        FROM MEMBER_EXCHANGE_LIST
        WHERE MEMBER_CODE = V_MEMBER_CODE
    ) 
    INTO V_MILEAGE
    FROM DUAL;

    V_CHANGE := V_MILEAGE;
    
END PRC_MEMBER_MILEAGE;


--○ 예약 신청 : 예약코드 받아 예약자 테이블, 결제, 메세지 테이블에 insert
CREATE OR REPLACE PROCEDURE PRC_BOOK_CODE_INSERT
(
    V_MEMBER_CODE IN BOOK_LIST.MEMBER_CODE%TYPE
,   V_ACTUAL_BOOKER IN ACTUAL_BOOKER.ACTUAL_BOOKER%TYPE
,   V_ACTUAL_BOOKER_TEL IN ACTUAL_BOOKER.ACTUAL_BOOKER_TEL%TYPE
)
IS
    V_BOOK_CODE BOOK_LIST.BOOK_CODE%TYPE;

BEGIN
    -- 예약번호 확인
    SELECT BOOK_CODE INTO V_BOOK_CODE 
    FROM
    (SELECT BOOK_CODE FROM BOOK_LIST WHERE MEMBER_CODE=V_MEMBER_CODE
    ORDER BY BOOK_CODE DESC)
    WHERE ROWNUM=1;
    
    -- 실예약자 테이블에 추가
    INSERT INTO ACTUAL_BOOKER (ACTUAL_BOOKER_CODE, BOOK_CODE, ACTUAL_BOOKER
    , ACTUAL_BOOKER_TEL)
    VALUES(F_CODE('AB', AB_SEQ.NEXTVAL), V_BOOK_CODE, V_ACTUAL_BOOKER
    , V_ACTUAL_BOOKER_TEL);
    
    -- 메시지 테이블에 추가
    INSERT INTO MSG(MSG_CODE, BOOK_CODE)
    VALUES(F_CODE('MSG', MSG_SEQ.NEXTVAL), V_BOOK_CODE);
    
    -- 결제내역 테이블에 추가
    INSERT INTO BOOK_PAY_LIST(BOOK_PAY_CODE, BOOK_CODE, BOOK_PAY_DATE)
    VALUES(F_CODE('BP', BP_SEQ.NEXTVAL), V_BOOK_CODE, SYSDATE);

    COMMIT;
    
END PRC_BOOK_CODE_INSERT;


--○ --○ 메시지에서 이미지 전송(이용자)
CREATE OR REPLACE PROCEDURE PRC_M_MSG_IMG
(
    V_BOOK_CODE IN BOOK_LIST.BOOK_CODE%TYPE
,   V_MSG_IMG_URL IN MEMBER_MSG_IMG.MEMBER_MSG_IMG_URL%TYPE
)
IS
    V_MSG_CODE      MEMBER_MSG_INFO.MSG_CODE%TYPE;
    V_MSG_INFO_CODE MEMBER_MSG_INFO.MEMBER_MSG_INFO_CODE%TYPE;
BEGIN
    -- 메신저 코드 검색
    SELECT MSG_CODE INTO V_MSG_CODE
    FROM MSG
    WHERE BOOK_CODE=V_BOOK_CODE;
    
    -- 텍스트가 NULL로 된 메시지 보내기
    INSERT INTO MEMBER_MSG_INFO(MEMBER_MSG_INFO_CODE, MSG_CODE, MEMBER_MSG_DATE)
    VALUES(F_CODE('MMIF', MMIF_SEQ.NEXTVAL), V_MSG_CODE, SYSDATE);

    -- 방금 보낸 메시지 번호 얻기
    -- ROWNUM 시간순으로 내림차순 정렬하고 첫번째값
    SELECT MSG_INFO_CODE INTO V_MSG_INFO_CODE
    FROM
    (SELECT A.MSG_INFO_CODE, A.BOOK_CODE
    FROM VIEW_MESSENGER A
    ORDER BY A.MSG_DATE DESC)
    WHERE ROWNUM = 1 AND BOOK_CODE=V_BOOK_CODE;

    -- 이미지 추가
    INSERT INTO MEMBER_MSG_IMG(MEMBER_MSG_IMG_CODE, MEMBER_MSG_INFO_CODE, MEMBER_MSG_IMG_URL)
    VALUES(F_CODE('MMIM', MMIF_SEQ.NEXTVAL), V_MSG_INFO_CODE, V_MSG_IMG_URL);
    
    COMMIT;
    
END PRC_M_MSG_IMG;


--○ 메시지에서 이미지 전송(호스트)
CREATE OR REPLACE PROCEDURE PRC_H_MSG_IMG
(
    V_BOOK_CODE IN BOOK_LIST.BOOK_CODE%TYPE
,   V_MSG_IMG_URL IN HOST_MSG_IMG.HOST_MSG_IMG_URL%TYPE
)
IS
    V_MSG_CODE      HOST_MSG_INFO.MSG_CODE%TYPE;
    V_MSG_INFO_CODE HOST_MSG_INFO.HOST_MSG_INFO_CODE%TYPE;
BEGIN
    -- 메신저 코드 검색
    SELECT MSG_CODE INTO V_MSG_CODE
    FROM MSG
    WHERE BOOK_CODE=V_BOOK_CODE;
    
    -- 텍스트가 NULL로 된 메시지 보내기
    INSERT INTO HOST_MSG_INFO(HOST_MSG_INFO_CODE, MSG_CODE, HOST_MSG_DATE)
    VALUES(F_CODE('HMIF', HMIF_SEQ.NEXTVAL), V_MSG_CODE, SYSDATE);
    
    -- 방금 보낸 메시지 번호 얻기
    -- ROWNUM 시간순으로 내림차순 정렬하고 첫번째값
    SELECT MSG_INFO_CODE INTO V_MSG_INFO_CODE
    FROM
    (SELECT A.MSG_INFO_CODE, A.BOOK_CODE
    FROM VIEW_MESSENGER A
    ORDER BY A.MSG_DATE DESC)
    WHERE ROWNUM = 1 AND BOOK_CODE=V_BOOK_CODE;

    -- 이미지 추가
    INSERT INTO HOST_MSG_IMG(HOST_MSG_IMG_CODE, HOST_MSG_INFO_CODE, HOST_MSG_IMG_URL)
    VALUES(F_CODE('HMIM', MMIF_SEQ.NEXTVAL), V_MSG_INFO_CODE, V_MSG_IMG_URL);
    
    COMMIT;
    
END PRC_H_MSG_IMG;


--○ 리뷰에서 이미지 전송
CREATE OR REPLACE PROCEDURE PRC_REVIEW_IMG
(
    V_LOC_CODE          IN REVIEW.LOC_CODE%TYPE
,   V_MEMBER_CODE       IN REVIEW.MEMBER_CODE%TYPE
,   V_REVIEW_RATE       IN REVIEW.REVIEW_RATE%TYPE
,   V_REVIEW_CONTENT    IN REVIEW.REVIEW_CONTENT%TYPE
,   V_REVIEW_IMG_URL    IN REVIEW_IMG.REVIEW_IMG_URL%TYPE
)
IS
    V_REVIEW_CODE       REVIEW.REVIEW_CODE%TYPE;
BEGIN
    -- 리뷰 텍스트들만 먼저 보내기 
    INSERT INTO REVIEW(REVIEW_CODE, LOC_CODE, MEMBER_CODE, REVIEW_RATE, REVIEW_CONTENT
    , REVIEW_DATE)
    VALUES(F_CODE('RV', RV_SEQ.NEXTVAL), V_LOC_CODE
    , V_MEMBER_CODE, V_REVIEW_RATE, V_REVIEW_CONTENT, SYSDATE);

    -- 방금 보낸 리뷰 번호 얻기
    SELECT REVIEW_CODE INTO V_REVIEW_CODE
    FROM
    (SELECT A.REVIEW_CODE, A.MEMBER_CODE
    FROM REVIEW A
    ORDER BY A.REVIEW_DATE DESC)
    WHERE ROWNUM = 1 AND MEMBER_CODE=V_MEMBER_CODE;

    -- 이미지 추가
    INSERT INTO REVIEW_IMG(REVIEW_IMG_CODE, REVIEW_CODE, REVIEW_IMG_URL)
    VALUES(F_CODE('RVIMG', RVIMG_SEQ.NEXTVAL), V_REVIEW_CODE, V_REVIEW_IMG_URL);

    COMMIT;

END PRC_REVIEW_IMG;














